/*
 * Created on 18 Jul 2017 ( Time 08:39:33 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 
package com.nsw.backend.mard.p25.model;

import lombok.Data;

import javax.persistence.*;
import java.io.Serializable;

/**
 * Persistent class for entity stored in table "TBDDVXL06" - Đơn vị xử lý
 *
 * @author Telosys Tools Generator
 */
@Entity
@Data
@Table(name = "TBDDVXL25", schema = "MARD")
public class TbdDonViXuLy25 implements Serializable {
    private static final long serialVersionUID = 1L;

    public static final String SEQUENCE_NAME = "TBDDVXL25_SEQ";

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(nullable = false)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = SEQUENCE_NAME)
    @SequenceGenerator(sequenceName = SEQUENCE_NAME, schema = "MARD", initialValue = 1, allocationSize = 1, name = SEQUENCE_NAME)
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS
    //----------------------------------------------------------------------
    @Column(name = "FI_PU_CODE")
    private String fiPUCode;

    @Column(name = "FI_PU_DESC")
    private String fiPUDesc;

    @Column(name = "FI_PU_LOCATION")
    private String fiPULocation;

    public TbdDonViXuLy25() {
    }

    public TbdDonViXuLy25(String fiPUCode, String fiPUDesc, String fiPULocation) {
        this.fiPUCode = fiPUCode;
        this.fiPUDesc = fiPUDesc;
        this.fiPULocation = fiPULocation;
    }
}
