/*
 * Created on 18 Jul 2017 ( Time 08:54:01 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 
package com.nsw.mard.p11.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
//import javax.persistence.*;

/**
 * Persistent class for entity stored in table "TBDGCN11"
 *
 * //@author Telosys Tools Generator
 *
 */
//@Entity
//@Table(name = "TBDGCN11", schema = "MARD")
// Define named queries here
//@NamedQueries({
    //@NamedQuery(name = "Tbdgcn11.countAll", query = "SELECT COUNT(x) FROM Tbdgcn11 x")
//})
public class Tbdgcn11 implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    //@Id
    //@Column(name = "FI_ID_GCN", nullable = false)
    //@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "TBDGCN11_SEQ")
    //@SequenceGenerator(sequenceName = "TBDGCN11_SEQ", schema = "MARD", initialValue = 1, allocationSize = 1, name = "TBDGCN11_SEQ")
    private Long fiIdGcn;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    //@Column(name = "FI_ID_HOSO", nullable = false)
    private Long fiIdHoso;

    //@Column(name = "FI_MA_HOSO", nullable = false, length = 12)
    private String fiMaHoso;

    //@Column(name = "FI_LOAI_CT", nullable = false)
    private Long fiLoaiCt;

    //@Column(name = "FI_TENNUOC_XK", nullable = false, length = 35)
    private String fiTennuocXk;

    //@Column(name = "FI_MANUOC_XK", nullable = false, length = 2)
    private String fiManuocXk;

    //@Column(name = "FI_TENNUOC_QC", nullable = false, length = 35)
    private String fiTennuocQc;

    //@Column(name = "FI_MANUOC_QC", nullable = false, length = 2)
    private String fiManuocQc;

    //@Column(name = "FI_SO_GCN", nullable = false, length = 50)
    private String fiSoGcn;

    //@Column(name = "FI_NGUOI_XK", nullable = false, length = 500)
    private String fiNguoiXk;

    //@Column(name = "FI_DIACHI_XK", nullable = false, length = 500)
    private String fiDiachiXk;

    //@Column(name = "FI_TEN_NN", nullable = false, length = 500)
    private String fiTenNn;

    //@Column(name = "FI_DIACHI_NN", nullable = false, length = 500)
    private String fiDiachiNn;
    
    //@Column(name = "FI_SOLUONG")
    private BigDecimal fiSoluong;

    //@Column(name = "FI_TENBAOBI", nullable = false, length = 255)
    private String fiTenbaobi;

    //@Column(name = "FI_MABAOBI", nullable = false, length = 2)
    private String fiMabaobi;

    //@Column(name = "FI_HIENTHI", nullable = false, length = 255)
    private String fiHienthi;

    //@Column(name = "FI_QUYCACH_DG", nullable = false)
    private Long fiQuycachDg;

    //@Column(name = "FI_MAKYHIEU", nullable = false, length = 500)
    private String fiMakyhieu;

    //@Column(name = "FI_TEN_NSX", length = 35)
    private String fiTenNsx;

    //@Column(name = "FI_DIACHI_NSX", length = 250)
    private String fiDiachiNsx;

    //@Column(name = "FI_TENNUOC_SX", nullable = false, length = 35)
    private String fiTennuocSx;

    //@Column(name = "FI_MANUOC_SX", nullable = false, length = 2)
    private String fiManuocSx;

    //@Column(name = "FI_TENTINH", length = 35)
    private String fiTentinh;

    //@Column(name = "FI_MATINH", length = 2)
    private String fiMatinh;

    //@Column(name = "FI_HTCC", nullable = false)
    private Long fiHtcc;

    //@Column(name = "FI_PTCC", nullable = false, length = 250)
    private String fiPtcc;

    //@Column(name = "FI_SOHIEU_PT", length = 250)
    private String fiSohieuPt;

    //@Column(name = "FI_CK_NHAP", nullable = false, length = 250)
    private String fiCkNhap;

    //@Column(name = "FI_MADV_KL", length = 18)
    private String fiMadvKl;

    //@Column(name = "FI_TENDV_KL", length = 255)
    private String fiTendvKl;

    //@Column(name = "FI_HIENTHI_KL", length = 255)
    private String fiHienthiKl;

    //@Column(name = "FI_MADV_BI", length = 18)
    private String fiMadvBi;

    //@Column(name = "FI_TENDV_BI", length = 255)
    private String fiTendvBi;

    //@Column(name = "FI_HIENTHI_BI", length = 255)
    private String fiHienthiBi;

    //@Column(name = "FI_TUNUOC", length = 255)
    private String fiTunuoc;

    //@Column(name = "FI_SOCNKDTV", length = 250)
    private String fiSocnkdtv;

    //@Column(name = "FI_BANGOC")
    private Long fiBangoc;

    //@Column(name = "FI_BANSAO")
    private Long fiBansao;

    //@Column(name = "FI_DADONGGOI")
    private Long fiDadonggoi;

    //@Column(name = "FI_DAGOILAI")
    private Long fiDagoilai;

    //@Column(name = "FI_GIUNGUYENGOC")
    private Long fiGiunguyengoc;

    //@Column(name = "FI_BAOBIMOI")
    private Long fiBaobimoi;

    //@Column(name = "FI_TRENCS_GOC")
    private Long fiTrencsGoc;

    //@Column(name = "FI_KT_BOSUNG")
    private Long fiKtBosung;

    //@Column(name = "FI_KB_BOSUNG", length = 500)
    private String fiKbBosung;

    //@Column(name = "FI_NGAY", length = 10)
    private String fiNgay;

    //@Column(name = "FI_MA_PPXL")
    private Long fiMaPpxl;

    //@Column(name = "FI_TEN_PPXL", length = 256)
    private String fiTenPpxl;

    //@Column(name = "FI_TENTHUOC", length = 256)
    private String fiTenthuoc;

    //@Column(name = "FI_NONGDO", length = 256)
    private String fiNongdo;

    //@Column(name = "FI_TG_ND", length = 256)
    private String fiTgNd;

    //@Column(name = "FI_TT_THEM", length = 256)
    private String fiTtThem;

    //@Column(name = "FI_NOICAPGIAY", length = 256)
    private String fiNoicapgiay;

    //@Column(name = "FI_NGAYCAP", length = 10)
    private String fiNgaycap;

    //@Column(name = "FI_CHUCVU_CB", length = 256)
    private String fiChucvuCb;

    //@Column(name = "FI_TEN_CB", length = 256)
    private String fiTenCb;

    //@Column(name = "FI_LYDOSUA", length = 256)
    private String fiLydosua;

    //@Column(name = "FI_HOATDONG", nullable = false)
    private Long fiHoatdong;

    //@Temporal(TemporalType.TIMESTAMP)
    //@Column(name = "FI_NGAYTAO", nullable = false)
    private Date fiNgaytao;

    //@Temporal(TemporalType.TIMESTAMP)
    //@Column(name = "FI_NGAY_CN")
    private Date fiNgayCn;

    //@Column(name = "FI_TONGKLTINH")
    private BigDecimal fiTongkltinh;

    //@Column(name = "FI_TONGKLBI")
    private BigDecimal fiTongklbi;
    
    //@Column(name = "FI_KBBS", length = 2000)
    private String fiKbbs;
    
    //@Column(name = "FI_TEN_LOAI_CT", length = 250)
    private String fiTenLoaiCt;
    
   //@Column(name = "FI_TEN_QUYCACH_DG", length = 250)
    private String fiTenQuycachDg;
   
   //@Column(name = "FI_TEN_HTCC", length = 250)
    private String fiTenHtcc;

    public String getFiTenLoaiCt() {
        return fiTenLoaiCt;
    }

    public void setFiTenLoaiCt(String fiTenLoaiCt) {
        this.fiTenLoaiCt = fiTenLoaiCt;
    }

    public String getFiTenQuycachDg() {
        return fiTenQuycachDg;
    }

    public void setFiTenQuycachDg(String fiTenQuycachDg) {
        this.fiTenQuycachDg = fiTenQuycachDg;
    }

    public String getFiTenHtcc() {
        return fiTenHtcc;
    }

    public void setFiTenHtcc(String fiTenHtcc) {
        this.fiTenHtcc = fiTenHtcc;
    }
    
    //@Transient
    private List<Tbdhhgcn11> tbdhhgcn11;

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Tbdgcn11() {
        super();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------

    public String getFiKbbs() {
        return fiKbbs;
    }

    public void setFiKbbs(String fiKbbs) {
        this.fiKbbs = fiKbbs;
    }
    

    public Long getFiIdGcn() {
        return fiIdGcn;
    }

    public void setFiIdGcn(Long fiIdGcn) {
        this.fiIdGcn = fiIdGcn;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : FI_ID_HOSO ( NUMBER ) 
    public void setFiIdHoso(Long fiIdHoso) {
        this.fiIdHoso = fiIdHoso;
    }

    public Long getFiIdHoso() {
        return this.fiIdHoso;
    }

    //--- DATABASE MAPPING : FI_MA_HOSO ( VARCHAR2 ) 
    public void setFiMaHoso(String fiMaHoso) {
        this.fiMaHoso = fiMaHoso;
    }

    public String getFiMaHoso() {
        return this.fiMaHoso;
    }

    //--- DATABASE MAPPING : FI_LOAI_CT ( NUMBER ) 
    public void setFiLoaiCt(Long fiLoaiCt) {
        this.fiLoaiCt = fiLoaiCt;
    }

    public Long getFiLoaiCt() {
        return this.fiLoaiCt;
    }

    //--- DATABASE MAPPING : FI_TENNUOC_XK ( VARCHAR2 ) 
    public void setFiTennuocXk(String fiTennuocXk) {
        this.fiTennuocXk = fiTennuocXk;
    }

    public String getFiTennuocXk() {
        return this.fiTennuocXk;
    }

    //--- DATABASE MAPPING : FI_MANUOC_XK ( VARCHAR2 ) 
    public void setFiManuocXk(String fiManuocXk) {
        this.fiManuocXk = fiManuocXk;
    }

    public String getFiManuocXk() {
        return this.fiManuocXk;
    }

    //--- DATABASE MAPPING : FI_TENNUOC_QC ( VARCHAR2 ) 
    public void setFiTennuocQc(String fiTennuocQc) {
        this.fiTennuocQc = fiTennuocQc;
    }

    public String getFiTennuocQc() {
        return this.fiTennuocQc;
    }

    //--- DATABASE MAPPING : FI_MANUOC_QC ( VARCHAR2 ) 
    public void setFiManuocQc(String fiManuocQc) {
        this.fiManuocQc = fiManuocQc;
    }

    public String getFiManuocQc() {
        return this.fiManuocQc;
    }

    //--- DATABASE MAPPING : FI_SO_GCN ( VARCHAR2 ) 
    public void setFiSoGcn(String fiSoGcn) {
        this.fiSoGcn = fiSoGcn;
    }

    public String getFiSoGcn() {
        return this.fiSoGcn;
    }

    //--- DATABASE MAPPING : FI_NGUOI_XK ( VARCHAR2 ) 
    public void setFiNguoiXk(String fiNguoiXk) {
        this.fiNguoiXk = fiNguoiXk;
    }

    public String getFiNguoiXk() {
        return this.fiNguoiXk;
    }

    //--- DATABASE MAPPING : FI_DIACHI_XK ( VARCHAR2 ) 
    public void setFiDiachiXk(String fiDiachiXk) {
        this.fiDiachiXk = fiDiachiXk;
    }

    public String getFiDiachiXk() {
        return this.fiDiachiXk;
    }

    //--- DATABASE MAPPING : FI_TEN_NN ( VARCHAR2 ) 
    public void setFiTenNn(String fiTenNn) {
        this.fiTenNn = fiTenNn;
    }

    public String getFiTenNn() {
        return this.fiTenNn;
    }

    //--- DATABASE MAPPING : FI_DIACHI_NN ( VARCHAR2 ) 
    public void setFiDiachiNn(String fiDiachiNn) {
        this.fiDiachiNn = fiDiachiNn;
    }

    public String getFiDiachiNn() {
        return this.fiDiachiNn;
    }

    //--- DATABASE MAPPING : FI_TENBAOBI ( VARCHAR2 ) 
    public void setFiTenbaobi(String fiTenbaobi) {
        this.fiTenbaobi = fiTenbaobi;
    }

    public String getFiTenbaobi() {
        return this.fiTenbaobi;
    }

    //--- DATABASE MAPPING : FI_MABAOBI ( VARCHAR2 ) 
    public void setFiMabaobi(String fiMabaobi) {
        this.fiMabaobi = fiMabaobi;
    }

    public String getFiMabaobi() {
        return this.fiMabaobi;
    }

    //--- DATABASE MAPPING : FI_HIENTHI ( VARCHAR2 ) 
    public void setFiHienthi(String fiHienthi) {
        this.fiHienthi = fiHienthi;
    }

    public String getFiHienthi() {
        return this.fiHienthi;
    }

    //--- DATABASE MAPPING : FI_QUYCACH_DG ( NUMBER ) 
    public void setFiQuycachDg(Long fiQuycachDg) {
        this.fiQuycachDg = fiQuycachDg;
    }

    public Long getFiQuycachDg() {
        return this.fiQuycachDg;
    }

    //--- DATABASE MAPPING : FI_MAKYHIEU ( VARCHAR2 ) 
    public void setFiMakyhieu(String fiMakyhieu) {
        this.fiMakyhieu = fiMakyhieu;
    }

    public String getFiMakyhieu() {
        return this.fiMakyhieu;
    }

    //--- DATABASE MAPPING : FI_TEN_NSX ( VARCHAR2 ) 
    public void setFiTenNsx(String fiTenNsx) {
        this.fiTenNsx = fiTenNsx;
    }

    public String getFiTenNsx() {
        return this.fiTenNsx;
    }

    //--- DATABASE MAPPING : FI_DIACHI_NSX ( VARCHAR2 ) 
    public void setFiDiachiNsx(String fiDiachiNsx) {
        this.fiDiachiNsx = fiDiachiNsx;
    }

    public String getFiDiachiNsx() {
        return this.fiDiachiNsx;
    }

    //--- DATABASE MAPPING : FI_TENNUOC_SX ( VARCHAR2 ) 
    public void setFiTennuocSx(String fiTennuocSx) {
        this.fiTennuocSx = fiTennuocSx;
    }

    public String getFiTennuocSx() {
        return this.fiTennuocSx;
    }

    //--- DATABASE MAPPING : FI_MANUOC_SX ( VARCHAR2 ) 
    public void setFiManuocSx(String fiManuocSx) {
        this.fiManuocSx = fiManuocSx;
    }

    public String getFiManuocSx() {
        return this.fiManuocSx;
    }

    //--- DATABASE MAPPING : FI_TENTINH ( VARCHAR2 ) 
    public void setFiTentinh(String fiTentinh) {
        this.fiTentinh = fiTentinh;
    }

    public String getFiTentinh() {
        return this.fiTentinh;
    }

    //--- DATABASE MAPPING : FI_MATINH ( VARCHAR2 ) 
    public void setFiMatinh(String fiMatinh) {
        this.fiMatinh = fiMatinh;
    }

    public String getFiMatinh() {
        return this.fiMatinh;
    }

    //--- DATABASE MAPPING : FI_HTCC ( NUMBER ) 
    public void setFiHtcc(Long fiHtcc) {
        this.fiHtcc = fiHtcc;
    }

    public Long getFiHtcc() {
        return this.fiHtcc;
    }

    //--- DATABASE MAPPING : FI_PTCC ( VARCHAR2 ) 
    public void setFiPtcc(String fiPtcc) {
        this.fiPtcc = fiPtcc;
    }

    public String getFiPtcc() {
        return this.fiPtcc;
    }

    //--- DATABASE MAPPING : FI_SOHIEU_PT ( VARCHAR2 ) 
    public void setFiSohieuPt(String fiSohieuPt) {
        this.fiSohieuPt = fiSohieuPt;
    }

    public String getFiSohieuPt() {
        return this.fiSohieuPt;
    }

    //--- DATABASE MAPPING : FI_CK_NHAP ( VARCHAR2 ) 
    public void setFiCkNhap(String fiCkNhap) {
        this.fiCkNhap = fiCkNhap;
    }

    public String getFiCkNhap() {
        return this.fiCkNhap;
    }

    //--- DATABASE MAPPING : FI_MADV_KL ( VARCHAR2 ) 
    public void setFiMadvKl(String fiMadvKl) {
        this.fiMadvKl = fiMadvKl;
    }

    public String getFiMadvKl() {
        return this.fiMadvKl;
    }

    //--- DATABASE MAPPING : FI_TENDV_KL ( VARCHAR2 ) 
    public void setFiTendvKl(String fiTendvKl) {
        this.fiTendvKl = fiTendvKl;
    }

    public String getFiTendvKl() {
        return this.fiTendvKl;
    }

    //--- DATABASE MAPPING : FI_HIENTHI_KL ( VARCHAR2 ) 
    public void setFiHienthiKl(String fiHienthiKl) {
        this.fiHienthiKl = fiHienthiKl;
    }

    public String getFiHienthiKl() {
        return this.fiHienthiKl;
    }

    //--- DATABASE MAPPING : FI_MADV_BI ( VARCHAR2 ) 
    public void setFiMadvBi(String fiMadvBi) {
        this.fiMadvBi = fiMadvBi;
    }

    public String getFiMadvBi() {
        return this.fiMadvBi;
    }

    //--- DATABASE MAPPING : FI_TENDV_BI ( VARCHAR2 ) 
    public void setFiTendvBi(String fiTendvBi) {
        this.fiTendvBi = fiTendvBi;
    }

    public String getFiTendvBi() {
        return this.fiTendvBi;
    }

    //--- DATABASE MAPPING : FI_HIENTHI_BI ( VARCHAR2 ) 
    public void setFiHienthiBi(String fiHienthiBi) {
        this.fiHienthiBi = fiHienthiBi;
    }

    public String getFiHienthiBi() {
        return this.fiHienthiBi;
    }

    //--- DATABASE MAPPING : FI_TUNUOC ( VARCHAR2 ) 
    public void setFiTunuoc(String fiTunuoc) {
        this.fiTunuoc = fiTunuoc;
    }

    public String getFiTunuoc() {
        return this.fiTunuoc;
    }

    //--- DATABASE MAPPING : FI_SOCNKDTV ( VARCHAR2 ) 
    public void setFiSocnkdtv(String fiSocnkdtv) {
        this.fiSocnkdtv = fiSocnkdtv;
    }

    public String getFiSocnkdtv() {
        return this.fiSocnkdtv;
    }

    //--- DATABASE MAPPING : FI_BANGOC ( NUMBER ) 
    public void setFiBangoc(Long fiBangoc) {
        this.fiBangoc = fiBangoc;
    }

    public Long getFiBangoc() {
        return this.fiBangoc;
    }

    //--- DATABASE MAPPING : FI_BANSAO ( NUMBER ) 
    public void setFiBansao(Long fiBansao) {
        this.fiBansao = fiBansao;
    }

    public Long getFiBansao() {
        return this.fiBansao;
    }

    //--- DATABASE MAPPING : FI_DADONGGOI ( NUMBER ) 
    public void setFiDadonggoi(Long fiDadonggoi) {
        this.fiDadonggoi = fiDadonggoi;
    }

    public Long getFiDadonggoi() {
        return this.fiDadonggoi;
    }

    //--- DATABASE MAPPING : FI_DAGOILAI ( NUMBER ) 
    public void setFiDagoilai(Long fiDagoilai) {
        this.fiDagoilai = fiDagoilai;
    }

    public Long getFiDagoilai() {
        return this.fiDagoilai;
    }

    //--- DATABASE MAPPING : FI_GIUNGUYENGOC ( NUMBER ) 
    public void setFiGiunguyengoc(Long fiGiunguyengoc) {
        this.fiGiunguyengoc = fiGiunguyengoc;
    }

    public Long getFiGiunguyengoc() {
        return this.fiGiunguyengoc;
    }

    //--- DATABASE MAPPING : FI_BAOBIMOI ( NUMBER ) 
    public void setFiBaobimoi(Long fiBaobimoi) {
        this.fiBaobimoi = fiBaobimoi;
    }

    public Long getFiBaobimoi() {
        return this.fiBaobimoi;
    }

    //--- DATABASE MAPPING : FI_TRENCS_GOC ( NUMBER ) 
    public void setFiTrencsGoc(Long fiTrencsGoc) {
        this.fiTrencsGoc = fiTrencsGoc;
    }

    public Long getFiTrencsGoc() {
        return this.fiTrencsGoc;
    }

    //--- DATABASE MAPPING : FI_KT_BOSUNG ( NUMBER ) 
    public void setFiKtBosung(Long fiKtBosung) {
        this.fiKtBosung = fiKtBosung;
    }

    public Long getFiKtBosung() {
        return this.fiKtBosung;
    }

    //--- DATABASE MAPPING : FI_KB_BOSUNG ( VARCHAR2 ) 
    public void setFiKbBosung(String fiKbBosung) {
        this.fiKbBosung = fiKbBosung;
    }

    public String getFiKbBosung() {
        return this.fiKbBosung;
    }

    //--- DATABASE MAPPING : FI_NGAY ( VARCHAR2 ) 
    public void setFiNgay(String fiNgay) {
        this.fiNgay = fiNgay;
    }

    public String getFiNgay() {
        return this.fiNgay;
    }

    //--- DATABASE MAPPING : FI_MA_PPXL ( NUMBER ) 
    public void setFiMaPpxl(Long fiMaPpxl) {
        this.fiMaPpxl = fiMaPpxl;
    }

    public Long getFiMaPpxl() {
        return this.fiMaPpxl;
    }

    //--- DATABASE MAPPING : FI_TEN_PPXL ( VARCHAR2 ) 
    public void setFiTenPpxl(String fiTenPpxl) {
        this.fiTenPpxl = fiTenPpxl;
    }

    public String getFiTenPpxl() {
        return this.fiTenPpxl;
    }

    //--- DATABASE MAPPING : FI_TENTHUOC ( VARCHAR2 ) 
    public void setFiTenthuoc(String fiTenthuoc) {
        this.fiTenthuoc = fiTenthuoc;
    }

    public String getFiTenthuoc() {
        return this.fiTenthuoc;
    }

    //--- DATABASE MAPPING : FI_NONGDO ( VARCHAR2 ) 
    public void setFiNongdo(String fiNongdo) {
        this.fiNongdo = fiNongdo;
    }

    public String getFiNongdo() {
        return this.fiNongdo;
    }

    //--- DATABASE MAPPING : FI_TG_ND ( VARCHAR2 ) 
    public void setFiTgNd(String fiTgNd) {
        this.fiTgNd = fiTgNd;
    }

    public String getFiTgNd() {
        return this.fiTgNd;
    }

    //--- DATABASE MAPPING : FI_TT_THEM ( VARCHAR2 ) 
    public void setFiTtThem(String fiTtThem) {
        this.fiTtThem = fiTtThem;
    }

    public String getFiTtThem() {
        return this.fiTtThem;
    }

    //--- DATABASE MAPPING : FI_NOICAPGIAY ( VARCHAR2 ) 
    public void setFiNoicapgiay(String fiNoicapgiay) {
        this.fiNoicapgiay = fiNoicapgiay;
    }

    public String getFiNoicapgiay() {
        return this.fiNoicapgiay;
    }

    //--- DATABASE MAPPING : FI_NGAYCAP ( VARCHAR2 ) 
    public void setFiNgaycap(String fiNgaycap) {
        this.fiNgaycap = fiNgaycap;
    }

    public String getFiNgaycap() {
        return this.fiNgaycap;
    }

    //--- DATABASE MAPPING : FI_CHUCVU_CB ( VARCHAR2 ) 
    public void setFiChucvuCb(String fiChucvuCb) {
        this.fiChucvuCb = fiChucvuCb;
    }

    public String getFiChucvuCb() {
        return this.fiChucvuCb;
    }

    //--- DATABASE MAPPING : FI_TEN_CB ( VARCHAR2 ) 
    public void setFiTenCb(String fiTenCb) {
        this.fiTenCb = fiTenCb;
    }

    public String getFiTenCb() {
        return this.fiTenCb;
    }

    //--- DATABASE MAPPING : FI_LYDOSUA ( VARCHAR2 ) 
    public void setFiLydosua(String fiLydosua) {
        this.fiLydosua = fiLydosua;
    }

    public String getFiLydosua() {
        return this.fiLydosua;
    }

    //--- DATABASE MAPPING : FI_HOATDONG ( NUMBER ) 
    public void setFiHoatdong(Long fiHoatdong) {
        this.fiHoatdong = fiHoatdong;
    }

    public Long getFiHoatdong() {
        return this.fiHoatdong;
    }

    //--- DATABASE MAPPING : FI_NGAYTAO ( DATE ) 
    public void setFiNgaytao(Date fiNgaytao) {
        this.fiNgaytao = fiNgaytao;
    }

    public Date getFiNgaytao() {
        return this.fiNgaytao;
    }

    //--- DATABASE MAPPING : FI_NGAY_CN ( DATE ) 
    public void setFiNgayCn(Date fiNgayCn) {
        this.fiNgayCn = fiNgayCn;
    }

    public Date getFiNgayCn() {
        return this.fiNgayCn;
    }

    //--- DATABASE MAPPING : FI_SOLUONG ( NUMBER ) 
    public void setFiSoluong(BigDecimal fiSoluong) {
        this.fiSoluong = fiSoluong;
    }

    public BigDecimal getFiSoluong() {
        return this.fiSoluong;
    }

    //--- DATABASE MAPPING : FI_TONGKLTINH ( NUMBER ) 
    public void setFiTongkltinh(BigDecimal fiTongkltinh) {
        this.fiTongkltinh = fiTongkltinh;
    }

    public BigDecimal getFiTongkltinh() {
        return this.fiTongkltinh;
    }

    //--- DATABASE MAPPING : FI_TONGKLBI ( NUMBER ) 
    public void setFiTongklbi(BigDecimal fiTongklbi) {
        this.fiTongklbi = fiTongklbi;
    }

    public BigDecimal getFiTongklbi() {
        return this.fiTongklbi;
    }

    public List<Tbdhhgcn11> getTbdhhgcn11() {
        return tbdhhgcn11;
    }

    public void setTbdhhgcn11(List<Tbdhhgcn11> tbdhhgcn11) {
        this.tbdhhgcn11 = tbdhhgcn11;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("[");
        sb.append(fiIdGcn);
        sb.append("]:");
        sb.append(fiIdHoso);
        sb.append("|");
        sb.append(fiMaHoso);
        sb.append("|");
        sb.append(fiLoaiCt);
        sb.append("|");
        sb.append(fiTennuocXk);
        sb.append("|");
        sb.append(fiManuocXk);
        sb.append("|");
        sb.append(fiTennuocQc);
        sb.append("|");
        sb.append(fiManuocQc);
        sb.append("|");
        sb.append(fiSoGcn);
        sb.append("|");
        sb.append(fiNguoiXk);
        sb.append("|");
        sb.append(fiDiachiXk);
        sb.append("|");
        sb.append(fiTenNn);
        sb.append("|");
        sb.append(fiDiachiNn);
        sb.append("|");
        sb.append(fiTenbaobi);
        sb.append("|");
        sb.append(fiMabaobi);
        sb.append("|");
        sb.append(fiHienthi);
        sb.append("|");
        sb.append(fiQuycachDg);
        sb.append("|");
        sb.append(fiMakyhieu);
        sb.append("|");
        sb.append(fiTenNsx);
        sb.append("|");
        sb.append(fiDiachiNsx);
        sb.append("|");
        sb.append(fiTennuocSx);
        sb.append("|");
        sb.append(fiManuocSx);
        sb.append("|");
        sb.append(fiTentinh);
        sb.append("|");
        sb.append(fiMatinh);
        sb.append("|");
        sb.append(fiHtcc);
        sb.append("|");
        sb.append(fiPtcc);
        sb.append("|");
        sb.append(fiSohieuPt);
        sb.append("|");
        sb.append(fiCkNhap);
        sb.append("|");
        sb.append(fiMadvKl);
        sb.append("|");
        sb.append(fiTendvKl);
        sb.append("|");
        sb.append(fiHienthiKl);
        sb.append("|");
        sb.append(fiMadvBi);
        sb.append("|");
        sb.append(fiTendvBi);
        sb.append("|");
        sb.append(fiHienthiBi);
        sb.append("|");
        sb.append(fiTunuoc);
        sb.append("|");
        sb.append(fiSocnkdtv);
        sb.append("|");
        sb.append(fiBangoc);
        sb.append("|");
        sb.append(fiBansao);
        sb.append("|");
        sb.append(fiDadonggoi);
        sb.append("|");
        sb.append(fiDagoilai);
        sb.append("|");
        sb.append(fiGiunguyengoc);
        sb.append("|");
        sb.append(fiBaobimoi);
        sb.append("|");
        sb.append(fiTrencsGoc);
        sb.append("|");
        sb.append(fiKtBosung);
        sb.append("|");
        sb.append(fiKbBosung);
        sb.append("|");
        sb.append(fiNgay);
        sb.append("|");
        sb.append(fiMaPpxl);
        sb.append("|");
        sb.append(fiTenPpxl);
        sb.append("|");
        sb.append(fiTenthuoc);
        sb.append("|");
        sb.append(fiNongdo);
        sb.append("|");
        sb.append(fiTgNd);
        sb.append("|");
        sb.append(fiTtThem);
        sb.append("|");
        sb.append(fiNoicapgiay);
        sb.append("|");
        sb.append(fiNgaycap);
        sb.append("|");
        sb.append(fiChucvuCb);
        sb.append("|");
        sb.append(fiTenCb);
        sb.append("|");
        sb.append(fiLydosua);
        sb.append("|");
        sb.append(fiHoatdong);
        sb.append("|");
        sb.append(fiNgaytao);
        sb.append("|");
        sb.append(fiNgayCn);
        sb.append("|");
        sb.append(fiSoluong);
        sb.append("|");
        sb.append(fiTongkltinh);
        sb.append("|");
        sb.append(fiTongklbi);
        return sb.toString();
    }

}
