/*
 * Created on 18 Jul 2017 ( Time 08:54:42 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 
package com.nsw.mard.p11.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
//import javax.persistence.*;

/**
 * Persistent class for entity stored in table "TBDHHGCN11"
 *
 * //@author Telosys Tools Generator
 *
 */
//@Entity
//@Table(name = "TBDHHGCN11", schema = "MARD")
// Define named queries here
//@NamedQueries({
    //@NamedQuery(name = "Tbdhhgcn11.countAll", query = "SELECT COUNT(x) FROM Tbdhhgcn11 x")
//})
public class Tbdhhgcn11 implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    //@Id
    //@Column(name = "FI_ID_HH", nullable = false)
    //@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "TBDHHGCN11_SEQ")
    //@SequenceGenerator(sequenceName = "TBDHHGCN11_SEQ", schema = "MARD", initialValue = 1, allocationSize = 1, name = "TBDHHGCN11_SEQ")
    private Long fiIdHh;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    //@Column(name = "FI_TEN_HH", nullable = false, length = 500)
    private String fiTenHh;

    //@Column(name = "FI_TEN_KH", length = 500)
    private String fiTenKh;

    //@Column(name = "FI_MADV_SL", length = 18)
    private String fiMadvSl;

    //@Column(name = "FI_TENDV_SL", length = 255)
    private String fiTendvSl;

    //@Column(name = "FI_MADV_KL", length = 18)
    private String fiMadvKl;

    //@Column(name = "FI_TENDV_KL", length = 255)
    private String fiTendvKl;

    //@Column(name = "FI_MADV_BI", length = 18)
    private String fiMadvBi;

    //@Column(name = "FI_TENDV_BI", length = 255)
    private String fiTendvBi;

    //@Column(name = "FI_MADV_TT", length = 18)
    private String fiMadvTt;

    //@Column(name = "FI_TENDV_TT", length = 255)
    private String fiTendvTt;

    //@Column(name = "FI_MADV_TTBI", length = 18)
    private String fiMadvTtbi;

    //@Column(name = "FI_TENDV_TTBI", length = 255)
    private String fiTendvTtbi;

    //@Column(name = "FI_ID_GCN")
    private Long fiIdGcn;

    //@Column(name = "FI_STT")
    private Long fiStt;

    //@Column(name = "FI_HOATDONG")
    private Long fiHoatdong;

    //@Temporal(TemporalType.TIMESTAMP)
    //@Column(name = "FI_NGAYTAO")
    private Date fiNgaytao;

    //@Temporal(TemporalType.TIMESTAMP)
    //@Column(name = "FI_NGAY_CN")
    private Date fiNgayCn;

    //@Column(name = "FI_SOLUONG")
    private BigDecimal fiSoluong;

    //@Column(name = "FI_KHOILUONG")
    private BigDecimal fiKhoiluong;

    //@Column(name = "FI_KLBI")
    private BigDecimal fiKlbi;

    //@Column(name = "FI_THETICH")
    private BigDecimal fiThetich;

    //@Column(name = "FI_THETICHBI")
    private BigDecimal fiThetichbi;

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Tbdhhgcn11() {
        super();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setFiIdHh(Long fiIdHh) {
        this.fiIdHh = fiIdHh;
    }

    public Long getFiIdHh() {
        return this.fiIdHh;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : FI_TEN_HH ( VARCHAR2 ) 
    public void setFiTenHh(String fiTenHh) {
        this.fiTenHh = fiTenHh;
    }

    public String getFiTenHh() {
        return this.fiTenHh;
    }

    //--- DATABASE MAPPING : FI_TEN_KH ( VARCHAR2 ) 
    public void setFiTenKh(String fiTenKh) {
        this.fiTenKh = fiTenKh;
    }

    public String getFiTenKh() {
        return this.fiTenKh;
    }

    //--- DATABASE MAPPING : FI_MADV_SL ( VARCHAR2 ) 
    public void setFiMadvSl(String fiMadvSl) {
        this.fiMadvSl = fiMadvSl;
    }

    public String getFiMadvSl() {
        return this.fiMadvSl;
    }

    //--- DATABASE MAPPING : FI_TENDV_SL ( VARCHAR2 ) 
    public void setFiTendvSl(String fiTendvSl) {
        this.fiTendvSl = fiTendvSl;
    }

    public String getFiTendvSl() {
        return this.fiTendvSl;
    }

    //--- DATABASE MAPPING : FI_MADV_KL ( VARCHAR2 ) 
    public void setFiMadvKl(String fiMadvKl) {
        this.fiMadvKl = fiMadvKl;
    }

    public String getFiMadvKl() {
        return this.fiMadvKl;
    }

    //--- DATABASE MAPPING : FI_TENDV_KL ( VARCHAR2 ) 
    public void setFiTendvKl(String fiTendvKl) {
        this.fiTendvKl = fiTendvKl;
    }

    public String getFiTendvKl() {
        return this.fiTendvKl;
    }

    //--- DATABASE MAPPING : FI_MADV_BI ( VARCHAR2 ) 
    public void setFiMadvBi(String fiMadvBi) {
        this.fiMadvBi = fiMadvBi;
    }

    public String getFiMadvBi() {
        return this.fiMadvBi;
    }

    //--- DATABASE MAPPING : FI_TENDV_BI ( VARCHAR2 ) 
    public void setFiTendvBi(String fiTendvBi) {
        this.fiTendvBi = fiTendvBi;
    }

    public String getFiTendvBi() {
        return this.fiTendvBi;
    }

    //--- DATABASE MAPPING : FI_MADV_TT ( VARCHAR2 ) 
    public void setFiMadvTt(String fiMadvTt) {
        this.fiMadvTt = fiMadvTt;
    }

    public String getFiMadvTt() {
        return this.fiMadvTt;
    }

    //--- DATABASE MAPPING : FI_TENDV_TT ( VARCHAR2 ) 
    public void setFiTendvTt(String fiTendvTt) {
        this.fiTendvTt = fiTendvTt;
    }

    public String getFiTendvTt() {
        return this.fiTendvTt;
    }

    //--- DATABASE MAPPING : FI_MADV_TTBI ( VARCHAR2 ) 
    public void setFiMadvTtbi(String fiMadvTtbi) {
        this.fiMadvTtbi = fiMadvTtbi;
    }

    public String getFiMadvTtbi() {
        return this.fiMadvTtbi;
    }

    //--- DATABASE MAPPING : FI_TENDV_TTBI ( VARCHAR2 ) 
    public void setFiTendvTtbi(String fiTendvTtbi) {
        this.fiTendvTtbi = fiTendvTtbi;
    }

    public String getFiTendvTtbi() {
        return this.fiTendvTtbi;
    }

    //--- DATABASE MAPPING : FI_ID_GCN ( NUMBER ) 
    public void setFiIdGcn(Long fiIdGcn) {
        this.fiIdGcn = fiIdGcn;
    }

    public Long getFiIdGcn() {
        return this.fiIdGcn;
    }

    //--- DATABASE MAPPING : FI_STT ( NUMBER ) 
    public void setFiStt(Long fiStt) {
        this.fiStt = fiStt;
    }

    public Long getFiStt() {
        return this.fiStt;
    }

    //--- DATABASE MAPPING : FI_HOATDONG ( NUMBER ) 
    public void setFiHoatdong(Long fiHoatdong) {
        this.fiHoatdong = fiHoatdong;
    }

    public Long getFiHoatdong() {
        return this.fiHoatdong;
    }

    //--- DATABASE MAPPING : FI_NGAYTAO ( DATE ) 
    public void setFiNgaytao(Date fiNgaytao) {
        this.fiNgaytao = fiNgaytao;
    }

    public Date getFiNgaytao() {
        return this.fiNgaytao;
    }

    //--- DATABASE MAPPING : FI_NGAY_CN ( DATE ) 
    public void setFiNgayCn(Date fiNgayCn) {
        this.fiNgayCn = fiNgayCn;
    }

    public Date getFiNgayCn() {
        return this.fiNgayCn;
    }

    //--- DATABASE MAPPING : FI_SOLUONG ( NUMBER ) 
    public void setFiSoluong(BigDecimal fiSoluong) {
        this.fiSoluong = fiSoluong;
    }

    public BigDecimal getFiSoluong() {
        return this.fiSoluong;
    }

    //--- DATABASE MAPPING : FI_KHOILUONG ( NUMBER ) 
    public void setFiKhoiluong(BigDecimal fiKhoiluong) {
        this.fiKhoiluong = fiKhoiluong;
    }

    public BigDecimal getFiKhoiluong() {
        return this.fiKhoiluong;
    }

    //--- DATABASE MAPPING : FI_KLBI ( NUMBER ) 
    public void setFiKlbi(BigDecimal fiKlbi) {
        this.fiKlbi = fiKlbi;
    }

    public BigDecimal getFiKlbi() {
        return this.fiKlbi;
    }

    //--- DATABASE MAPPING : FI_THETICH ( NUMBER ) 
    public void setFiThetich(BigDecimal fiThetich) {
        this.fiThetich = fiThetich;
    }

    public BigDecimal getFiThetich() {
        return this.fiThetich;
    }

    //--- DATABASE MAPPING : FI_THETICHBI ( NUMBER ) 
    public void setFiThetichbi(BigDecimal fiThetichbi) {
        this.fiThetichbi = fiThetichbi;
    }

    public BigDecimal getFiThetichbi() {
        return this.fiThetichbi;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("[");
        sb.append(fiIdHh);
        sb.append("]:");
        sb.append(fiTenHh);
        sb.append("|");
        sb.append(fiTenKh);
        sb.append("|");
        sb.append(fiMadvSl);
        sb.append("|");
        sb.append(fiTendvSl);
        sb.append("|");
        sb.append(fiMadvKl);
        sb.append("|");
        sb.append(fiTendvKl);
        sb.append("|");
        sb.append(fiMadvBi);
        sb.append("|");
        sb.append(fiTendvBi);
        sb.append("|");
        sb.append(fiMadvTt);
        sb.append("|");
        sb.append(fiTendvTt);
        sb.append("|");
        sb.append(fiMadvTtbi);
        sb.append("|");
        sb.append(fiTendvTtbi);
        sb.append("|");
        sb.append(fiIdGcn);
        sb.append("|");
        sb.append(fiStt);
        sb.append("|");
        sb.append(fiHoatdong);
        sb.append("|");
        sb.append(fiNgaytao);
        sb.append("|");
        sb.append(fiNgayCn);
        sb.append("|");
        sb.append(fiSoluong);
        sb.append("|");
        sb.append(fiKhoiluong);
        sb.append("|");
        sb.append(fiKlbi);
        sb.append("|");
        sb.append(fiThetich);
        sb.append("|");
        sb.append(fiThetichbi);
        return sb.toString();
    }

}
