/*
 * Created on 18 Jul 2017 ( Time 08:39:33 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 
package com.nsw.mard.p26.model;

import lombok.Data;
import lombok.EqualsAndHashCode;

import java.io.Serializable;


/**
 * Persistent class for entity stored in table "25" - Hồ sơ Đăng ký
 *
 * @author Telosys Tools Generator
 */
@Data
public class TbdHanghoaCL26  implements Serializable {
    private static final long serialVersionUID = 1L;

    public static final String SEQUENCE_NAME = "TBDHANGHOACL26_SEQ";

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    private Integer fiIdProCL;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS
    //----------------------------------------------------------------------
    private Integer fiIdProduct;

    private String fiProCLTarg;

    private String fiProCLCompare;

    private String fiProCLContent;

    private String fiProCLUnitID;

    private String fiProCLUnitName;
}
