/*
 * Created on 25 Jul 2017 ( Time 08:16:55 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 
package com.nsw.mard.comon;

import lombok.Data;

import java.io.Serializable;

/**
 * Persistent class for entity stored in table "CMON_SEAFOODPROCESSORS"
 *
 * @author Telosys Tools Generator
 *
 */
@Data
public class CmonSeafoodprocessors implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long seafoodprocessorsid;

    private String seafoodprocessorscode;

    private String seafoodprocessorsname;

    private String seafoodprocessorsadress;

    private String commercialnameofestablishments;

    private String seafoodprocessorsadressen;

}
