/*
 * Created on 28 Dec 2018 ( Time 17:29:13 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 
package com.nsw.moh.p36.model;

import java.io.Serializable;

import java.util.Date;

public class Tbdcongvan36 implements Serializable {

    private static final long serialVersionUID = 1L;
    private Long fiIdCv;

    private Long fiIdHoso;

    private String fiMaHoso;

    private String fiCoQuanCap;

    private String fiSoCongVan;

    private Date fiNgayKy;

    private String fiNguoiKy;

    private Date fiNgayHetHl;

    private Long fiLoaiDon;

    private Long fiHoatdong;

    private String fiNguoitao;

    private Date fiNgaytao;

    private Date fiNgCapnhat;

    //
    private TbdcvDinhkem36 dinhKemCongVan;

    //
    private TbdcvDinhkem36 dinhKemDonHang;

    //
    private TbdcvDonhang36 donHang;

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Tbdcongvan36() {
        super();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setFiIdCv(Long fiIdCv) {
        this.fiIdCv = fiIdCv;
    }

    public Long getFiIdCv() {
        return this.fiIdCv;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : FI_ID_HOSO ( NUMBER ) 
    public void setFiIdHoso(Long fiIdHoso) {
        this.fiIdHoso = fiIdHoso;
    }

    public Long getFiIdHoso() {
        return this.fiIdHoso;
    }

    //--- DATABASE MAPPING : FI_MA_HOSO ( VARCHAR2 ) 
    public void setFiMaHoso(String fiMaHoso) {
        this.fiMaHoso = fiMaHoso;
    }

    public String getFiMaHoso() {
        return this.fiMaHoso;
    }

    //--- DATABASE MAPPING : FI_CO_QUAN_CAP ( VARCHAR2 ) 
    public void setFiCoQuanCap(String fiCoQuanCap) {
        this.fiCoQuanCap = fiCoQuanCap;
    }

    public String getFiCoQuanCap() {
        return this.fiCoQuanCap;
    }

    //--- DATABASE MAPPING : FI_SO_CONG_VAN ( VARCHAR2 ) 
    public void setFiSoCongVan(String fiSoCongVan) {
        this.fiSoCongVan = fiSoCongVan;
    }

    public String getFiSoCongVan() {
        return this.fiSoCongVan;
    }

    //--- DATABASE MAPPING : FI_NGAY_KY ( TIMESTAMP(6) ) 
    public void setFiNgayKy(Date fiNgayKy) {
        this.fiNgayKy = fiNgayKy;
    }

    public Date getFiNgayKy() {
        return this.fiNgayKy;
    }

    //--- DATABASE MAPPING : FI_NGUOI_KY ( VARCHAR2 ) 
    public void setFiNguoiKy(String fiNguoiKy) {
        this.fiNguoiKy = fiNguoiKy;
    }

    public String getFiNguoiKy() {
        return this.fiNguoiKy;
    }

    //--- DATABASE MAPPING : FI_NGAY_HET_HL ( TIMESTAMP(6) ) 
    public void setFiNgayHetHl(Date fiNgayHetHl) {
        this.fiNgayHetHl = fiNgayHetHl;
    }

    public Date getFiNgayHetHl() {
        return this.fiNgayHetHl;
    }

    //--- DATABASE MAPPING : FI_LOAI_DON ( NUMBER ) 
    public void setFiLoaiDon(Long fiLoaiDon) {
        this.fiLoaiDon = fiLoaiDon;
    }

    public Long getFiLoaiDon() {
        return this.fiLoaiDon;
    }

    //--- DATABASE MAPPING : FI_HOATDONG ( NUMBER ) 
    public void setFiHoatdong(Long fiHoatdong) {
        this.fiHoatdong = fiHoatdong;
    }

    public Long getFiHoatdong() {
        return this.fiHoatdong;
    }

    //--- DATABASE MAPPING : FI_NGUOITAO ( VARCHAR2 ) 
    public void setFiNguoitao(String fiNguoitao) {
        this.fiNguoitao = fiNguoitao;
    }

    public String getFiNguoitao() {
        return this.fiNguoitao;
    }

    //--- DATABASE MAPPING : FI_NGAYTAO ( TIMESTAMP(6) ) 
    public void setFiNgaytao(Date fiNgaytao) {
        this.fiNgaytao = fiNgaytao;
    }

    public Date getFiNgaytao() {
        return this.fiNgaytao;
    }

    //--- DATABASE MAPPING : FI_NG_CAPNHAT ( TIMESTAMP(6) ) 
    public void setFiNgCapnhat(Date fiNgCapnhat) {
        this.fiNgCapnhat = fiNgCapnhat;
    }

    public Date getFiNgCapnhat() {
        return this.fiNgCapnhat;
    }

    public TbdcvDinhkem36 getDinhKemCongVan() {
        return dinhKemCongVan;
    }

    public void setDinhKemCongVan(TbdcvDinhkem36 dinhKemCongVan) {
        this.dinhKemCongVan = dinhKemCongVan;
    }

    public TbdcvDinhkem36 getDinhKemDonHang() {
        return dinhKemDonHang;
    }

    public void setDinhKemDonHang(TbdcvDinhkem36 dinhKemDonHang) {
        this.dinhKemDonHang = dinhKemDonHang;
    }

    public TbdcvDonhang36 getDonHang() {
        return donHang;
    }

    public void setDonHang(TbdcvDonhang36 donHang) {
        this.donHang = donHang;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("[");
        sb.append(fiIdCv);
        sb.append("]:");
        sb.append(fiIdHoso);
        sb.append("|");
        sb.append(fiMaHoso);
        sb.append("|");
        sb.append(fiCoQuanCap);
        sb.append("|");
        sb.append(fiSoCongVan);
        sb.append("|");
        sb.append(fiNgayKy);
        sb.append("|");
        sb.append(fiNguoiKy);
        sb.append("|");
        sb.append(fiNgayHetHl);
        sb.append("|");
        sb.append(fiLoaiDon);
        sb.append("|");
        sb.append(fiHoatdong);
        sb.append("|");
        sb.append(fiNguoitao);
        sb.append("|");
        sb.append(fiNgaytao);
        sb.append("|");
        sb.append(fiNgCapnhat);
        return sb.toString();
    }

}
