/*
 * Created on 24 Jan 2019 ( Time 01:38:40 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.nsw.moh.p07.model;

import java.io.Serializable;

import java.util.Date;
import java.util.List;

public class TbdhsHanghoa7 implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    private Long fiIdHanghoa  ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    //@Column(name="FI_ID_HOSO")
    private Long fiIdHoso     ;

    //@Column(name="FI_TEN_TTB", length=250)
    private String     fiTenTtb     ;

    //@Column(name="FI_LOAI_TTB", length=250)
    private String     fiLoaiTtb    ;

    //@Column(name="FI_TEN_CSH", length=250)
    private String     fiTenCsh     ;

    //@Column(name="FI_DIACHI_CSH", length=250)
    private String     fiDiachiCsh  ;

    //@Column(name="FI_TEN_QG_CSH", length=250)
    private String     fiTenQgCsh   ;

    //@Column(name="FI_MA_QA_CSH", length=2)
    private String     fiMaQaCsh    ;

    //@Column(name="FI_TIEUCHUAN", length=250)
    private String     fiTieuchuan  ;

    //@Column(name="FI_PHANNHOM", length=250)
    private String     fiPhannhom   ;

    //@Column(name="FI_NHOM_TTB", length=250)
    private String     fiNhomTtb    ;

    //@Column(name="FI_NHIEU_CSSX", length=250)
    private String     fiNhieuCssx  ;

    //@Column(name="FI_DONG_GOI", length=250)
    private String     fiDongGoi    ;

    //@Column(name="FI_SO_DKLH", length=50)
    private String     fiSoDklh     ;

    //@Column(name="FI_DA_CO_DKLH", length=50)
    private String     fiDaCoDklh   ;

    //@Column(name="FI_HOATDONG")
    private Long fiHoatdong   ;

    //@Column(name="FI_NGUOITAO", length=50)
    private String     fiNguoitao   ;

    //@Temporal(TemporalType.TIMESTAMP)
    //@Column(name="FI_NGAYTAO")
    private Date       fiNgaytao    ;

    //@Temporal(TemporalType.TIMESTAMP)
    //@Column(name="FI_NG_CAPNHAT")
    private Date       fiNgCapnhat  ;

    //@Transient
    List<TbdhsHhLoai7> lstLoaiHangHoas;
    
    //@Transient
    List<TbdhsHhBaohanh7> lstBaoHanhHangHoas;
    

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TbdhsHanghoa7() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setFiIdHanghoa( Long fiIdHanghoa ) {
        this.fiIdHanghoa = fiIdHanghoa ;
    }
    public Long getFiIdHanghoa() {
        return this.fiIdHanghoa;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : FI_ID_HOSO ( NUMBER ) 
    public void setFiIdHoso( Long fiIdHoso ) {
        this.fiIdHoso = fiIdHoso;
    }
    public Long getFiIdHoso() {
        return this.fiIdHoso;
    }

    //--- DATABASE MAPPING : FI_TEN_TTB ( VARCHAR2 ) 
    public void setFiTenTtb( String fiTenTtb ) {
        this.fiTenTtb = fiTenTtb;
    }
    public String getFiTenTtb() {
        return this.fiTenTtb;
    }

    //--- DATABASE MAPPING : FI_LOAI_TTB ( VARCHAR2 ) 
    public void setFiLoaiTtb( String fiLoaiTtb ) {
        this.fiLoaiTtb = fiLoaiTtb;
    }
    public String getFiLoaiTtb() {
        return this.fiLoaiTtb;
    }

    //--- DATABASE MAPPING : FI_TEN_CSH ( VARCHAR2 ) 
    public void setFiTenCsh( String fiTenCsh ) {
        this.fiTenCsh = fiTenCsh;
    }
    public String getFiTenCsh() {
        return this.fiTenCsh;
    }

    //--- DATABASE MAPPING : FI_DIACHI_CSH ( VARCHAR2 ) 
    public void setFiDiachiCsh( String fiDiachiCsh ) {
        this.fiDiachiCsh = fiDiachiCsh;
    }
    public String getFiDiachiCsh() {
        return this.fiDiachiCsh;
    }

    //--- DATABASE MAPPING : FI_TEN_QG_CSH ( VARCHAR2 ) 
    public void setFiTenQgCsh( String fiTenQgCsh ) {
        this.fiTenQgCsh = fiTenQgCsh;
    }
    public String getFiTenQgCsh() {
        return this.fiTenQgCsh;
    }

    //--- DATABASE MAPPING : FI_MA_QA_CSH ( VARCHAR2 ) 
    public void setFiMaQaCsh( String fiMaQaCsh ) {
        this.fiMaQaCsh = fiMaQaCsh;
    }
    public String getFiMaQaCsh() {
        return this.fiMaQaCsh;
    }

    //--- DATABASE MAPPING : FI_TIEUCHUAN ( VARCHAR2 ) 
    public void setFiTieuchuan( String fiTieuchuan ) {
        this.fiTieuchuan = fiTieuchuan;
    }
    public String getFiTieuchuan() {
        return this.fiTieuchuan;
    }

    //--- DATABASE MAPPING : FI_PHANNHOM ( VARCHAR2 ) 
    public void setFiPhannhom( String fiPhannhom ) {
        this.fiPhannhom = fiPhannhom;
    }
    public String getFiPhannhom() {
        return this.fiPhannhom;
    }

    //--- DATABASE MAPPING : FI_NHOM_TTB ( VARCHAR2 ) 
    public void setFiNhomTtb( String fiNhomTtb ) {
        this.fiNhomTtb = fiNhomTtb;
    }
    public String getFiNhomTtb() {
        return this.fiNhomTtb;
    }

    //--- DATABASE MAPPING : FI_NHIEU_CSSX ( VARCHAR2 ) 
    public void setFiNhieuCssx( String fiNhieuCssx ) {
        this.fiNhieuCssx = fiNhieuCssx;
    }
    public String getFiNhieuCssx() {
        return this.fiNhieuCssx;
    }

    //--- DATABASE MAPPING : FI_DONG_GOI ( VARCHAR2 ) 
    public void setFiDongGoi( String fiDongGoi ) {
        this.fiDongGoi = fiDongGoi;
    }
    public String getFiDongGoi() {
        return this.fiDongGoi;
    }

    //--- DATABASE MAPPING : FI_SO_DKLH ( VARCHAR2 ) 
    public void setFiSoDklh( String fiSoDklh ) {
        this.fiSoDklh = fiSoDklh;
    }
    public String getFiSoDklh() {
        return this.fiSoDklh;
    }

    //--- DATABASE MAPPING : FI_DA_CO_DKLH ( VARCHAR2 ) 
    public void setFiDaCoDklh( String fiDaCoDklh ) {
        this.fiDaCoDklh = fiDaCoDklh;
    }
    public String getFiDaCoDklh() {
        return this.fiDaCoDklh;
    }

    //--- DATABASE MAPPING : FI_HOATDONG ( NUMBER ) 
    public void setFiHoatdong( Long fiHoatdong ) {
        this.fiHoatdong = fiHoatdong;
    }
    public Long getFiHoatdong() {
        return this.fiHoatdong;
    }

    //--- DATABASE MAPPING : FI_NGUOITAO ( VARCHAR2 ) 
    public void setFiNguoitao( String fiNguoitao ) {
        this.fiNguoitao = fiNguoitao;
    }
    public String getFiNguoitao() {
        return this.fiNguoitao;
    }

    //--- DATABASE MAPPING : FI_NGAYTAO ( TIMESTAMP(6) ) 
    public void setFiNgaytao( Date fiNgaytao ) {
        this.fiNgaytao = fiNgaytao;
    }
    public Date getFiNgaytao() {
        return this.fiNgaytao;
    }

    //--- DATABASE MAPPING : FI_NG_CAPNHAT ( TIMESTAMP(6) ) 
    public void setFiNgCapnhat( Date fiNgCapnhat ) {
        this.fiNgCapnhat = fiNgCapnhat;
    }
    public Date getFiNgCapnhat() {
        return this.fiNgCapnhat;
    }

    public List<TbdhsHhLoai7> getLstLoaiHangHoas() {
        return lstLoaiHangHoas;
    }

    public void setLstLoaiHangHoas(List<TbdhsHhLoai7> lstLoaiHangHoas) {
        this.lstLoaiHangHoas = lstLoaiHangHoas;
    }

    public List<TbdhsHhBaohanh7> getLstBaoHanhHangHoas() {
        return lstBaoHanhHangHoas;
    }

    public void setLstBaoHanhHangHoas(List<TbdhsHhBaohanh7> lstBaoHanhHangHoas) {
        this.lstBaoHanhHangHoas = lstBaoHanhHangHoas;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(fiIdHanghoa);
        sb.append("]:"); 
        sb.append(fiIdHoso);
        sb.append("|");
        sb.append(fiTenTtb);
        sb.append("|");
        sb.append(fiLoaiTtb);
        sb.append("|");
        sb.append(fiTenCsh);
        sb.append("|");
        sb.append(fiDiachiCsh);
        sb.append("|");
        sb.append(fiTenQgCsh);
        sb.append("|");
        sb.append(fiMaQaCsh);
        sb.append("|");
        sb.append(fiTieuchuan);
        sb.append("|");
        sb.append(fiPhannhom);
        sb.append("|");
        sb.append(fiNhomTtb);
        sb.append("|");
        sb.append(fiNhieuCssx);
        sb.append("|");
        sb.append(fiDongGoi);
        sb.append("|");
        sb.append(fiSoDklh);
        sb.append("|");
        sb.append(fiDaCoDklh);
        sb.append("|");
        sb.append(fiHoatdong);
        sb.append("|");
        sb.append(fiNguoitao);
        sb.append("|");
        sb.append(fiNgaytao);
        sb.append("|");
        sb.append(fiNgCapnhat);
        return sb.toString(); 
    } 

}
