/*
 * Created on 24 Jan 2019 ( Time 01:39:41 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 
package com.nsw.moh.p07.model;

import java.io.Serializable;

import java.util.Date;

public class TbdkqGcn7 implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    private Long fiIdKqGcn;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    //@Column(name="FI_ID_KQXL")
    private Long fiIdKqxl;

    //@Column(name="FI_SO_CHUNGNHAN", length=50)
    private String fiSoChungnhan;

    //@Temporal(TemporalType.TIMESTAMP)
    //@Column(name="FI_NGAYCAP")
    private Date fiNgaycap;

    //@Column(name="FI_TEN_TTB", length=250)
    private String fiTenTtb;

    //@Column(name="FI_LOAI_TTB", length=250)
    private String fiLoaiTtb;

    //@Column(name="FI_TEN_CSH", length=250)
    private String fiTenCsh;

    //@Column(name="FI_DIACHI_CSH", length=250)
    private String fiDiachiCsh;

    //@Column(name="FI_TIEUCHUAN", length=250)
    private String fiTieuchuan;

    //@Column(name="FI_HANG_SX", length=250)
    private String fiHangSx;

    //@Column(name="FI_DIACHI_CSSX", length=250)
    private String fiDiachiCssx;

    //@Temporal(TemporalType.TIMESTAMP)
    //@Column(name="FI_HIEULUC_TU")
    private Date fiHieulucTu;

    //@Temporal(TemporalType.TIMESTAMP)
    //@Column(name="FI_HIEULUC_DEN")
    private Date fiHieulucDen;

    //@Column(name="FI_HOATDONG")
    private Long fiHoatdong;

    //@Column(name="FI_NGUOITAO", length=50)
    private String fiNguoitao;

    //@Temporal(TemporalType.TIMESTAMP)
    //@Column(name="FI_NGAYTAO")
    private Date fiNgaytao;

    //@Temporal(TemporalType.TIMESTAMP)
    //@Column(name="FI_NG_CAPNHAT")
    private Date fiNgCapnhat;

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TbdkqGcn7() {
        super();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setFiIdKqGcn(Long fiIdKqGcn) {
        this.fiIdKqGcn = fiIdKqGcn;
    }

    public Long getFiIdKqGcn() {
        return this.fiIdKqGcn;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : FI_ID_KQXL ( NUMBER ) 
    public void setFiIdKqxl(Long fiIdKqxl) {
        this.fiIdKqxl = fiIdKqxl;
    }

    public Long getFiIdKqxl() {
        return this.fiIdKqxl;
    }

    //--- DATABASE MAPPING : FI_SO_CHUNGNHAN ( VARCHAR2 ) 
    public void setFiSoChungnhan(String fiSoChungnhan) {
        this.fiSoChungnhan = fiSoChungnhan;
    }

    public String getFiSoChungnhan() {
        return this.fiSoChungnhan;
    }

    //--- DATABASE MAPPING : FI_NGAYCAP ( TIMESTAMP(6) ) 
    public void setFiNgaycap(Date fiNgaycap) {
        this.fiNgaycap = fiNgaycap;
    }

    public Date getFiNgaycap() {
        return this.fiNgaycap;
    }

    //--- DATABASE MAPPING : FI_TEN_TTB ( VARCHAR2 ) 
    public void setFiTenTtb(String fiTenTtb) {
        this.fiTenTtb = fiTenTtb;
    }

    public String getFiTenTtb() {
        return this.fiTenTtb;
    }

    //--- DATABASE MAPPING : FI_LOAI_TTB ( VARCHAR2 ) 
    public void setFiLoaiTtb(String fiLoaiTtb) {
        this.fiLoaiTtb = fiLoaiTtb;
    }

    public String getFiLoaiTtb() {
        return this.fiLoaiTtb;
    }

    //--- DATABASE MAPPING : FI_TEN_CSH ( VARCHAR2 ) 
    public void setFiTenCsh(String fiTenCsh) {
        this.fiTenCsh = fiTenCsh;
    }

    public String getFiTenCsh() {
        return this.fiTenCsh;
    }

    //--- DATABASE MAPPING : FI_DIACHI_CSH ( VARCHAR2 ) 
    public void setFiDiachiCsh(String fiDiachiCsh) {
        this.fiDiachiCsh = fiDiachiCsh;
    }

    public String getFiDiachiCsh() {
        return this.fiDiachiCsh;
    }

    //--- DATABASE MAPPING : FI_TIEUCHUAN ( VARCHAR2 ) 
    public void setFiTieuchuan(String fiTieuchuan) {
        this.fiTieuchuan = fiTieuchuan;
    }

    public String getFiTieuchuan() {
        return this.fiTieuchuan;
    }

    //--- DATABASE MAPPING : FI_HANG_SX ( VARCHAR2 ) 
    public void setFiHangSx(String fiHangSx) {
        this.fiHangSx = fiHangSx;
    }

    public String getFiHangSx() {
        return this.fiHangSx;
    }

    //--- DATABASE MAPPING : FI_DIACHI_CSSX ( VARCHAR2 ) 
    public void setFiDiachiCssx(String fiDiachiCssx) {
        this.fiDiachiCssx = fiDiachiCssx;
    }

    public String getFiDiachiCssx() {
        return this.fiDiachiCssx;
    }

    //--- DATABASE MAPPING : FI_HIEULUC_TU ( TIMESTAMP(6) ) 
    public void setFiHieulucTu(Date fiHieulucTu) {
        this.fiHieulucTu = fiHieulucTu;
    }

    public Date getFiHieulucTu() {
        return this.fiHieulucTu;
    }

    //--- DATABASE MAPPING : FI_HIEULUC_DEN ( TIMESTAMP(6) ) 
    public void setFiHieulucDen(Date fiHieulucDen) {
        this.fiHieulucDen = fiHieulucDen;
    }

    public Date getFiHieulucDen() {
        return this.fiHieulucDen;
    }

    //--- DATABASE MAPPING : FI_HOATDONG ( NUMBER ) 
    public void setFiHoatdong(Long fiHoatdong) {
        this.fiHoatdong = fiHoatdong;
    }

    public Long getFiHoatdong() {
        return this.fiHoatdong;
    }

    //--- DATABASE MAPPING : FI_NGUOITAO ( VARCHAR2 ) 
    public void setFiNguoitao(String fiNguoitao) {
        this.fiNguoitao = fiNguoitao;
    }

    public String getFiNguoitao() {
        return this.fiNguoitao;
    }

    //--- DATABASE MAPPING : FI_NGAYTAO ( TIMESTAMP(6) ) 
    public void setFiNgaytao(Date fiNgaytao) {
        this.fiNgaytao = fiNgaytao;
    }

    public Date getFiNgaytao() {
        return this.fiNgaytao;
    }

    //--- DATABASE MAPPING : FI_NG_CAPNHAT ( TIMESTAMP(6) ) 
    public void setFiNgCapnhat(Date fiNgCapnhat) {
        this.fiNgCapnhat = fiNgCapnhat;
    }

    public Date getFiNgCapnhat() {
        return this.fiNgCapnhat;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("[");
        sb.append(fiIdKqGcn);
        sb.append("]:");
        sb.append(fiIdKqxl);
        sb.append("|");
        sb.append(fiSoChungnhan);
        sb.append("|");
        sb.append(fiNgaycap);
        sb.append("|");
        sb.append(fiTenTtb);
        sb.append("|");
        sb.append(fiLoaiTtb);
        sb.append("|");
        sb.append(fiTenCsh);
        sb.append("|");
        sb.append(fiDiachiCsh);
        sb.append("|");
        sb.append(fiTieuchuan);
        sb.append("|");
        sb.append(fiHangSx);
        sb.append("|");
        sb.append(fiDiachiCssx);
        sb.append("|");
        sb.append(fiHieulucTu);
        sb.append("|");
        sb.append(fiHieulucDen);
        sb.append("|");
        sb.append(fiHoatdong);
        sb.append("|");
        sb.append(fiNguoitao);
        sb.append("|");
        sb.append(fiNgaytao);
        sb.append("|");
        sb.append(fiNgCapnhat);
        return sb.toString();
    }

}
