/*
 * Created on 18 Jul 2017 ( Time 08:39:33 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 
package com.nsw.mard.p8.model;

import lombok.Data;

import java.io.Serializable;

@Data
public class Tbdcnkdhanghoa08 implements Serializable {
    private static final long serialVersionUID = 1L;

    private Long fiIdProduct;

    private Long fiIdCV;

    private Integer fiSort;

    private String fiProductName;

    private String fiProductScienceName;

    private String fiProductCode;

    private Integer fiQtyMale;

    private Integer fiQtyFemale;

    private Integer fiAge = 0;

    private String fiPackingType; //Unit of measurement

    private Double fiNumber = 0d;

    private Double fiNumberOrigin = 0d;

    private String fiUnitCode; //Unit of measurement

    private String fiUnitName;

    private Double fiNetWeight = 0d;
    
    private Double fiNetWeightOrigin;

    private String fiNWUnitCode; //Unit of measurement

    private Double fiGrossWeight = 0d;

    private Double fiGrossWeightOrigin = 0d;

    private String fiGWUnitCode; //Unit of measurement

    private String fiPurpose;

    private String fiCountryOrigin;

    private String fiCountryOriginName;

    private String fiPortCode;

    private String fiPortName;

    public Tbdcnkdhanghoa08() {
    }
}
