/*
 * Created on 15 Sep 2017 ( Time 15:28:14 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 
package com.nsw.most.p03.model;

import java.io.Serializable;
import java.util.Date;

public class Tbdcongvan3 implements Serializable {

    private Long fiIdCv;

    private Long fiIdHoso;

    private String fiMaHoso;

    private String fiSoCv;

    private Date fiNgayCap;

    private String fiNguoiKy;

    private String fiChucVu;

    private String fiTenTep;

    private Long fiHoatdong;

    private String fiNguoitao;
    private Date fiNgaytao;

    private Long fiTrangthai;

    private Tbddinhkem3 dinhkem;

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Tbdcongvan3() {
        super();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setFiIdCv(Long fiIdCv) {
        this.fiIdCv = fiIdCv;
    }

    public Long getFiIdCv() {
        return this.fiIdCv;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : FI_ID_HOSO ( NUMBER ) 
    public void setFiIdHoso(Long fiIdHoso) {
        this.fiIdHoso = fiIdHoso;
    }

    public Long getFiIdHoso() {
        return this.fiIdHoso;
    }

    //--- DATABASE MAPPING : FI_MA_HOSO ( VARCHAR2 ) 
    public void setFiMaHoso(String fiMaHoso) {
        this.fiMaHoso = fiMaHoso;
    }

    public String getFiMaHoso() {
        return this.fiMaHoso;
    }

    //--- DATABASE MAPPING : FI_SO_GP ( VARCHAR2 ) 
    public void setFiSoCv(String fiSoCv) {
        this.fiSoCv = fiSoCv;
    }

    public String getFiSoCv() {
        return this.fiSoCv;
    }

    //--- DATABASE MAPPING : FI_NGAY_CAP ( TIMESTAMP(6) ) 
    public void setFiNgayCap(Date fiNgayCap) {
        this.fiNgayCap = fiNgayCap;
    }

    public Date getFiNgayCap() {
        return this.fiNgayCap;
    }

    //--- DATABASE MAPPING : FI_NGUOI_KY ( VARCHAR2 ) 
    public void setFiNguoiKy(String fiNguoiKy) {
        this.fiNguoiKy = fiNguoiKy;
    }

    public String getFiNguoiKy() {
        return this.fiNguoiKy;
    }

    //--- DATABASE MAPPING : FI_CHUC_VU ( VARCHAR2 ) 
    public void setFiChucVu(String fiChucVu) {
        this.fiChucVu = fiChucVu;
    }

    public String getFiChucVu() {
        return this.fiChucVu;
    }

    //--- DATABASE MAPPING : FI_TEN_TEP ( VARCHAR2 ) 
    public void setFiTenTep(String fiTenTep) {
        this.fiTenTep = fiTenTep;
    }

    public String getFiTenTep() {
        return this.fiTenTep;
    }

    //--- DATABASE MAPPING : FI_HOATDONG ( NUMBER ) 
    public void setFiHoatdong(Long fiHoatdong) {
        this.fiHoatdong = fiHoatdong;
    }

    public Long getFiHoatdong() {
        return this.fiHoatdong;
    }

    //--- DATABASE MAPPING : FI_NGUOITAO ( VARCHAR2 ) 
    public void setFiNguoitao(String fiNguoitao) {
        this.fiNguoitao = fiNguoitao;
    }

    public String getFiNguoitao() {
        return this.fiNguoitao;
    }

    //--- DATABASE MAPPING : FI_NGAYTAO ( TIMESTAMP(6) ) 
    public void setFiNgaytao(Date fiNgaytao) {
        this.fiNgaytao = fiNgaytao;
    }

    public Date getFiNgaytao() {
        return this.fiNgaytao;
    }

    public Long getFiTrangthai() {
        return fiTrangthai;
    }

    public void setFiTrangthai(Long fiTrangthai) {
        this.fiTrangthai = fiTrangthai;
    }

    public Tbddinhkem3 getDinhkem() {
        return dinhkem;
    }

    public void setDinhkem(Tbddinhkem3 dinhkem) {
        this.dinhkem = dinhkem;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("[");
        sb.append(fiIdCv);
        sb.append("]:");
        sb.append(fiIdHoso);
        sb.append("|");
        sb.append(fiMaHoso);
        sb.append("|");
        sb.append(fiSoCv);
        sb.append("|");
        sb.append(fiNgayCap);
        sb.append("|");
        sb.append(fiNguoiKy);
        sb.append("|");
        sb.append(fiChucVu);
        sb.append("|");
        sb.append(fiTenTep);
        sb.append("|");
        sb.append(fiHoatdong);
        sb.append("|");
        sb.append(fiNguoitao);
        sb.append("|");
        sb.append(fiNgaytao);
        return sb.toString();
    }

}
