/*
 * Created on 2 Aug 2017 ( Time 15:47:35 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 
package com.nsw.most.p03.model;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.nsw.util.CustomJsonDateDeserializer;
import java.io.Serializable;

import java.util.Date;
import java.util.List;

public class Tbdtokhaihq3 implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long fiIdTk;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    private String fiSoTk;

    private Date fiNgayDk;

    private String fiMaHq;

    private String fiTenDvNk;

    private String fiDiachiDvNk;

    private String fiTenDvXk;

    private String fiDiachiDvXk;

    private String fiNuocXk;

    private String fiSoHoadon;

    private Date fiNgayCapHd;

    private String fiSoluong;

    private String fiTong;

    private Long fiIdHoso;

    private String fiGhichu;

    private Date fiNgaytao;

    private Long fiHoatdong;

    private String fiNguoitao;

    private String fiMaHoso;

    List<Tbdtokhaihqd3> toKhaiHQDs;

    Long stt;

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Tbdtokhaihq3() {
        super();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setFiIdTk(Long fiIdTk) {
        this.fiIdTk = fiIdTk;
    }

    public Long getFiIdTk() {
        return this.fiIdTk;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : FI_SO_TK ( VARCHAR2 ) 
    public void setFiSoTk(String fiSoTk) {
        this.fiSoTk = fiSoTk;
    }

    public String getFiSoTk() {
        return this.fiSoTk;
    }

    //--- DATABASE MAPPING : FI_NGAY_DK ( TIMESTAMP(6) ) 
    public void setFiNgayDk(Date fiNgayDk) {
        this.fiNgayDk = fiNgayDk;
    }

    public Date getFiNgayDk() {
        return this.fiNgayDk;
    }

    //--- DATABASE MAPPING : FI_MA_HQ ( VARCHAR2 ) 
    public void setFiMaHq(String fiMaHq) {
        this.fiMaHq = fiMaHq;
    }

    public String getFiMaHq() {
        return this.fiMaHq;
    }

    //--- DATABASE MAPPING : FI_TEN_DV_NK ( VARCHAR2 ) 
    public void setFiTenDvNk(String fiTenDvNk) {
        this.fiTenDvNk = fiTenDvNk;
    }

    public String getFiTenDvNk() {
        return this.fiTenDvNk;
    }

    //--- DATABASE MAPPING : FI_DIACHI_DV_NK ( VARCHAR2 ) 
    public void setFiDiachiDvNk(String fiDiachiDvNk) {
        this.fiDiachiDvNk = fiDiachiDvNk;
    }

    public String getFiDiachiDvNk() {
        return this.fiDiachiDvNk;
    }

    //--- DATABASE MAPPING : FI_TEN_DV_XK ( VARCHAR2 ) 
    public void setFiTenDvXk(String fiTenDvXk) {
        this.fiTenDvXk = fiTenDvXk;
    }

    public String getFiTenDvXk() {
        return this.fiTenDvXk;
    }

    //--- DATABASE MAPPING : FI_DIACHI_DV_XK ( VARCHAR2 ) 
    public void setFiDiachiDvXk(String fiDiachiDvXk) {
        this.fiDiachiDvXk = fiDiachiDvXk;
    }

    public String getFiDiachiDvXk() {
        return this.fiDiachiDvXk;
    }

    //--- DATABASE MAPPING : FI_NUOC_XK ( VARCHAR2 ) 
    public void setFiNuocXk(String fiNuocXk) {
        this.fiNuocXk = fiNuocXk;
    }

    public String getFiNuocXk() {
        return this.fiNuocXk;
    }

    //--- DATABASE MAPPING : FI_SO_HOADON ( VARCHAR2 ) 
    public void setFiSoHoadon(String fiSoHoadon) {
        this.fiSoHoadon = fiSoHoadon;
    }

    public String getFiSoHoadon() {
        return this.fiSoHoadon;
    }

    //--- DATABASE MAPPING : FI_NGAY_CAP_HD ( TIMESTAMP(6) ) 
    public void setFiNgayCapHd(Date fiNgayCapHd) {
        this.fiNgayCapHd = fiNgayCapHd;
    }

    public Date getFiNgayCapHd() {
        return this.fiNgayCapHd;
    }

    //--- DATABASE MAPPING : FI_SOLUONG ( NUMBER ) 
    public void setFiSoluong(String fiSoluong) {
        this.fiSoluong = fiSoluong;
    }

    public String getFiSoluong() {
        return this.fiSoluong;
    }

    //--- DATABASE MAPPING : FI_TONG ( NUMBER ) 
    public void setFiTong(String fiTong) {
        this.fiTong = fiTong;
    }

    public String getFiTong() {
        return this.fiTong;
    }

    //--- DATABASE MAPPING : FI_ID_HOSO ( NUMBER ) 
    public void setFiIdHoso(Long fiIdHoso) {
        this.fiIdHoso = fiIdHoso;
    }

    public Long getFiIdHoso() {
        return this.fiIdHoso;
    }

    //--- DATABASE MAPPING : FI_GHICHU ( VARCHAR2 ) 
    public void setFiGhichu(String fiGhichu) {
        this.fiGhichu = fiGhichu;
    }

    public String getFiGhichu() {
        return this.fiGhichu;
    }

    //--- DATABASE MAPPING : FI_NGAYTAO ( TIMESTAMP(6) ) 
    @JsonDeserialize(using = CustomJsonDateDeserializer.class)
    public void setFiNgaytao(Date fiNgaytao) {
        this.fiNgaytao = fiNgaytao;
    }

    public Date getFiNgaytao() {
        return this.fiNgaytao;
    }

    //--- DATABASE MAPPING : FI_HOATDONG ( NUMBER ) 
    public void setFiHoatdong(Long fiHoatdong) {
        this.fiHoatdong = fiHoatdong;
    }

    public Long getFiHoatdong() {
        return this.fiHoatdong;
    }

    //--- DATABASE MAPPING : FI_NGUOITAO ( VARCHAR2 ) 
    public void setFiNguoitao(String fiNguoitao) {
        this.fiNguoitao = fiNguoitao;
    }

    public String getFiNguoitao() {
        return this.fiNguoitao;
    }

    //--- DATABASE MAPPING : FI_MA_HOSO ( VARCHAR2 ) 
    public void setFiMaHoso(String fiMaHoso) {
        this.fiMaHoso = fiMaHoso;
    }

    public String getFiMaHoso() {
        return this.fiMaHoso;
    }

    public List<Tbdtokhaihqd3> getToKhaiHQDs() {
        return toKhaiHQDs;
    }

    public void setToKhaiHQDs(List<Tbdtokhaihqd3> toKhaiHQDs) {
        this.toKhaiHQDs = toKhaiHQDs;
    }

    public Long getStt() {
        return stt;
    }

    public void setStt(Long stt) {
        this.stt = stt;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("[");
        sb.append(fiIdTk);
        sb.append("]:");
        sb.append(fiSoTk);
        sb.append("|");
        sb.append(fiNgayDk);
        sb.append("|");
        sb.append(fiMaHq);
        sb.append("|");
        sb.append(fiTenDvNk);
        sb.append("|");
        sb.append(fiDiachiDvNk);
        sb.append("|");
        sb.append(fiTenDvXk);
        sb.append("|");
        sb.append(fiDiachiDvXk);
        sb.append("|");
        sb.append(fiNuocXk);
        sb.append("|");
        sb.append(fiSoHoadon);
        sb.append("|");
        sb.append(fiNgayCapHd);
        sb.append("|");
        sb.append(fiSoluong);
        sb.append("|");
        sb.append(fiTong);
        sb.append("|");
        sb.append(fiIdHoso);
        sb.append("|");
        sb.append(fiGhichu);
        sb.append("|");
        sb.append(fiNgaytao);
        sb.append("|");
        sb.append(fiHoatdong);
        sb.append("|");
        sb.append(fiNguoitao);
        sb.append("|");
        sb.append(fiMaHoso);
        return sb.toString();
    }

}
