/*
 * Created on 18 Jul 2017 ( Time 08:39:33 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 
package com.nsw.backend.mard.p26.model;

import com.nsw.backend.dic.model.CmonBaseEntity;
import lombok.Data;
import lombok.EqualsAndHashCode;

import javax.persistence.*;
import java.io.Serializable;

/**
 * Persistent class for entity stored in table "25" - Hồ sơ Đăng ký
 *
 * @author Telosys Tools Generator
 */
@Entity
@Data
@EqualsAndHashCode(callSuper = false)
@Table(name = "TBDHANGHOACL26", schema = "MARD")
public class TbdHanghoaCL26 extends CmonBaseEntity implements Serializable {
    private static final long serialVersionUID = 1L;

    public static final String SEQUENCE_NAME = "TBDHANGHOACL26_SEQ";

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(nullable = false,name = "FI_ID")
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = SEQUENCE_NAME)
    @SequenceGenerator(sequenceName = SEQUENCE_NAME, schema = "MARD", initialValue = 1, allocationSize = 1, name = SEQUENCE_NAME)
    private Integer fiIdCL26;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS
    //----------------------------------------------------------------------
    @Column(name = "FI_PRO_ID")
    private Integer fiIdHH26;
    @Column(name = "FI_ID_HH_25")
    private Integer fiIdProduct;
    @Column(name = "FI_PRO_CL25")
    private Integer fiIdProCL;
    @Column(name = "FI_PROCL_TARG", nullable = false, length = 50)
    private String fiProCLTarg;

    @Column(name = "FI_PROCL_COMPARE", nullable = false, length = 15)
    private String fiProCLCompare;

    @Column(name = "FI_PROCL_CONTENT", nullable = false, length = 15)
    private String fiProCLContent;

    @Column(name = "FI_PROCL_UNIT_ID")
    private String fiProCLUnitID;

    @Column(name = "FI_PROCL_UNIT_NAME")
    private String fiProCLUnitName;
}
