/*
 * Created on 12 Jul 2017 ( Time 16:04:27 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 
package com.nsw.most.p02.model;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;
import java.util.Date;

/**
 * Persistent class for entity stored in table "TBDTOKHAIHQD2"
 *
 * @author Telosys Tools Generator
 *
 */
public class Tbdtokhaihqd2 implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    private Long fiIdSp;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    private String fiMaHs;

    private String fiTenHh;

    private String fiKlSl;

    private String fiTenDv;

    private Long fiIdTk;

    private String fiGhichu;

    private Date fiNgaytao;

    private Long fiHoatdong;

    private String fiNguoitao;
    
    private Long stt;
    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Tbdtokhaihqd2() {
        super();
    }

    public Tbdtokhaihqd2(Long fiIdSp, String fiMaHs, String fiTenHh, String fiKlSl, String fiTenDv, Long fiIdTk, String fiGhichu, Date fiNgaytao, Long fiHoatdong, String fiNguoitao, Long stt) {
        this.fiIdSp = fiIdSp;
        this.fiMaHs = fiMaHs;
        this.fiTenHh = fiTenHh;
        this.fiKlSl = fiKlSl;
        this.fiTenDv = fiTenDv;
        this.fiIdTk = fiIdTk;
        this.fiGhichu = fiGhichu;
        this.fiNgaytao = fiNgaytao;
        this.fiHoatdong = fiHoatdong;
        this.fiNguoitao = fiNguoitao;
        this.stt = stt;
    }

    public Long getStt() {
        return stt;
    }

    public void setStt(Long stt) {
        this.stt = stt;
    }

    
    

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setFiIdSp(Long fiIdSp) {
        this.fiIdSp = fiIdSp;
    }

    public Long getFiIdSp() {
        return this.fiIdSp;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : FI_MA_HS ( VARCHAR2 ) 
    public void setFiMaHs(String fiMaHs) {
        this.fiMaHs = fiMaHs;
    }

    public String getFiMaHs() {
        return this.fiMaHs;
    }

    //--- DATABASE MAPPING : FI_TEN_HH ( VARCHAR2 ) 
    public void setFiTenHh(String fiTenHh) {
        this.fiTenHh = fiTenHh;
    }

    public String getFiTenHh() {
        return this.fiTenHh;
    }

    //--- DATABASE MAPPING : FI_KL_SL ( NUMBER ) 
    public void setFiKlSl(String fiKlSl) {
        this.fiKlSl = fiKlSl;
    }

    public String getFiKlSl() {
        return this.fiKlSl;
    }

    //--- DATABASE MAPPING : FI_TEN_DV ( VARCHAR2 ) 
    public void setFiTenDv(String fiTenDv) {
        this.fiTenDv = fiTenDv;
    }

    public String getFiTenDv() {
        return this.fiTenDv;
    }

    //--- DATABASE MAPPING : FI_ID_TK ( NUMBER ) 
    public void setFiIdTk(Long fiIdTk) {
        this.fiIdTk = fiIdTk;
    }

    public Long getFiIdTk() {
        return this.fiIdTk;
    }

    //--- DATABASE MAPPING : FI_GHICHU ( VARCHAR2 ) 
    public void setFiGhichu(String fiGhichu) {
        this.fiGhichu = fiGhichu;
    }

    public String getFiGhichu() {
        return this.fiGhichu;
    }

    //--- DATABASE MAPPING : FI_NGAYTAO ( TIMESTAMP(6) ) 
    public void setFiNgaytao(Date fiNgaytao) {
        this.fiNgaytao = fiNgaytao;
    }

    public Date getFiNgaytao() {
        return this.fiNgaytao;
    }

    //--- DATABASE MAPPING : FI_HOATDONG ( NUMBER ) 
    public void setFiHoatdong(Long fiHoatdong) {
        this.fiHoatdong = fiHoatdong;
    }

    public Long getFiHoatdong() {
        return this.fiHoatdong;
    }

    //--- DATABASE MAPPING : FI_NGUOITAO ( VARCHAR2 ) 
    public void setFiNguoitao(String fiNguoitao) {
        this.fiNguoitao = fiNguoitao;
    }

    public String getFiNguoitao() {
        return this.fiNguoitao;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("[");
        sb.append(fiIdSp);
        sb.append("]:");
        sb.append(fiMaHs);
        sb.append("|");
        sb.append(fiTenHh);
        sb.append("|");
        sb.append(fiKlSl);
        sb.append("|");
        sb.append(fiTenDv);
        sb.append("|");
        sb.append(fiIdTk);
        sb.append("|");
        sb.append(fiGhichu);
        sb.append("|");
        sb.append(fiNgaytao);
        sb.append("|");
        sb.append(fiHoatdong);
        sb.append("|");
        sb.append(fiNguoitao);
        return sb.toString();
    }

}
