/*
 * Created on 12 Jul 2017 ( Time 16:04:24 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 
package com.nsw.most.p02.model;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.io.Serializable;
import com.nsw.annotations.*;
import com.nsw.util.CustomJsonDateDeserializer;
//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.List;

/**
 * Persistent class for entity stored in table "TBDTOKHAIHQ2"
 *
 * @author Telosys Tools Generator
 *
 */
public class Tbdtokhaihq2 extends AbstractEntity {

    private Long fiIdTk;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    private String fiSoTk;

    private Date fiNgayDk;

    private String fiMaHq;

    private String fiNguoiNk;

    private String fiDiachiNnk;

    private String fiDtNnk;

    private String fiNguoiXk;

    private String fiDiachiNxk;

    private String fiNuocXk;

    private String fiSoHoadon;

    private Date fiNgayCapHd;

    private String fiSoluong;

    private String fiTong;

    private Long fiIdHoso;

    private String fiGhichu;

    private Date fiNgaytao;

    private Long fiHoatdong;

    private String fiNguoitao;

    List<Tbdtokhaihqd2> toKhaiHQD2s;

    Long stt;

    public Tbdtokhaihq2() {
        super();
    }

    public Tbdtokhaihq2(Long fiIdTk, String fiSoTk, Date fiNgayDk, String fiMaHq, String fiNguoiNk, String fiDiachiNnk, String fiDtNnk, String fiNguoiXk, String fiDiachiNxk, String fiNuocXk, String fiSoHoadon, Date fiNgayCapHd, String fiSoluong, String fiTong, Long fiIdHoso, String fiGhichu, Date fiNgaytao, Long fiHoatdong, String fiNguoitao, List<Tbdtokhaihqd2> toKhaiHQD2s, Long stt) {
        this.fiIdTk = fiIdTk;
        this.fiSoTk = fiSoTk;
        this.fiNgayDk = fiNgayDk;
        this.fiMaHq = fiMaHq;
        this.fiNguoiNk = fiNguoiNk;
        this.fiDiachiNnk = fiDiachiNnk;
        this.fiDtNnk = fiDtNnk;
        this.fiNguoiXk = fiNguoiXk;
        this.fiDiachiNxk = fiDiachiNxk;
        this.fiNuocXk = fiNuocXk;
        this.fiSoHoadon = fiSoHoadon;
        this.fiNgayCapHd = fiNgayCapHd;
        this.fiSoluong = fiSoluong;
        this.fiTong = fiTong;
        this.fiIdHoso = fiIdHoso;
        this.fiGhichu = fiGhichu;
        this.fiNgaytao = fiNgaytao;
        this.fiHoatdong = fiHoatdong;
        this.fiNguoitao = fiNguoitao;
        this.toKhaiHQD2s = toKhaiHQD2s;
        this.stt = stt;
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setFiIdTk(Long fiIdTk) {
        this.fiIdTk = fiIdTk;
    }

    public Long getFiIdTk() {
        return this.fiIdTk;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : FI_SO_TK ( VARCHAR2 ) 
    public void setFiSoTk(String fiSoTk) {
        this.fiSoTk = fiSoTk;
    }

    public String getFiSoTk() {
        return this.fiSoTk;
    }

    //--- DATABASE MAPPING : FI_NGAY_DK ( DATE ) 
    @JsonDeserialize(using = CustomJsonDateDeserializer.class)
    public void setFiNgayDk(Date fiNgayDk) {
        this.fiNgayDk = fiNgayDk;
    }

    public Date getFiNgayDk() {
        return this.fiNgayDk;
    }

    //--- DATABASE MAPPING : FI_MA_HQ ( VARCHAR2 ) 
    public void setFiMaHq(String fiMaHq) {
        this.fiMaHq = fiMaHq;
    }

    public String getFiMaHq() {
        return this.fiMaHq;
    }

    //--- DATABASE MAPPING : FI_NGUOI_NK ( VARCHAR2 ) 
    public void setFiNguoiNk(String fiNguoiNk) {
        this.fiNguoiNk = fiNguoiNk;
    }

    public String getFiNguoiNk() {
        return this.fiNguoiNk;
    }

    //--- DATABASE MAPPING : FI_DIACHI_NNK ( VARCHAR2 ) 
    public void setFiDiachiNnk(String fiDiachiNnk) {
        this.fiDiachiNnk = fiDiachiNnk;
    }

    public String getFiDiachiNnk() {
        return this.fiDiachiNnk;
    }

    //--- DATABASE MAPPING : FI_DT_NNK ( VARCHAR2 ) 
    public void setFiDtNnk(String fiDtNnk) {
        this.fiDtNnk = fiDtNnk;
    }

    public String getFiDtNnk() {
        return this.fiDtNnk;
    }

    //--- DATABASE MAPPING : FI_NGUOI_XK ( VARCHAR2 ) 
    public void setFiNguoiXk(String fiNguoiXk) {
        this.fiNguoiXk = fiNguoiXk;
    }

    public String getFiNguoiXk() {
        return this.fiNguoiXk;
    }

    //--- DATABASE MAPPING : FI_DIACHI_NXK ( VARCHAR2 ) 
    public void setFiDiachiNxk(String fiDiachiNxk) {
        this.fiDiachiNxk = fiDiachiNxk;
    }

    public String getFiDiachiNxk() {
        return this.fiDiachiNxk;
    }

    //--- DATABASE MAPPING : FI_NUOC_XK ( VARCHAR2 ) 
    public void setFiNuocXk(String fiNuocXk) {
        this.fiNuocXk = fiNuocXk;
    }

    public String getFiNuocXk() {
        return this.fiNuocXk;
    }

    //--- DATABASE MAPPING : FI_SO_HOADON ( VARCHAR2 ) 
    public void setFiSoHoadon(String fiSoHoadon) {
        this.fiSoHoadon = fiSoHoadon;
    }

    public String getFiSoHoadon() {
        return this.fiSoHoadon;
    }

    @JsonDeserialize(using = CustomJsonDateDeserializer.class)
    public void setFiNgayCapHd(Date fiNgayCapHd) {
        this.fiNgayCapHd = fiNgayCapHd;
    }

    public Date getFiNgayCapHd() {
        return this.fiNgayCapHd;
    }

    //--- DATABASE MAPPING : FI_SOLUONG ( NUMBER ) 
    public void setFiSoluong(String fiSoluong) {
        this.fiSoluong = fiSoluong;
    }

    public String getFiSoluong() {
        return this.fiSoluong;
    }

    //--- DATABASE MAPPING : FI_TONG ( NUMBER ) 
    public void setFiTong(String fiTong) {
        this.fiTong = fiTong;
    }

    public String getFiTong() {
        return this.fiTong;
    }

    //--- DATABASE MAPPING : FI_ID_HOSO ( NUMBER ) 
    public void setFiIdHoso(Long fiIdHoso) {
        this.fiIdHoso = fiIdHoso;
    }

    public Long getFiIdHoso() {
        return this.fiIdHoso;
    }

    //--- DATABASE MAPPING : FI_GHICHU ( VARCHAR2 ) 
    public void setFiGhichu(String fiGhichu) {
        this.fiGhichu = fiGhichu;
    }

    public String getFiGhichu() {
        return this.fiGhichu;
    }

    //--- DATABASE MAPPING : FI_NGAYTAO ( TIMESTAMP(6) ) 
    public void setFiNgaytao(Date fiNgaytao) {
        this.fiNgaytao = fiNgaytao;
    }

    public Date getFiNgaytao() {
        return this.fiNgaytao;
    }

    //--- DATABASE MAPPING : FI_HOATDONG ( NUMBER ) 
    public void setFiHoatdong(Long fiHoatdong) {
        this.fiHoatdong = fiHoatdong;
    }

    public Long getFiHoatdong() {
        return this.fiHoatdong;
    }

    //--- DATABASE MAPPING : FI_NGUOITAO ( VARCHAR2 ) 
    public void setFiNguoitao(String fiNguoitao) {
        this.fiNguoitao = fiNguoitao;
    }

    public String getFiNguoitao() {
        return this.fiNguoitao;
    }

    public List<Tbdtokhaihqd2> getToKhaiHQD2s() {
        return toKhaiHQD2s;
    }

    public void setToKhaiHQD2s(List<Tbdtokhaihqd2> toKhaiHQD2s) {
        this.toKhaiHQD2s = toKhaiHQD2s;
    }

    public Long getStt() {
        return stt;
    }

    public void setStt(Long stt) {
        this.stt = stt;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("[");
        sb.append(fiIdTk);
        sb.append("]:");
        sb.append(fiSoTk);
        sb.append("|");
        sb.append(fiNgayDk);
        sb.append("|");
        sb.append(fiMaHq);
        sb.append("|");
        sb.append(fiNguoiNk);
        sb.append("|");
        sb.append(fiDiachiNnk);
        sb.append("|");
        sb.append(fiDtNnk);
        sb.append("|");
        sb.append(fiNguoiXk);
        sb.append("|");
        sb.append(fiDiachiNxk);
        sb.append("|");
        sb.append(fiNuocXk);
        sb.append("|");
        sb.append(fiSoHoadon);
        sb.append("|");
        sb.append(fiNgayCapHd);
        sb.append("|");
        sb.append(fiSoluong);
        sb.append("|");
        sb.append(fiTong);
        sb.append("|");
        sb.append(fiIdHoso);
        sb.append("|");
        sb.append(fiGhichu);
        sb.append("|");
        sb.append(fiNgaytao);
        sb.append("|");
        sb.append(fiHoatdong);
        sb.append("|");
        sb.append(fiNguoitao);
        return sb.toString();
    }

}
