/*
 * Created on 18 Jul 2017 ( Time 08:39:33 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 
package com.nsw.mard.p8.model;

import lombok.Data;

import java.io.Serializable;

@Data
public class Tbdctyxk08 implements Serializable {
    private static final long serialVersionUID = 1L;

    private Long fiIdExporter;

    private Long fiIdHS;

    private String fiExporterName;

    private String fiExporterAddress;

    private String fiCountryOrigin;

    private String fiExporterTel;

    private String fiExporterFax;

    public Tbdctyxk08() {
    }

    public Tbdctyxk08(String fiExporterName, String fiExporterAddress) {
        this.fiExporterName = fiExporterName;
        this.fiExporterAddress = fiExporterAddress;
    }

    public Tbdctyxk08(String fiExporterName, String fiExporterAddress, String fiCountryOrigin, String fiExporterTel, String fiExporterFax) {
        this.fiExporterName = fiExporterName;
        this.fiExporterAddress = fiExporterAddress;
        this.fiCountryOrigin = fiCountryOrigin;
        this.fiExporterTel = fiExporterTel;
        this.fiExporterFax = fiExporterFax;
    }


}
