/*
 * Created on 18 Jul 2017 ( Time 08:39:33 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 
package com.nsw.mard.p8.model;

import lombok.Data;

import java.io.Serializable;

@Data
public class Tbdvstyclkd08 implements Serializable {
    private static final long serialVersionUID = 1L;

    private Long fiIdQuarLoc;

    private Long fiIdCV;

    private String fiIsoLocName;

    private String fiIsoLocAddress;

    public Tbdvstyclkd08() {
    }

    public Tbdvstyclkd08(String fiIsoLocName, String fiIsoLocAddress) {
        this.fiIsoLocName = fiIsoLocName;
        this.fiIsoLocAddress = fiIsoLocAddress;
    }

}
