/*
 * Created on 18 Jul 2017 ( Time 08:39:33 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 
package com.nsw.backend.mard.p06.model;

import com.nsw.backend.dic.model.CmonBaseEntity;
import lombok.Data;
import lombok.EqualsAndHashCode;

import javax.persistence.*;
import java.io.Serializable;

/**
 * Persistent class for entity stored in table "TBDCVHANGHOA06" - Thông tin hàng hóa cho công văn
 *
 * @author Telosys Tools Generator
 */
@Entity
@Data
@EqualsAndHashCode(callSuper = false)
@Table(name = "TBDCVHANGHOA06", schema = "MARD")
public class TbdCvHanghoa06 extends CmonBaseEntity implements Serializable {
    private static final long serialVersionUID = 1L;

    public static final String SEQUENCE_NAME = "TBDCVHANGHOA06_SEQ";

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(nullable = false)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = SEQUENCE_NAME)
    @SequenceGenerator(sequenceName = SEQUENCE_NAME, schema = "MARD", initialValue = 10000, allocationSize = 1, name = SEQUENCE_NAME)
    private Integer fiIdProduct;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS
    //----------------------------------------------------------------------
    @Column(name = "FI_CV_ID")
    private Integer fiIdCV;

    //ID phục vụ trừ lùi
    @Column(name = "FI_CV_PRODUCT_ID")
    private Integer fiId;

    @Column(name = "FI_PRODUCT_BIZ_NAME")
    private String fiProductBusinessName;

    @Column(name = "FI_PRODUCT_SCIENCE_NAME")
    private String fiProductScienceName;

    @Column(name = "FI_PACKAGE_UNIT_CODE")
    private String fiPackageUnitCode;

    @Column(name = "FI_PACKAGE_UNIT_NAME")
    private String fiPackageUnitName;

    @Column(name = "FI_ORIGIN_COUNTRY_CODE")
    private String fiOriginCountryCode;

    @Column(name = "FI_ORIGIN_COUNTRY_NAME")
    private String fiOriginCountryName;

    @Column(name = "FI_QUANTITY", precision = 15, scale = 6)
    private Double fiQuantity;

    @Column(name = "FI_QUANTITY_ORIGIN", precision = 15, scale = 6)
    private Double fiQuantityOrigin;

    @Column(name = "FI_SIZE_OR_TYPE")
    private String fiSizeOrType;

    public TbdCvHanghoa06() {
        super();
    }

    public TbdCvHanghoa06(String fiProductBusinessName, String fiProductScienceName, String fiPackageUnitCode, String fiPackageUnitName, String fiOriginCountryCode, String fiOriginCountryName, String fiSizeOrType) {
        this.fiProductBusinessName = fiProductBusinessName;
        this.fiProductScienceName = fiProductScienceName;
        this.fiPackageUnitCode = fiPackageUnitCode;
        this.fiPackageUnitName = fiPackageUnitName;
        this.fiOriginCountryCode = fiOriginCountryCode;
        this.fiOriginCountryName = fiOriginCountryName;
        this.fiSizeOrType = fiSizeOrType;
    }

    @PrePersist
    public void duplicateQuantityData() {
        this.fiQuantityOrigin = this.fiQuantity;
    }
}
