/*
 * Created on 13 Sep 2017 ( Time 10:43:33 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.nsw.most.p04.model;

import java.io.Serializable;

import java.util.Date;

public class Tbdlichsu4 implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long fiIdLichsu;

    private Long fiIdHoso;

    private String fiMaHoso;

    private String fiMaNggui;

    private String fiTenNggui;

    private String fiMaDvgui;

    private String fiTenDvgui;

    private String fiMaNgnhan;

    private String fiTenNgnhan;

    private String fiMaDvnhan;

    private String fiTenDvnhan;

    private String fiNoidung;

    private Long fiHoatdong;

    private String fiNguoitao;

    private Date fiNgaytao;

    private Long fiTrangthai;

    private String fiTenTt;
    
    private String fiFilePath;
    
    private String fiFileCode;
    
    private String fiFileName;
    
    private Date       fiNgayHhan   ;

    public Tbdlichsu4() {
        super();
    }

    public void setFiIdLichsu(Long fiIdLichsu) {
        this.fiIdLichsu = fiIdLichsu;
    }

    public Long getFiIdLichsu() {
        return this.fiIdLichsu;
    }

    public void setFiIdHoso(Long fiIdHoso) {
        this.fiIdHoso = fiIdHoso;
    }

    public Long getFiIdHoso() {
        return this.fiIdHoso;
    }

    public void setFiMaHoso(String fiMaHoso) {
        this.fiMaHoso = fiMaHoso;
    }

    public String getFiMaHoso() {
        return this.fiMaHoso;
    }

    //--- DATABASE MAPPING : FI_MA_NGGUI ( VARCHAR2 ) 
    public void setFiMaNggui(String fiMaNggui) {
        this.fiMaNggui = fiMaNggui;
    }

    public String getFiMaNggui() {
        return this.fiMaNggui;
    }

    //--- DATABASE MAPPING : FI_TEN_NGGUI ( VARCHAR2 ) 
    public void setFiTenNggui(String fiTenNggui) {
        this.fiTenNggui = fiTenNggui;
    }

    public String getFiTenNggui() {
        return this.fiTenNggui;
    }

    //--- DATABASE MAPPING : FI_MA_DVGUI ( VARCHAR2 ) 
    public void setFiMaDvgui(String fiMaDvgui) {
        this.fiMaDvgui = fiMaDvgui;
    }

    public String getFiMaDvgui() {
        return this.fiMaDvgui;
    }

    //--- DATABASE MAPPING : FI_TEN_DVGUI ( VARCHAR2 ) 
    public void setFiTenDvgui(String fiTenDvgui) {
        this.fiTenDvgui = fiTenDvgui;
    }

    public String getFiTenDvgui() {
        return this.fiTenDvgui;
    }

    //--- DATABASE MAPPING : FI_MA_NGNHAN ( VARCHAR2 ) 
    public void setFiMaNgnhan(String fiMaNgnhan) {
        this.fiMaNgnhan = fiMaNgnhan;
    }

    public String getFiMaNgnhan() {
        return this.fiMaNgnhan;
    }

    //--- DATABASE MAPPING : FI_TEN_NGNHAN ( VARCHAR2 ) 
    public void setFiTenNgnhan(String fiTenNgnhan) {
        this.fiTenNgnhan = fiTenNgnhan;
    }

    public String getFiTenNgnhan() {
        return this.fiTenNgnhan;
    }

    //--- DATABASE MAPPING : FI_MA_DVNHAN ( VARCHAR2 ) 
    public void setFiMaDvnhan(String fiMaDvnhan) {
        this.fiMaDvnhan = fiMaDvnhan;
    }

    public String getFiMaDvnhan() {
        return this.fiMaDvnhan;
    }

    //--- DATABASE MAPPING : FI_TEN_DVNHAN ( VARCHAR2 ) 
    public void setFiTenDvnhan(String fiTenDvnhan) {
        this.fiTenDvnhan = fiTenDvnhan;
    }

    public String getFiTenDvnhan() {
        return this.fiTenDvnhan;
    }

    //--- DATABASE MAPPING : FI_NOIDUNG ( VARCHAR2 ) 
    public void setFiNoidung(String fiNoidung) {
        this.fiNoidung = fiNoidung;
    }

    public String getFiNoidung() {
        return this.fiNoidung;
    }

    //--- DATABASE MAPPING : FI_HOATDONG ( NUMBER ) 
    public void setFiHoatdong(Long fiHoatdong) {
        this.fiHoatdong = fiHoatdong;
    }

    public Long getFiHoatdong() {
        return this.fiHoatdong;
    }

    //--- DATABASE MAPPING : FI_NGUOITAO ( VARCHAR2 ) 
    public void setFiNguoitao(String fiNguoitao) {
        this.fiNguoitao = fiNguoitao;
    }

    public String getFiNguoitao() {
        return this.fiNguoitao;
    }

    //--- DATABASE MAPPING : FI_NGAYTAO ( TIMESTAMP(6) ) 
    public void setFiNgaytao(Date fiNgaytao) {
        this.fiNgaytao = fiNgaytao;
    }

    public Date getFiNgaytao() {
        return this.fiNgaytao;
    }

    //--- DATABASE MAPPING : FI_TRANGTHAI ( NUMBER ) 
    public void setFiTrangthai(Long fiTrangthai) {
        this.fiTrangthai = fiTrangthai;
    }

    public Long getFiTrangthai() {
        return this.fiTrangthai;
    }

    //--- DATABASE MAPPING : FI_TEN_TT ( VARCHAR2 ) 
    public void setFiTenTt(String fiTenTt) {
        this.fiTenTt = fiTenTt;
    }

    public String getFiTenTt() {
        return this.fiTenTt;
    }
    
    public String getFiFilePath() {
        return fiFilePath;
    }

    public void setFiFilePath(String fiFilePath) {
        this.fiFilePath = fiFilePath;
    }

    public String getFiFileCode() {
        return fiFileCode;
    }

    public void setFiFileCode(String fiFileCode) {
        this.fiFileCode = fiFileCode;
    }

    public String getFiFileName() {
        return fiFileName;
    }

    public void setFiFileName(String fiFileName) {
        this.fiFileName = fiFileName;
    }

    public Date getFiNgayHhan() {
        return fiNgayHhan;
    }

    public void setFiNgayHhan(Date fiNgayHhan) {
        this.fiNgayHhan = fiNgayHhan;
    }
    
    

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("[");
        sb.append(fiIdLichsu);
        sb.append("]:");
        sb.append(fiIdHoso);
        sb.append("|");
        sb.append(fiMaHoso);
        sb.append("|");
        sb.append(fiMaNggui);
        sb.append("|");
        sb.append(fiTenNggui);
        sb.append("|");
        sb.append(fiMaDvgui);
        sb.append("|");
        sb.append(fiTenDvgui);
        sb.append("|");
        sb.append(fiMaNgnhan);
        sb.append("|");
        sb.append(fiTenNgnhan);
        sb.append("|");
        sb.append(fiMaDvnhan);
        sb.append("|");
        sb.append(fiTenDvnhan);
        sb.append("|");
        sb.append(fiNoidung);
        sb.append("|");
        sb.append(fiHoatdong);
        sb.append("|");
        sb.append(fiNguoitao);
        sb.append("|");
        sb.append(fiNgaytao);
        sb.append("|");
        sb.append(fiTrangthai);
        sb.append("|");
        sb.append(fiTenTt);
        return sb.toString();
    }

}
