/*
 * Created on 18 Jul 2017 ( Time 08:39:33 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 
package com.nsw.backend.mard.p07.model;

import com.nsw.backend.dic.model.CmonBaseEntity;
import com.nsw.backend.mard.p07.client.PhytosanitaryFee;
import lombok.Data;
import lombok.EqualsAndHashCode;
import org.springframework.beans.BeanUtils;

import javax.persistence.*;
import java.io.Serializable;

/**
 * Persistent class for entity stored in table "TBDHANGHOA07" - Hàng hóa
 *
 * @author Telosys Tools Generator
 */
@Entity
@Data
@EqualsAndHashCode(callSuper = false)
@Table(name = "TBDAPPHI07", schema = "MARD")
public class TbdApphi07 extends CmonBaseEntity implements Serializable {
    private static final long serialVersionUID = 1L;

    public static final String SEQUENCE_NAME = "TBDAPPHI07_SEQ";

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name = "FI_ID_FEE", nullable = false)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = SEQUENCE_NAME)
    @SequenceGenerator(sequenceName = SEQUENCE_NAME, schema = "MARD", initialValue = 10000, allocationSize = 1, name = SEQUENCE_NAME)
    private Integer fiIdFee;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS
    //----------------------------------------------------------------------
    @Column(name = "FI_NSW_FILE_CODE", length = 50)
    private String fiNSWFileCode;

    @Column(name = "FI_TYPE")
    private Integer fiType;

    @Column(name = "FI_TOTAL_FEE", precision = 15, scale = 3)
    private Double fiTotalFee;

    @Column(name = "FI_TOTAL_FEE_TEXT", length = 250)
    private String fiTotalFeeText;

    @Column(name = "FI_NOTE", length = 250)
    private String fiNote;

    @Column(name = "FI_DEPARTMENT", length = 250)
    private String fiDepartment;

    @Column(name = "FI_CREATOR_NAME", length = 250)
    private String fiCreaterName;


    public static TbdApphi07 parse(PhytosanitaryFee animalFee) {
        TbdApphi07 fee = new TbdApphi07();
        BeanUtils.copyProperties(animalFee, fee);
        return fee;
    }
}
