/*
 * Created on 2 Aug 2017 ( Time 15:47:00 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.nsw.most.p03.model;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

public class Tbdkhpdmau3 implements Serializable {

    
    private Long fiIdMau      ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    private Long fiIdHoso     ;

    private String     fiMaHoso     ;

    private Long fiIdQd       ;

    private String     fiKieu       ;

    private String     fiSoSx       ;

    private String     fiKhpdMau    ;

    private Date       fiNgaytao    ;

    private Long fiHoatdong   ;

    private String     fiNguoitao   ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Tbdkhpdmau3() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setFiIdMau( Long fiIdMau ) {
        this.fiIdMau = fiIdMau ;
    }
    public Long getFiIdMau() {
        return this.fiIdMau;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : FI_ID_HOSO ( NUMBER ) 
    public void setFiIdHoso( Long fiIdHoso ) {
        this.fiIdHoso = fiIdHoso;
    }
    public Long getFiIdHoso() {
        return this.fiIdHoso;
    }

    //--- DATABASE MAPPING : FI_MA_HOSO ( VARCHAR2 ) 
    public void setFiMaHoso( String fiMaHoso ) {
        this.fiMaHoso = fiMaHoso;
    }
    public String getFiMaHoso() {
        return this.fiMaHoso;
    }

    //--- DATABASE MAPPING : FI_ID_QD ( NUMBER ) 
    public void setFiIdQd( Long fiIdQd ) {
        this.fiIdQd = fiIdQd;
    }
    public Long getFiIdQd() {
        return this.fiIdQd;
    }

    //--- DATABASE MAPPING : FI_KIEU ( VARCHAR2 ) 
    public void setFiKieu( String fiKieu ) {
        this.fiKieu = fiKieu;
    }
    public String getFiKieu() {
        return this.fiKieu;
    }

    //--- DATABASE MAPPING : FI_SO_SX ( VARCHAR2 ) 
    public void setFiSoSx( String fiSoSx ) {
        this.fiSoSx = fiSoSx;
    }
    public String getFiSoSx() {
        return this.fiSoSx;
    }

    //--- DATABASE MAPPING : FI_KHPD_MAU ( VARCHAR2 ) 
    public void setFiKhpdMau( String fiKhpdMau ) {
        this.fiKhpdMau = fiKhpdMau;
    }
    public String getFiKhpdMau() {
        return this.fiKhpdMau;
    }

    //--- DATABASE MAPPING : FI_NGAYTAO ( TIMESTAMP(6) ) 
    public void setFiNgaytao( Date fiNgaytao ) {
        this.fiNgaytao = fiNgaytao;
    }
    public Date getFiNgaytao() {
        return this.fiNgaytao;
    }

    //--- DATABASE MAPPING : FI_HOATDONG ( NUMBER ) 
    public void setFiHoatdong( Long fiHoatdong ) {
        this.fiHoatdong = fiHoatdong;
    }
    public Long getFiHoatdong() {
        return this.fiHoatdong;
    }

    //--- DATABASE MAPPING : FI_NGUOITAO ( VARCHAR2 ) 
    public void setFiNguoitao( String fiNguoitao ) {
        this.fiNguoitao = fiNguoitao;
    }
    public String getFiNguoitao() {
        return this.fiNguoitao;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(fiIdMau);
        sb.append("]:"); 
        sb.append(fiIdHoso);
        sb.append("|");
        sb.append(fiMaHoso);
        sb.append("|");
        sb.append(fiIdQd);
        sb.append("|");
        sb.append(fiKieu);
        sb.append("|");
        sb.append(fiSoSx);
        sb.append("|");
        sb.append(fiKhpdMau);
        sb.append("|");
        sb.append(fiNgaytao);
        sb.append("|");
        sb.append(fiHoatdong);
        sb.append("|");
        sb.append(fiNguoitao);
        return sb.toString(); 
    } 

}
