/*
 * Created on 2 Aug 2017 ( Time 15:47:19 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 
package com.nsw.most.p03.model;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class Tbdquyetdinh3 implements Serializable{

    private Long fiIdQd;

    private Long fiIdHoso;

    private String fiMaHoso;

    private String fiSoQd;

    private Date fiNgayCap;

    private Long fiTongSl;

    private Long fiTrangthai;

    private Date fiNgayHetHan;

    private String fiNguoiKyQD;

    private String fiChucVu;

    private String fiNguoitao;

    private String fiSoCvTuchoi;
    
    private String     fiChiCucNhan     ;

    private List<Tbdhanghoa3> hangHoas;

    private List<Tbddinhkem3> dinhKems;

    public Tbdquyetdinh3() {
        super();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setFiIdQd(Long fiIdQd) {
        this.fiIdQd = fiIdQd;
    }

    public Long getFiIdQd() {
        return this.fiIdQd;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : FI_ID_HOSO ( NUMBER ) 
    public void setFiIdHoso(Long fiIdHoso) {
        this.fiIdHoso = fiIdHoso;
    }

    public Long getFiIdHoso() {
        return this.fiIdHoso;
    }

    //--- DATABASE MAPPING : FI_MA_HOSO ( VARCHAR2 ) 
    public void setFiMaHoso(String fiMaHoso) {
        this.fiMaHoso = fiMaHoso;
    }

    public String getFiMaHoso() {
        return this.fiMaHoso;
    }

    //--- DATABASE MAPPING : FI_SO_QD ( VARCHAR2 ) 
    public void setFiSoQd(String fiSoQd) {
        this.fiSoQd = fiSoQd;
    }

    public String getFiSoQd() {
        return this.fiSoQd;
    }

    //--- DATABASE MAPPING : FI_NGAY_CAP ( TIMESTAMP(6) ) 
    public void setFiNgayCap(Date fiNgayCap) {
        this.fiNgayCap = fiNgayCap;
    }

    public Date getFiNgayCap() {
        return this.fiNgayCap;
    }

    //--- DATABASE MAPPING : FI_TONG_SL ( NUMBER ) 
    public void setFiTongSl(Long fiTongSl) {
        this.fiTongSl = fiTongSl;
    }

    public Long getFiTongSl() {
        return this.fiTongSl;
    }

    //--- DATABASE MAPPING : FI_TRANGTHAI ( NUMBER ) 
    public void setFiTrangthai(Long fiTrangthai) {
        this.fiTrangthai = fiTrangthai;
    }

    public Long getFiTrangthai() {
        return this.fiTrangthai;
    }

    public Date getFiNgayHetHan() {
        return fiNgayHetHan;
    }

    public void setFiNgayHetHan(Date fiNgayHetHan) {
        this.fiNgayHetHan = fiNgayHetHan;
    }

    public String getFiNguoiKyQD() {
        return fiNguoiKyQD;
    }

    public void setFiNguoiKyQD(String fiNguoiKyQD) {
        this.fiNguoiKyQD = fiNguoiKyQD;
    }

    public String getFiChucVu() {
        return fiChucVu;
    }

    public void setFiChucVu(String fiChucVu) {
        this.fiChucVu = fiChucVu;
    }

    public String getFiNguoitao() {
        return fiNguoitao;
    }

    public void setFiNguoitao(String fiNguoitao) {
        this.fiNguoitao = fiNguoitao;
    }

    public String getFiSoCvTuchoi() {
        return fiSoCvTuchoi;
    }

    public void setFiSoCvTuchoi(String fiSoCvTuchoi) {
        this.fiSoCvTuchoi = fiSoCvTuchoi;
    }

    public String getFiChiCucNhan() {
        return fiChiCucNhan;
    }

    public void setFiChiCucNhan(String fiChiCucNhan) {
        this.fiChiCucNhan = fiChiCucNhan;
    }

    public List<Tbdhanghoa3> getHangHoas() {
        return hangHoas;
    }

    public void setHangHoas(List<Tbdhanghoa3> hangHoas) {
        this.hangHoas = hangHoas;
    }

    public List<Tbddinhkem3> getDinhKems() {
        return dinhKems;
    }

    public void setDinhKems(List<Tbddinhkem3> dinhKems) {
        this.dinhKems = dinhKems;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("[");
        sb.append(fiIdQd);
        sb.append("]:");
        sb.append(fiIdHoso);
        sb.append("|");
        sb.append(fiMaHoso);
        sb.append("|");
        sb.append(fiSoQd);
        sb.append("|");
        sb.append(fiNgayCap);
        sb.append("|");
        sb.append(fiTongSl);
        sb.append("|");
        sb.append(fiTrangthai);
        return sb.toString();
    }

}
