/*
 * Created on 2 Aug 2017 ( Time 15:47:40 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 
package com.nsw.most.p03.model;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.nsw.util.CustomJsonDateDeserializer;
import java.io.Serializable;

import java.util.Date;

public class Tbdtokhaihqd3 implements Serializable {

    private Long fiIdSp;

    private String fiMaHs;

    private String fiTenHh;

    private String fiKlSl;

    private String fiTenDv;
    private Long fiIdTk;

    private String fiGhichu;

    private Date fiNgaytao;

    private Long fiHoatdong;

    private String fiNguoitao;

    private String fiMaql;

    private Long stt;

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Tbdtokhaihqd3() {
        super();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setFiIdSp(Long fiIdSp) {
        this.fiIdSp = fiIdSp;
    }

    public Long getFiIdSp() {
        return this.fiIdSp;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : FI_MA_HOSO ( VARCHAR2 ) 
    public String getFiMaHs() {
        return fiMaHs;
    }

    public void setFiMaHs(String fiMaHs) {
        this.fiMaHs = fiMaHs;
    }

    //--- DATABASE MAPPING : FI_TEN_HH ( VARCHAR2 ) 
    public void setFiTenHh(String fiTenHh) {
        this.fiTenHh = fiTenHh;
    }

    public String getFiTenHh() {
        return this.fiTenHh;
    }

    //--- DATABASE MAPPING : FI_KL_SL ( NUMBER ) 
    public void setFiKlSl(String fiKlSl) {
        this.fiKlSl = fiKlSl;
    }

    public String getFiKlSl() {
        return this.fiKlSl;
    }

    //--- DATABASE MAPPING : FI_TEN_DV ( VARCHAR2 ) 
    public void setFiTenDv(String fiTenDv) {
        this.fiTenDv = fiTenDv;
    }

    public String getFiTenDv() {
        return this.fiTenDv;
    }

    //--- DATABASE MAPPING : FI_ID_TK ( NUMBER ) 
    public void setFiIdTk(Long fiIdTk) {
        this.fiIdTk = fiIdTk;
    }

    public Long getFiIdTk() {
        return this.fiIdTk;
    }

    //--- DATABASE MAPPING : FI_GHICHU ( VARCHAR2 ) 
    public void setFiGhichu(String fiGhichu) {
        this.fiGhichu = fiGhichu;
    }

    public String getFiGhichu() {
        return this.fiGhichu;
    }

    //--- DATABASE MAPPING : FI_NGAYTAO ( TIMESTAMP(6) )
    @JsonDeserialize(using = CustomJsonDateDeserializer.class)
    public void setFiNgaytao(Date fiNgaytao) {
        this.fiNgaytao = fiNgaytao;
    }

    public Date getFiNgaytao() {
        return this.fiNgaytao;
    }

    //--- DATABASE MAPPING : FI_HOATDONG ( NUMBER ) 
    public void setFiHoatdong(Long fiHoatdong) {
        this.fiHoatdong = fiHoatdong;
    }

    public Long getFiHoatdong() {
        return this.fiHoatdong;
    }

    //--- DATABASE MAPPING : FI_NGUOITAO ( VARCHAR2 ) 
    public void setFiNguoitao(String fiNguoitao) {
        this.fiNguoitao = fiNguoitao;
    }

    public String getFiNguoitao() {
        return this.fiNguoitao;
    }

    //--- DATABASE MAPPING : FI_MAQL ( VARCHAR2 ) 
    public void setFiMaql(String fiMaql) {
        this.fiMaql = fiMaql;
    }

    public String getFiMaql() {
        return this.fiMaql;
    }

    public Long getStt() {
        return stt;
    }

    public void setStt(Long stt) {
        this.stt = stt;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("[");
        sb.append(fiIdSp);
        sb.append("]:");
        //sb.append(fiMaHoso);
        sb.append("|");
        sb.append(fiTenHh);
        sb.append("|");
        sb.append(fiKlSl);
        sb.append("|");
        sb.append(fiTenDv);
        sb.append("|");
        sb.append(fiIdTk);
        sb.append("|");
        sb.append(fiGhichu);
        sb.append("|");
        sb.append(fiNgaytao);
        sb.append("|");
        sb.append(fiHoatdong);
        sb.append("|");
        sb.append(fiNguoitao);
        sb.append("|");
        sb.append(fiMaql);
        return sb.toString();
    }

}
