/*
 * Created on 21 Dec 2018 ( Time 23:45:14 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 
package com.nsw.moh.p19.model;

import java.io.Serializable;

import java.util.Date;
import java.util.List;

public class Tbdcongvan19 implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long fiIdCv;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    //@Column(name="FI_ID_HOSO")
    private Long fiIdHoso;

    //@Column(name="FI_MA_HOSO", length=50)
    private String fiMaHoso;

    //@Column(name="FI_CO_QUAN_CAP", length=10)
    private String fiCoQuanCap;

    //@Column(name="FI_SO_CONG_VAN", length=50)
    private String fiSoCongVan;

    //@Temporal(TemporalType.TIMESTAMP)
    //@Column(name="FI_NGAY_KY")
    private Date fiNgayKy;

    //@Column(name="FI_NGUOI_KY", length=250)
    private String fiNguoiKy;

    //@Temporal(TemporalType.TIMESTAMP)
    //@Column(name="FI_NGAY_HET_HL")
    private Date fiNgayHetHl;

    //@Column(name="FI_LOAI_DON")
    private Long fiLoaiDon;

    //@Column(name="FI_HOATDONG")
    private Long fiHoatdong;

    //@Column(name="FI_NGUOITAO", length=50)
    private String fiNguoitao;

    //@Temporal(TemporalType.TIMESTAMP)
    //@Column(name="FI_NGAYTAO")
    private Date fiNgaytao;

    //@Temporal(TemporalType.TIMESTAMP)
    //@Column(name="FI_NG_CAPNHAT")
    private Date fiNgCapnhat;

    //@Transient
    private TbdcvDinhkem19 dinhKemCongVan;

    //@Transient
    private TbdcvDinhkem19 dinhKemDonHang;

    //@Transient
    private TbdcvDonhang19 donHang;

    //@Transient
    private List<TbdcvCuakhau19> lstCuaKhaus;

    //@Transient
    private List<TbdcvDinhkem19> lstDinhKems;

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Tbdcongvan19() {
        super();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setFiIdCv(Long fiIdCv) {
        this.fiIdCv = fiIdCv;
    }

    public Long getFiIdCv() {
        return this.fiIdCv;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : FI_ID_HOSO ( NUMBER ) 
    public void setFiIdHoso(Long fiIdHoso) {
        this.fiIdHoso = fiIdHoso;
    }

    public Long getFiIdHoso() {
        return this.fiIdHoso;
    }

    //--- DATABASE MAPPING : FI_MA_HOSO ( VARCHAR2 ) 
    public void setFiMaHoso(String fiMaHoso) {
        this.fiMaHoso = fiMaHoso;
    }

    public String getFiMaHoso() {
        return this.fiMaHoso;
    }

    //--- DATABASE MAPPING : FI_CO_QUAN_CAP ( VARCHAR2 ) 
    public void setFiCoQuanCap(String fiCoQuanCap) {
        this.fiCoQuanCap = fiCoQuanCap;
    }

    public String getFiCoQuanCap() {
        return this.fiCoQuanCap;
    }

    //--- DATABASE MAPPING : FI_SO_CONG_VAN ( VARCHAR2 ) 
    public void setFiSoCongVan(String fiSoCongVan) {
        this.fiSoCongVan = fiSoCongVan;
    }

    public String getFiSoCongVan() {
        return this.fiSoCongVan;
    }

    //--- DATABASE MAPPING : FI_NGAY_KY ( TIMESTAMP(6) ) 
    public void setFiNgayKy(Date fiNgayKy) {
        this.fiNgayKy = fiNgayKy;
    }

    public Date getFiNgayKy() {
        return this.fiNgayKy;
    }

    //--- DATABASE MAPPING : FI_NGUOI_KY ( VARCHAR2 ) 
    public void setFiNguoiKy(String fiNguoiKy) {
        this.fiNguoiKy = fiNguoiKy;
    }

    public String getFiNguoiKy() {
        return this.fiNguoiKy;
    }

    //--- DATABASE MAPPING : FI_NGAY_HET_HL ( TIMESTAMP(6) ) 
    public void setFiNgayHetHl(Date fiNgayHetHl) {
        this.fiNgayHetHl = fiNgayHetHl;
    }

    public Date getFiNgayHetHl() {
        return this.fiNgayHetHl;
    }

    //--- DATABASE MAPPING : FI_LOAI_DON ( NUMBER ) 
    public void setFiLoaiDon(Long fiLoaiDon) {
        this.fiLoaiDon = fiLoaiDon;
    }

    public Long getFiLoaiDon() {
        return this.fiLoaiDon;
    }

    //--- DATABASE MAPPING : FI_HOATDONG ( NUMBER ) 
    public void setFiHoatdong(Long fiHoatdong) {
        this.fiHoatdong = fiHoatdong;
    }

    public Long getFiHoatdong() {
        return this.fiHoatdong;
    }

    //--- DATABASE MAPPING : FI_NGUOITAO ( VARCHAR2 ) 
    public void setFiNguoitao(String fiNguoitao) {
        this.fiNguoitao = fiNguoitao;
    }

    public String getFiNguoitao() {
        return this.fiNguoitao;
    }

    //--- DATABASE MAPPING : FI_NGAYTAO ( TIMESTAMP(6) ) 
    public void setFiNgaytao(Date fiNgaytao) {
        this.fiNgaytao = fiNgaytao;
    }

    public Date getFiNgaytao() {
        return this.fiNgaytao;
    }

    //--- DATABASE MAPPING : FI_NG_CAPNHAT ( TIMESTAMP(6) ) 
    public void setFiNgCapnhat(Date fiNgCapnhat) {
        this.fiNgCapnhat = fiNgCapnhat;
    }

    public Date getFiNgCapnhat() {
        return this.fiNgCapnhat;
    }

    public TbdcvDonhang19 getDonHang() {
        return donHang;
    }

    public void setDonHang(TbdcvDonhang19 donHang) {
        this.donHang = donHang;
    }

    public List<TbdcvCuakhau19> getLstCuaKhaus() {
        return lstCuaKhaus;
    }

    public void setLstCuaKhaus(List<TbdcvCuakhau19> lstCuaKhaus) {
        this.lstCuaKhaus = lstCuaKhaus;
    }

    public List<TbdcvDinhkem19> getLstDinhKems() {
        return lstDinhKems;
    }

    public void setLstDinhKems(List<TbdcvDinhkem19> lstDinhKems) {
        this.lstDinhKems = lstDinhKems;
    }

    public TbdcvDinhkem19 getDinhKemCongVan() {
        return dinhKemCongVan;
    }

    public void setDinhKemCongVan(TbdcvDinhkem19 dinhKemCongVan) {
        this.dinhKemCongVan = dinhKemCongVan;
    }

    public TbdcvDinhkem19 getDinhKemDonHang() {
        return dinhKemDonHang;
    }

    public void setDinhKemDonHang(TbdcvDinhkem19 dinhKemDonHang) {
        this.dinhKemDonHang = dinhKemDonHang;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("[");
        sb.append(fiIdCv);
        sb.append("]:");
        sb.append(fiIdHoso);
        sb.append("|");
        sb.append(fiMaHoso);
        sb.append("|");
        sb.append(fiCoQuanCap);
        sb.append("|");
        sb.append(fiSoCongVan);
        sb.append("|");
        sb.append(fiNgayKy);
        sb.append("|");
        sb.append(fiNguoiKy);
        sb.append("|");
        sb.append(fiNgayHetHl);
        sb.append("|");
        sb.append(fiLoaiDon);
        sb.append("|");
        sb.append(fiHoatdong);
        sb.append("|");
        sb.append(fiNguoitao);
        sb.append("|");
        sb.append(fiNgaytao);
        sb.append("|");
        sb.append(fiNgCapnhat);
        return sb.toString();
    }

}
