/*
 * Created on 20 Apr 2017 ( Time 15:14:07 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 
package com.nsw.most.p01.model;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class TbdkqktHh1 implements Serializable {

    private Long fiIdKqkthh;

    private Long fiIdCqxl;

    private String fiSoTb;

    private Date fiNgayTb;

    private String fiNguoiKy;

    private String fiMaDv;

    private String fiTenDv;

    private String fiSoDkkt;

    private Date fiNgayTnhan;

    private String fiSoCnhq;

    private Date fiNgaycap;

    private String fiMaTcgd;

    private String fiTenTcgd;

    private Date fiNgaytao;

    private Long fiTrangthai;

    private String fiMaDvThu;

    private String fiTendvThu;

    private Date fiNgayThuhoi;

    private String fiLydoThuhoi;

    private String fiCvienThuhoi;

    private String fiFileCode;

    private String fiFileName;

    private String fiFilePath;

    private String fiMahs;

    private Tbdhoso1 tbdhoso;
    
    private List<Tbddinhkem1> tepDinhKem;

    private List<Tbdhanghoa1> lstTbdhanghoa1;

    // ----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    // ----------------------------------------------------------------------
    // ----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    // ----------------------------------------------------------------------
    public TbdkqktHh1() {
        super();
    }

    // ----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    // ----------------------------------------------------------------------
    public void setFiIdKqkthh(Long fiIdKqkthh) {
        this.fiIdKqkthh = fiIdKqkthh;
    }

    public Long getFiIdKqkthh() {
        return this.fiIdKqkthh;
    }

    // ----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    // ----------------------------------------------------------------------
    // --- DATABASE MAPPING : FI_ID_CQXL ( NUMBER )
    public void setFiIdCqxl(Long fiIdCqxl) {
        this.fiIdCqxl = fiIdCqxl;
    }

    public Long getFiIdCqxl() {
        return this.fiIdCqxl;
    }

    // --- DATABASE MAPPING : FI_SO_TB ( VARCHAR2 )
    public void setFiSoTb(String fiSoTb) {
        this.fiSoTb = fiSoTb;
    }

    public String getFiSoTb() {
        return this.fiSoTb;
    }

    // --- DATABASE MAPPING : FI_NGAY_TB ( DATE )
    public void setFiNgayTb(Date fiNgayTb) {
        this.fiNgayTb = fiNgayTb;
    }

    public Date getFiNgayTb() {
        return this.fiNgayTb;
    }

    // --- DATABASE MAPPING : FI_NGUOI_KY ( VARCHAR2 )
    public void setFiNguoiKy(String fiNguoiKy) {
        this.fiNguoiKy = fiNguoiKy;
    }

    public String getFiNguoiKy() {
        return this.fiNguoiKy;
    }

    // --- DATABASE MAPPING : FI_MA_DV ( VARCHAR2 )
    public void setFiMaDv(String fiMaDv) {
        this.fiMaDv = fiMaDv;
    }

    public String getFiMaDv() {
        return this.fiMaDv;
    }

    // --- DATABASE MAPPING : FI_TEN_DV ( VARCHAR2 )
    public void setFiTenDv(String fiTenDv) {
        this.fiTenDv = fiTenDv;
    }

    public String getFiTenDv() {
        return this.fiTenDv;
    }

    // --- DATABASE MAPPING : FI_SO_DKKT ( VARCHAR2 )
    public void setFiSoDkkt(String fiSoDkkt) {
        this.fiSoDkkt = fiSoDkkt;
    }

    public String getFiSoDkkt() {
        return this.fiSoDkkt;
    }

    // --- DATABASE MAPPING : FI_NGAY_TNHAN ( DATE )
    public void setFiNgayTnhan(Date fiNgayTnhan) {
        this.fiNgayTnhan = fiNgayTnhan;
    }

    public Date getFiNgayTnhan() {
        return this.fiNgayTnhan;
    }

    // --- DATABASE MAPPING : FI_SO_CNHQ ( VARCHAR2 )
    public void setFiSoCnhq(String fiSoCnhq) {
        this.fiSoCnhq = fiSoCnhq;
    }

    public String getFiSoCnhq() {
        return this.fiSoCnhq;
    }

    // --- DATABASE MAPPING : FI_NGAYCAP ( DATE )
    public void setFiNgaycap(Date fiNgaycap) {
        this.fiNgaycap = fiNgaycap;
    }

    public Date getFiNgaycap() {
        return this.fiNgaycap;
    }

    // --- DATABASE MAPPING : FI_MA_TCGD ( VARCHAR2 )
    public void setFiMaTcgd(String fiMaTcgd) {
        this.fiMaTcgd = fiMaTcgd;
    }

    public String getFiMaTcgd() {
        return this.fiMaTcgd;
    }

    // --- DATABASE MAPPING : FI_TEN_TCGD ( VARCHAR2 )
    public void setFiTenTcgd(String fiTenTcgd) {
        this.fiTenTcgd = fiTenTcgd;
    }

    public String getFiTenTcgd() {
        return this.fiTenTcgd;
    }

    // --- DATABASE MAPPING : FI_NGAYTAO ( DATE )
    public void setFiNgaytao(Date fiNgaytao) {
        this.fiNgaytao = fiNgaytao;
    }

    public Date getFiNgaytao() {
        return this.fiNgaytao;
    }

    // --- DATABASE MAPPING : FI_TRANGTHAI ( NUMBER )
    public void setFiTrangthai(Long fiTrangthai) {
        this.fiTrangthai = fiTrangthai;
    }

    public Long getFiTrangthai() {
        return this.fiTrangthai;
    }

    // --- DATABASE MAPPING : FI_MA_DV_THU ( VARCHAR2 )
    public void setFiMaDvThu(String fiMaDvThu) {
        this.fiMaDvThu = fiMaDvThu;
    }

    public String getFiMaDvThu() {
        return this.fiMaDvThu;
    }

    // --- DATABASE MAPPING : FI_TENDV_THU ( VARCHAR2 )
    public void setFiTendvThu(String fiTendvThu) {
        this.fiTendvThu = fiTendvThu;
    }

    public String getFiTendvThu() {
        return this.fiTendvThu;
    }

    // --- DATABASE MAPPING : FI_NGAY_THUHOI ( DATE )
    public void setFiNgayThuhoi(Date fiNgayThuhoi) {
        this.fiNgayThuhoi = fiNgayThuhoi;
    }

    public Date getFiNgayThuhoi() {
        return this.fiNgayThuhoi;
    }

    // --- DATABASE MAPPING : FI_LYDO_THUHOI ( VARCHAR2 )
    public void setFiLydoThuhoi(String fiLydoThuhoi) {
        this.fiLydoThuhoi = fiLydoThuhoi;
    }

    public String getFiLydoThuhoi() {
        return this.fiLydoThuhoi;
    }

    // --- DATABASE MAPPING : FI_CVIEN_THUHOI ( VARCHAR2 )
    public void setFiCvienThuhoi(String fiCvienThuhoi) {
        this.fiCvienThuhoi = fiCvienThuhoi;
    }

    public String getFiCvienThuhoi() {
        return this.fiCvienThuhoi;
    }

    public String getFiFileCode() {
        return fiFileCode;
    }

    public void setFiFileCode(String fiFileCode) {
        this.fiFileCode = fiFileCode;
    }

    public String getFiFileName() {
        return fiFileName;
    }

    public void setFiFileName(String fiFileName) {
        this.fiFileName = fiFileName;
    }

    public String getFiFilePath() {
        return fiFilePath;
    }

    public void setFiFilePath(String fiFilePath) {
        this.fiFilePath = fiFilePath;
    }

    public String getFiMahs() {
        return fiMahs;
    }

    public void setFiMahs(String fiMahs) {
        this.fiMahs = fiMahs;
    }

    public Tbdhoso1 getTbdhoso() {
        return tbdhoso;
    }

    public void setTbdhoso(Tbdhoso1 tbdhoso) {
        this.tbdhoso = tbdhoso;
    }

    public List<Tbddinhkem1> getTepDinhKem() {
        return tepDinhKem;
    }

    public void setTepDinhKem(List<Tbddinhkem1> tepDinhKem) {
        this.tepDinhKem = tepDinhKem;
    }

    public List<Tbdhanghoa1> getLstTbdhanghoa1() {
        return lstTbdhanghoa1;
    }

    public void setLstTbdhanghoa1(List<Tbdhanghoa1> lstTbdhanghoa1) {
        this.lstTbdhanghoa1 = lstTbdhanghoa1;
    }

    // ----------------------------------------------------------------------
    // toString METHOD
    // ----------------------------------------------------------------------
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("[");
        sb.append(fiIdKqkthh);
        sb.append("]:");
        sb.append(fiIdCqxl);
        sb.append("|");
        sb.append(fiSoTb);
        sb.append("|");
        sb.append(fiNgayTb);
        sb.append("|");
        sb.append(fiNguoiKy);
        sb.append("|");
        sb.append(fiMaDv);
        sb.append("|");
        sb.append(fiTenDv);
        sb.append("|");
        sb.append(fiSoDkkt);
        sb.append("|");
        sb.append(fiNgayTnhan);
        sb.append("|");
        sb.append(fiSoCnhq);
        sb.append("|");
        sb.append(fiNgaycap);
        sb.append("|");
        sb.append(fiMaTcgd);
        sb.append("|");
        sb.append(fiTenTcgd);
        sb.append("|");
        sb.append(fiNgaytao);
        sb.append("|");
        sb.append(fiTrangthai);
        sb.append("|");
        sb.append(fiMaDvThu);
        sb.append("|");
        sb.append(fiTendvThu);
        sb.append("|");
        sb.append(fiNgayThuhoi);
        sb.append("|");
        sb.append(fiLydoThuhoi);
        sb.append("|");
        sb.append(fiCvienThuhoi);
        return sb.toString();
    }

}
