/*
 * Created on 25 Jul 2017 ( Time 08:16:39 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 
package com.nsw.backend.dic.model;

import java.io.Serializable;
import javax.persistence.*;

/**
 * Persistent class for entity stored in table "CMON_PORT"
 *
 * @author Telosys Tools Generator
 *
 */
@Entity
@Table(name = "\"Cmon_Port\"", schema = "MARD")
// Define named queries here
@NamedQueries({
    @NamedQuery(name = "CmonPort.countAll", query = "SELECT COUNT(x) FROM CmonPort x")
})
public class CmonPort implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @Column(name = "\"PortID\"")
    private Long portid;

    @Column(name = "\"PortCode\"", length = 10)
    private String portcode;

    @Column(name = "\"PortName\"")
    private String portname;

    @Column(name = "\"SystemID\"")
    private Long systemid;

    @Column(name = "\"StateCode\"", length = 10)
    private String statecode;

    @Column(name = "\"PortNameEn\"", length = 250)
    private String portnameen;

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public CmonPort() {
        super();
    }

    public CmonPort(String portcode, String portname, Long systemid, String statecode, String portnameen) {
        this.portcode = portcode;
        this.portname = portname;
        this.systemid = systemid;
        this.statecode = statecode;
        this.portnameen = portnameen;
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : PortID ( NUMBER ) 
    public void setPortid(Long portid) {
        this.portid = portid;
    }

    public Long getPortid() {
        return this.portid;
    }

    //--- DATABASE MAPPING : PortCode ( VARCHAR2 ) 
    public void setPortcode(String portcode) {
        this.portcode = portcode;
    }

    public String getPortcode() {
        return this.portcode;
    }

    //--- DATABASE MAPPING : PortName ( NVARCHAR2 ) 
    public void setPortname(String portname) {
        this.portname = portname;
    }

    public String getPortname() {
        return this.portname;
    }

    //--- DATABASE MAPPING : SystemID ( NUMBER ) 
    public void setSystemid(Long systemid) {
        this.systemid = systemid;
    }

    public Long getSystemid() {
        return this.systemid;
    }

    //--- DATABASE MAPPING : StateCode ( VARCHAR2 ) 
    public void setStatecode(String statecode) {
        this.statecode = statecode;
    }

    public String getStatecode() {
        return this.statecode;
    }

    //--- DATABASE MAPPING : PortNameEn ( VARCHAR2 ) 
    public void setPortnameen(String portnameen) {
        this.portnameen = portnameen;
    }

    public String getPortnameen() {
        return this.portnameen;
    }

    
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("[");
        sb.append("]:");
        sb.append(portid);
        sb.append("|");
        sb.append(portcode);
        sb.append("|");
        sb.append(portname);
        sb.append("|");
        sb.append(systemid);
        sb.append("|");
        sb.append(statecode);
        sb.append("|");
        sb.append(portnameen);
        return sb.toString();
    }

}
