/*
 * Created on 25 Jul 2017 ( Time 08:16:42 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 
package com.nsw.backend.dic.model;

import java.io.Serializable;
import javax.persistence.*;

/**
 * Persistent class for entity stored in table "CMON_PROVINCE"
 *
 * @author Telosys Tools Generator
 *
 */
@Entity
@Table(name = "\"Cmon_Province\"", schema = "MARD")
// Define named queries here
@NamedQueries({
    @NamedQuery(name = "CmonProvince.countAll", query = "SELECT COUNT(x) FROM CmonProvince x")
})
public class CmonProvince implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @Column(name = "\"PROVINCE_ID\"")
    private Long provinceId;

    @Column(name = "\"PROVINCE_NAME\"")
    private String provinceName;

    @Column(name = "\"PROVINCE_CODE\"")
    private String provinceCode;

    @Column(name = "\"IS_DELETED\"", length = 1)
    private String isDeleted;

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public CmonProvince() {
        super();
    }

    public CmonProvince(String provinceName, String provinceCode) {
        this.provinceName = provinceName;
        this.provinceCode = provinceCode;
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : PROVINCE_ID ( NUMBER ) 
    public void setProvinceId(Long provinceId) {
        this.provinceId = provinceId;
    }

    public Long getProvinceId() {
        return this.provinceId;
    }

    //--- DATABASE MAPPING : PROVINCE_NAME ( NVARCHAR2 ) 
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName;
    }

    public String getProvinceName() {
        return this.provinceName;
    }

    //--- DATABASE MAPPING : PROVINCE_CODE ( NCHAR ) 
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode;
    }

    public String getProvinceCode() {
        return this.provinceCode;
    }

    //--- DATABASE MAPPING : IS_DELETED ( CHAR ) 
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }

    public String getIsDeleted() {
        return this.isDeleted;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("[");
        sb.append("]:");
        sb.append(provinceId);
        sb.append("|");
        sb.append(provinceName);
        sb.append("|");
        sb.append(provinceCode);
        sb.append("|");
        sb.append(isDeleted);
        return sb.toString();
    }

}
