/*
 * Created on 25 Jul 2017 ( Time 08:17:04 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 
package com.nsw.backend.dic.model;

import java.io.Serializable;
import javax.persistence.*;

/**
 * Persistent class for entity stored in table "CMON_SYSTEM"
 *
 * @author Telosys Tools Generator
 *
 */
@Entity
@Table(name = "\"Cmon_System\"", schema = "MARD")
// Define named queries here
@NamedQueries({
    @NamedQuery(name = "CmonSystem.countAll", query = "SELECT COUNT(x) FROM CmonSystem x")
})
public class CmonSystem implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @Column(name = "\"SystemID\"")
    private Long systemid;

    @Column(name = "\"SystemName\"")
    private String systemname;

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public CmonSystem() {
        super();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : SystemID ( NUMBER ) 
    public void setSystemid(Long systemid) {
        this.systemid = systemid;
    }

    public Long getSystemid() {
        return this.systemid;
    }

    //--- DATABASE MAPPING : SystemName ( NVARCHAR2 ) 
    public void setSystemname(String systemname) {
        this.systemname = systemname;
    }

    public String getSystemname() {
        return this.systemname;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("[");
        sb.append("]:");
        sb.append(systemid);
        sb.append("|");
        sb.append(systemname);
        return sb.toString();
    }

}
