/*
 * Created on 25 Jul 2017 ( Time 08:15:33 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 
package com.nsw.backend.dic.model;

import lombok.Data;

import java.io.Serializable;
import javax.persistence.*;

/**
 * Persistent class for entity - Danh sách đính kèm giai đoạn 2
 *
 * @author Telosys Tools Generator
 *
 */
@Data
@Entity
@Table(name = "CMON_ATCH_PHS2", schema = "MARD")
public class CmonAttachmentTypePhase2 implements Serializable {
    private static final long serialVersionUID = 1L;

    public static final String SEQUENCE_NAME = "CMON_ATCH_PHS2_SEQ";

    @Id
    @Column(name = "ID", nullable = false)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = SEQUENCE_NAME)
    @SequenceGenerator(sequenceName = SEQUENCE_NAME, schema = "MARD", initialValue = 1, allocationSize = 1, name = SEQUENCE_NAME)
    private Long atchId;

    @Column(name = "ATCHTYPEID")
    private Long atchTypeId;

    @Column(name = "ATCHTYPECODE")
    private String atchTypeCode;

    @Column(name = "ATCHTYPENAME")
    private String atchTypeName;

    @Column(name = "TEMPLATETYPE")
    private String templateType;

    @Column(name = "SYSTEMID")
    private Long systemId;

    @Column(name = "REQUIRED")
    private boolean required;

    public CmonAttachmentTypePhase2() {
        super();
    }

    public CmonAttachmentTypePhase2(Long atchTypeId, String atchTypeCode, String atchTypeName, String templateType, Long systemId, boolean required) {
        this.atchTypeId = atchTypeId;
        this.atchTypeCode = atchTypeCode;
        this.atchTypeName = atchTypeName;
        this.templateType = templateType;
        this.systemId = systemId;
        this.required = required;
    }

    public CmonAttachmentTypePhase2(Long attachtypeid, String atchTypeCode, String atchTypeName, Long systemId) {
        this(attachtypeid, atchTypeCode, atchTypeName, "", systemId, false);
    }

    public CmonAttachmentTypePhase2(Long attachtypeid, String atchTypeCode, String atchTypeName, Long systemId, boolean required) {
        this(attachtypeid, atchTypeCode, atchTypeName, "", systemId, required);
    }

    public CmonAttachmentTypePhase2(Long attachtypeid, String atchTypeCode, String atchTypeName, String templateType, Long systemId) {
        this(attachtypeid, atchTypeCode, atchTypeName, templateType, systemId, false);
    }

    @Transient
    public String getName(){
        return this.atchTypeName;
    }

    @Transient
    public Long getId(){
        return this.atchTypeId;
    }
}
