/*
 * Created on 25 Jul 2017 ( Time 08:17:22 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 
package com.nsw.backend.dic.model;

import java.io.Serializable;
import javax.persistence.*;

/**
 * Persistent class for entity stored in table "CMON_UNIT"
 *
 * @author Telosys Tools Generator
 *
 */
@Entity
@Table(name = "\"Cmon_Unit\"", schema = "MARD")
// Define named queries here
@NamedQueries({
    @NamedQuery(name = "CmonUnit.countAll", query = "SELECT COUNT(x) FROM CmonUnit x")
})
public class CmonUnit implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @Column(name = "\"UnitID\"")
    private Long unitid;

    @Column(name = "\"UnitCode\"", length = 15)
    private String unitcode;

    @Column(name = "\"UnitName\"", length = 250)
    private String unitname;

    @Column(name = "\"SystemID\"")
    private Long systemid;

    @Column(name = "\"UnitTypeID\"")
    private Long unittypeid;

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public CmonUnit() {
        super();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : UnitID ( NUMBER ) 
    public void setUnitid(Long unitid) {
        this.unitid = unitid;
    }

    public Long getUnitid() {
        return this.unitid;
    }

    //--- DATABASE MAPPING : UnitCode ( VARCHAR2 ) 
    public void setUnitcode(String unitcode) {
        this.unitcode = unitcode;
    }

    public String getUnitcode() {
        return this.unitcode;
    }

    //--- DATABASE MAPPING : UnitName ( VARCHAR2 ) 
    public void setUnitname(String unitname) {
        this.unitname = unitname;
    }

    public String getUnitname() {
        return this.unitname;
    }

    //--- DATABASE MAPPING : SystemID ( NUMBER ) 
    public void setSystemid(Long systemid) {
        this.systemid = systemid;
    }

    public Long getSystemid() {
        return this.systemid;
    }

    //--- DATABASE MAPPING : UnitTypeID ( NUMBER ) 
    public void setUnittypeid(Long unittypeid) {
        this.unittypeid = unittypeid;
    }

    public Long getUnittypeid() {
        return this.unittypeid;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("[");
        sb.append("]:");
        sb.append(unitid);
        sb.append("|");
        sb.append(unitcode);
        sb.append("|");
        sb.append(unitname);
        sb.append("|");
        sb.append(systemid);
        sb.append("|");
        sb.append(unittypeid);
        return sb.toString();
    }

}
