/*
 * Created on 25 Jul 2017 ( Time 08:16:10 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 
package com.nsw.backend.dic.model;

import java.io.Serializable;
import javax.persistence.*;

/**
 * Persistent class for entity stored in table "CMON_COUNTRY"
 *
 * @author Telosys Tools Generator
 *
 */
@Entity
@Table(name = "\"Cmon_Country\"", schema = "MARD")
// Define named queries here
@NamedQueries({
    @NamedQuery(name = "CmonCountry.countAll", query = "SELECT COUNT(x) FROM CmonCountry x")
})
public class CmonCountry implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @Column(name = "\"CountryID\"")
    private Long countryid;

    @Column(name = "\"CountryCode\"", length = 2)
    private String countrycode;

    @Column(name = "\"CountryName\"")
    private String countryname;

   
    public CmonCountry() {
        super();
    }

    public CmonCountry(String countrycode, String countryname) {
        this.countrycode = countrycode;
        this.countryname = countryname;
    }

    public void setCountryid(Long countryid) {
        this.countryid = countryid;
    }

    public Long getCountryid() {
        return this.countryid;
    }

    //--- DATABASE MAPPING : CountryCode ( VARCHAR2 ) 
    public void setCountrycode(String countrycode) {
        this.countrycode = countrycode;
    }

    public String getCountrycode() {
        return this.countrycode;
    }

    //--- DATABASE MAPPING : CountryName ( NVARCHAR2 ) 
    public void setCountryname(String countryname) {
        this.countryname = countryname;
    }

    public String getCountryname() {
        return this.countryname;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("[");
        sb.append("]:");
        sb.append(countryid);
        sb.append("|");
        sb.append(countrycode);
        sb.append("|");
        sb.append(countryname);
        return sb.toString();
    }

}
