/*
 * Created on 13 Oct 2018 ( Time 11:48:14 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.vnsw.ws.p12.entity.db;

import com.vnsw.ws.annotations.DateSerialization;
import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

@XmlAccessorType(XmlAccessType.FIELD)
public class TbdhsHanghoa12 implements Serializable {

    @XmlTransient
    private static final long serialVersionUID = 1L;

    @XmlTransient
    private Long fiIdHh       ;

    @XmlTransient
    private Long fiIdHoso     ;

    @XmlTransient
    private String     fiMaHoso     ;

    @XmlElement(name = "NSWAniFeedFileCode")
    private String     fiMahosoXncl ;

    @XmlElement(name = "NameOfGoods")
    private String     fiTenHh      ;

    @XmlElement(name = "RegistrationNumber")
    private String     fiMsChungnhan ;

    @XmlElement(name = "QualityLevel", nillable = true)
    private String     fiMucChatluong ;

    @XmlElement(name = "Manufacture")
    private String     fiHangSx     ;

    @XmlElement(name = "ManufactureState")
    private String     fiNuocSx     ;

    @XmlElement(name = "AniFeedConfirmNo")
    private String     fiSodkXncl   ;

    @XmlElement(name = "AniFeedResultNo")
    private String     fiSogiayXncl ;

    @XmlElement(name = "ImportDate")
    @XmlJavaTypeAdapter(DateSerialization.class)
    private Date       fiNgaycapXncl ;

    @XmlTransient
    private Long fiHoatdong   ;

    @XmlTransient
    private String     fiNguoitao   ;

    @XmlTransient
    private Date       fiNgaytao    ;

    @XmlTransient
    private Date       fiNgCapnhat  ;

    @XmlTransient
    private String aniFeedFileCodes;
    
    @XmlTransient
    private String aniFeedConfirmNos;
    
    @XmlTransient
    private String aniFeedResultNos;
    
    @XmlTransient
    private String aniFeedSignResultDates;
    
    @XmlTransient
    private String aniFeedDepartmentCodes;
    
    @XmlTransient
    private Long goodInspectionTypes;
    
    @XmlTransient
    private String group;

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TbdhsHanghoa12() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setFiIdHh( Long fiIdHh ) {
        this.fiIdHh = fiIdHh ;
    }
    public Long getFiIdHh() {
        return this.fiIdHh;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : FI_ID_HOSO ( NUMBER ) 
    public void setFiIdHoso( Long fiIdHoso ) {
        this.fiIdHoso = fiIdHoso;
    }
    public Long getFiIdHoso() {
        return this.fiIdHoso;
    }

    //--- DATABASE MAPPING : FI_MA_HOSO ( VARCHAR2 ) 
    public void setFiMaHoso( String fiMaHoso ) {
        this.fiMaHoso = fiMaHoso;
    }
    public String getFiMaHoso() {
        return this.fiMaHoso;
    }

    //--- DATABASE MAPPING : FI_MAHOSO_XNCL ( VARCHAR2 ) 
    public void setFiMahosoXncl( String fiMahosoXncl ) {
        this.fiMahosoXncl = fiMahosoXncl;
    }
    public String getFiMahosoXncl() {
        return this.fiMahosoXncl;
    }

    //--- DATABASE MAPPING : FI_TEN_HH ( VARCHAR2 ) 
    public void setFiTenHh( String fiTenHh ) {
        this.fiTenHh = fiTenHh;
    }
    public String getFiTenHh() {
        return this.fiTenHh;
    }

    //--- DATABASE MAPPING : FI_MS_CHUNGNHAN ( VARCHAR2 ) 
    public void setFiMsChungnhan( String fiMsChungnhan ) {
        this.fiMsChungnhan = fiMsChungnhan;
    }
    public String getFiMsChungnhan() {
        return this.fiMsChungnhan;
    }

    //--- DATABASE MAPPING : FI_MUC_CHATLUONG ( VARCHAR2 ) 
    public void setFiMucChatluong( String fiMucChatluong ) {
        this.fiMucChatluong = fiMucChatluong;
    }
    public String getFiMucChatluong() {
        return this.fiMucChatluong;
    }

    //--- DATABASE MAPPING : FI_HANG_SX ( VARCHAR2 ) 
    public void setFiHangSx( String fiHangSx ) {
        this.fiHangSx = fiHangSx;
    }
    public String getFiHangSx() {
        return this.fiHangSx;
    }

    //--- DATABASE MAPPING : FI_NUOC_SX ( VARCHAR2 ) 
    public void setFiNuocSx( String fiNuocSx ) {
        this.fiNuocSx = fiNuocSx;
    }
    public String getFiNuocSx() {
        return this.fiNuocSx;
    }

    //--- DATABASE MAPPING : FI_SODK_XNCL ( VARCHAR2 ) 
    public void setFiSodkXncl( String fiSodkXncl ) {
        this.fiSodkXncl = fiSodkXncl;
    }
    public String getFiSodkXncl() {
        return this.fiSodkXncl;
    }

    //--- DATABASE MAPPING : FI_SOGIAY_XNCL ( VARCHAR2 ) 
    public void setFiSogiayXncl( String fiSogiayXncl ) {
        this.fiSogiayXncl = fiSogiayXncl;
    }
    public String getFiSogiayXncl() {
        return this.fiSogiayXncl;
    }

    //--- DATABASE MAPPING : FI_NGAYCAP_XNCL ( TIMESTAMP(6) ) 
    public void setFiNgaycapXncl( Date fiNgaycapXncl ) {
        this.fiNgaycapXncl = fiNgaycapXncl;
    }
    public Date getFiNgaycapXncl() {
        return this.fiNgaycapXncl;
    }

    //--- DATABASE MAPPING : FI_HOATDONG ( NUMBER ) 
    public void setFiHoatdong( Long fiHoatdong ) {
        this.fiHoatdong = fiHoatdong;
    }
    public Long getFiHoatdong() {
        return this.fiHoatdong;
    }

    //--- DATABASE MAPPING : FI_NGUOITAO ( VARCHAR2 ) 
    public void setFiNguoitao( String fiNguoitao ) {
        this.fiNguoitao = fiNguoitao;
    }
    public String getFiNguoitao() {
        return this.fiNguoitao;
    }

    //--- DATABASE MAPPING : FI_NGAYTAO ( TIMESTAMP(6) ) 
    public void setFiNgaytao( Date fiNgaytao ) {
        this.fiNgaytao = fiNgaytao;
    }
    public Date getFiNgaytao() {
        return this.fiNgaytao;
    }

    //--- DATABASE MAPPING : FI_NG_CAPNHAT ( TIMESTAMP(6) ) 
    public void setFiNgCapnhat( Date fiNgCapnhat ) {
        this.fiNgCapnhat = fiNgCapnhat;
    }
    public Date getFiNgCapnhat() {
        return this.fiNgCapnhat;
    }

    public String getAniFeedFileCodes() {
        return aniFeedFileCodes;
    }

    public void setAniFeedFileCodes(String aniFeedFileCodes) {
        this.aniFeedFileCodes = aniFeedFileCodes;
    }

    public String getAniFeedConfirmNos() {
        return aniFeedConfirmNos;
    }

    public void setAniFeedConfirmNos(String aniFeedConfirmNos) {
        this.aniFeedConfirmNos = aniFeedConfirmNos;
    }

    public String getAniFeedResultNos() {
        return aniFeedResultNos;
    }

    public void setAniFeedResultNos(String aniFeedResultNos) {
        this.aniFeedResultNos = aniFeedResultNos;
    }

    public String getAniFeedSignResultDates() {
        return aniFeedSignResultDates;
    }

    public void setAniFeedSignResultDates(String aniFeedSignResultDates) {
        this.aniFeedSignResultDates = aniFeedSignResultDates;
    }

    public String getAniFeedDepartmentCodes() {
        return aniFeedDepartmentCodes;
    }

    public void setAniFeedDepartmentCodes(String aniFeedDepartmentCodes) {
        this.aniFeedDepartmentCodes = aniFeedDepartmentCodes;
    }

    public Long getGoodInspectionTypes() {
        return goodInspectionTypes;
    }

    public void setGoodInspectionTypes(Long goodInspectionTypes) {
        this.goodInspectionTypes = goodInspectionTypes;
    }

    public String getGroup() {
        return group;
    }

    public void setGroup(String group) {
        this.group = group;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(fiIdHh);
        sb.append("]:"); 
        sb.append(fiIdHoso);
        sb.append("|");
        sb.append(fiMaHoso);
        sb.append("|");
        sb.append(fiMahosoXncl);
        sb.append("|");
        sb.append(fiTenHh);
        sb.append("|");
        sb.append(fiMsChungnhan);
        sb.append("|");
        sb.append(fiMucChatluong);
        sb.append("|");
        sb.append(fiHangSx);
        sb.append("|");
        sb.append(fiNuocSx);
        sb.append("|");
        sb.append(fiSodkXncl);
        sb.append("|");
        sb.append(fiSogiayXncl);
        sb.append("|");
        sb.append(fiNgaycapXncl);
        sb.append("|");
        sb.append(fiHoatdong);
        sb.append("|");
        sb.append(fiNguoitao);
        sb.append("|");
        sb.append(fiNgaytao);
        sb.append("|");
        sb.append(fiNgCapnhat);
        return sb.toString(); 
    } 

}
