/*
 * Created on 25 Jul 2017 ( Time 08:16:22 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.nsw.backend.dic.service;

import com.nsw.backend.dic.model.CmonGood;
import java.util.List;

/**
 * Business Service Interface for entity CmonGood.
 */
public interface CmonGoodService {

    /**
     * Loads an entity from the database using its Primary Key
     *
     * @param id
     * @return entity
     */
    CmonGood findById(Long id);

    /**
     * Loads all entities.
     *
     * @return all entities
     */
    List<CmonGood> findAll();

    /**
     * Saves the given entity in the database (create or update)
     *
     * @param entity
     * @return entity
     */
    CmonGood save(CmonGood entity);

    /**
     * Updates the given entity in the database
     *
     * @param entity
     * @return
     */
    CmonGood update(CmonGood entity);

    /**
     * Creates the given entity in the database
     *
     * @param entity
     * @return
     */
    CmonGood create(CmonGood entity);

    /**
     * Deletes an entity using its Primary Key
     * @param id
     */
    void delete(Long id);

}
