/*
 * Created on 25 Jul 2017 ( Time 08:16:33 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.nsw.backend.dic.service;

import com.nsw.backend.dic.model.CmonPaymenttype;
import java.util.List;

/**
 * Business Service Interface for entity CmonPaymenttype.
 */
public interface CmonPaymenttypeService {

    /**
     * Loads an entity from the database using its Primary Key
     *
     * @param id
     * @return entity
     */
    CmonPaymenttype findById(Long id);

    /**
     * Loads all entities.
     *
     * @return all entities
     */
    List<CmonPaymenttype> findAll();

    /**
     * Saves the given entity in the database (create or update)
     *
     * @param entity
     * @return entity
     */
    CmonPaymenttype save(CmonPaymenttype entity);

    /**
     * Updates the given entity in the database
     *
     * @param entity
     * @return
     */
    CmonPaymenttype update(CmonPaymenttype entity);

    /**
     * Creates the given entity in the database
     *
     * @param entity
     * @return
     */
    CmonPaymenttype create(CmonPaymenttype entity);

    /**
     * Deletes an entity using its Primary Key
     * @param id
     */
    void delete(Long id);

}
