/*
 * Created on 25 Jul 2017 ( Time 08:16:46 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.nsw.backend.dic.service;

import com.nsw.backend.dic.model.CmonProvince;
import java.util.List;

/**
 * Business Service Interface for entity CmonProvince.
 */
public interface CmonProvinceService {

    /**
     * Loads an entity from the database using its Primary Key
     *
     * @param id
     * @return entity
     */
    CmonProvince findById(Long id);

    /**
     * Loads all entities.
     *
     * @return all entities
     */
    List<CmonProvince> findAll();

    /**
     * Saves the given entity in the database (create or update)
     *
     * @param entity
     * @return entity
     */
    CmonProvince save(CmonProvince entity);

    /**
     * Updates the given entity in the database
     *
     * @param entity
     * @return
     */
    CmonProvince update(CmonProvince entity);

    /**
     * Creates the given entity in the database
     *
     * @param entity
     * @return
     */
    CmonProvince create(CmonProvince entity);

    /**
     * Deletes an entity using its Primary Key
     * @param id
     */
    void delete(Long id);

}
