/*
 * Created on 13 Sep 2017 ( Time 10:42:56 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 
package com.nsw.most.p04.model;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class Tbdgiayphep4 implements Serializable {

    private Long fiIdGp;

    private Long fiIdHoso;

    private String fiMaHoso;

    private String fiSoGp;

    private String fiTenTep;

    private String fiTenDn;

    private String fiDiachiDn;

    private String fiDtDn;

    private String fiFaxDn;

    private Date fiNgayHhan;

    private Date fiNgayCap;

    private String fiNguoiKy;

    private Long fiHoatdong;

    private String fiNguoitao;

    private Date fiNgaytao;

    private Long fiTrangthai;

    private List<Tbdhanghoa4> hangHoas;

    private Tbddinhkem4 dinhkem;

    public Tbdgiayphep4() {
        super();
    }

    public void setFiIdGp(Long fiIdGp) {
        this.fiIdGp = fiIdGp;
    }

    public Long getFiIdGp() {
        return this.fiIdGp;
    }

    public void setFiIdHoso(Long fiIdHoso) {
        this.fiIdHoso = fiIdHoso;
    }

    public Long getFiIdHoso() {
        return this.fiIdHoso;
    }

    public void setFiMaHoso(String fiMaHoso) {
        this.fiMaHoso = fiMaHoso;
    }

    public String getFiMaHoso() {
        return this.fiMaHoso;
    }

    public void setFiSoGp(String fiSoGp) {
        this.fiSoGp = fiSoGp;
    }

    public String getFiSoGp() {
        return this.fiSoGp;
    }

    public void setFiTenTep(String fiTenTep) {
        this.fiTenTep = fiTenTep;
    }

    public String getFiTenTep() {
        return this.fiTenTep;
    }

    public void setFiTenDn(String fiTenDn) {
        this.fiTenDn = fiTenDn;
    }

    public String getFiTenDn() {
        return this.fiTenDn;
    }

    //--- DATABASE MAPPING : FI_DIACHI_DN ( VARCHAR2 ) 
    public void setFiDiachiDn(String fiDiachiDn) {
        this.fiDiachiDn = fiDiachiDn;
    }

    public String getFiDiachiDn() {
        return this.fiDiachiDn;
    }

    //--- DATABASE MAPPING : FI_DT_DN ( VARCHAR2 ) 
    public void setFiDtDn(String fiDtDn) {
        this.fiDtDn = fiDtDn;
    }

    public String getFiDtDn() {
        return this.fiDtDn;
    }

    //--- DATABASE MAPPING : FI_FAX_DN ( VARCHAR2 ) 
    public void setFiFaxDn(String fiFaxDn) {
        this.fiFaxDn = fiFaxDn;
    }

    public String getFiFaxDn() {
        return this.fiFaxDn;
    }

    //--- DATABASE MAPPING : FI_NGAY_HHAN ( TIMESTAMP(6) ) 
    public void setFiNgayHhan(Date fiNgayHhan) {
        this.fiNgayHhan = fiNgayHhan;
    }

    public Date getFiNgayHhan() {
        return this.fiNgayHhan;
    }

    //--- DATABASE MAPPING : FI_NGAY_CAP ( TIMESTAMP(6) ) 
    public void setFiNgayCap(Date fiNgayCap) {
        this.fiNgayCap = fiNgayCap;
    }

    public Date getFiNgayCap() {
        return this.fiNgayCap;
    }

    //--- DATABASE MAPPING : FI_NGUOI_KY ( VARCHAR2 ) 
    public void setFiNguoiKy(String fiNguoiKy) {
        this.fiNguoiKy = fiNguoiKy;
    }

    public String getFiNguoiKy() {
        return this.fiNguoiKy;
    }

    //--- DATABASE MAPPING : FI_HOATDONG ( NUMBER ) 
    public void setFiHoatdong(Long fiHoatdong) {
        this.fiHoatdong = fiHoatdong;
    }

    public Long getFiHoatdong() {
        return this.fiHoatdong;
    }

    //--- DATABASE MAPPING : FI_NGUOITAO ( VARCHAR2 ) 
    public void setFiNguoitao(String fiNguoitao) {
        this.fiNguoitao = fiNguoitao;
    }

    public String getFiNguoitao() {
        return this.fiNguoitao;
    }

    //--- DATABASE MAPPING : FI_NGAYTAO ( TIMESTAMP(6) ) 
    public void setFiNgaytao(Date fiNgaytao) {
        this.fiNgaytao = fiNgaytao;
    }

    public Date getFiNgaytao() {
        return this.fiNgaytao;
    }

    public Long getFiTrangthai() {
        return fiTrangthai;
    }

    public void setFiTrangthai(Long fiTrangthai) {
        this.fiTrangthai = fiTrangthai;
    }

    public List<Tbdhanghoa4> getHangHoas() {
        return hangHoas;
    }

    public void setHangHoas(List<Tbdhanghoa4> hangHoas) {
        this.hangHoas = hangHoas;
    }

    public Tbddinhkem4 getDinhkem() {
        return dinhkem;
    }

    public void setDinhkem(Tbddinhkem4 dinhkem) {
        this.dinhkem = dinhkem;
    }

    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("[");
        sb.append(fiIdGp);
        sb.append("]:");
        sb.append(fiIdHoso);
        sb.append("|");
        sb.append(fiMaHoso);
        sb.append("|");
        sb.append(fiSoGp);
        sb.append("|");
        sb.append(fiTenTep);
        sb.append("|");
        sb.append(fiTenDn);
        sb.append("|");
        sb.append(fiDiachiDn);
        sb.append("|");
        sb.append(fiDtDn);
        sb.append("|");
        sb.append(fiFaxDn);
        sb.append("|");
        sb.append(fiNgayHhan);
        sb.append("|");
        sb.append(fiNgayCap);
        sb.append("|");
        sb.append(fiNguoiKy);
        sb.append("|");
        sb.append(fiHoatdong);
        sb.append("|");
        sb.append(fiNguoitao);
        sb.append("|");
        sb.append(fiNgaytao);
        return sb.toString();
    }
}
