spring:
  profiles:
    active: hq_test
---
server:
  port: 8081
  contextPath: /MARDBackend
---
spring:
  profiles: local, default, dev
  cache:
    ehcache:
      config: classpath:ehcache.xml
  data:
      elasticsearch:
            cluster-name: NSWSearch
            cluster-nodes: 127.0.0.1:9300
  http:
      multipart:
       max-file-size: 10MB
       max-request-size: 10MB
  jmx:
    default-domain: MARDBackend
datasource:
  MARDBackend:
    url: jdbc:oracle:thin:@localhost:1521/orcl
    username: MARD
    password: MARD
    driverClassName: oracle.jdbc.OracleDriver
    defaultSchema: MARD
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: false
      format_sql: false
      dialect: org.hibernate.dialect.Oracle10gDialect
management:
    security:
        enabled: false
PATH_TEMPLATE: C:/mard/template/
EXPORT_FOLDER: C:/mard/export/
PATH_UPLOAD: C:/temp/
URL_DOWNLOAD: http://localhost:8001/FileServices/file/download
URL_FILE_SERVICE: http://localhost:8001/FileServices
FOLDER_TEMP_FILE_SERVICE: C:/upload/
TIMEOUT: 900
ACTIVE_PROFILE: dev
# URL common backend de lay danh muc Quoc gia
COMMON_BACKEND_DIC_STATE: http://10.224.164.18:8007/NSWBackendCommon/dic/state/
# URL common backend de lay danh muc Don vi tinh
COMMON_BACKEND_DIC_UNIT: http://10.224.164.18:8007/NSWBackendCommon/dic/unit/
# URL SERVICE
#SEND_SERVICE_URL: http://10.224.164.236:8002/MOSTWs/send/01/sendAll/
SEND_SERVICE_URL: http://localhost:8002/MARDWs/send/10/sendAll/
SEND_PAY_SERVICE_URL: http://localhost:8002/MARDWs/send/10/sendPayFee/
SEND_SERVICE_11_URL: http://localhost:8002/MARDWs/send/11/sendAll/
SEND_PAY_SERVICE_11_URL: http://localhost:8002/MARDWs/send/11/sendPayFee/
SEND_SERVICE_URL_12: http://localhost:8002/MARDWs/send/12/sendAll/
SEND_SERVICE_URL_14: http://localhost:8002/MARDWs/send/14/sendAll/
SEND_SERVICE_URL_15: http://localhost:8002/MARDWs/send/15/sendAll/
SEND_SERVICE_URL_16: http://localhost:8002/MARDWs/send/16/sendAll/
# URL To khai hai quan
URI_ADDRESS_TOKHAI_SERVER: http://103.248.160.16/eMoitService/ServiceTCTKHQ.svc?wsdl
# Service kiem tra chu ky so cua doanh nghiep
CASERVICE_LINK: http://10.224.164.236/CAService/CAService.svc?wsdl
CASERVICE_NAMESPACE_NAME: tem
CASERVICE_NAMESPACE_LINK: http://tempuri.org/
CASERVICE_METHOD: Verify
CASERVICE_PARAMS: user,signature
# Thong tin rabbitMQ
activemq.host: 10.224.164.16
activemq.port: 5672
activemq.user: nswlog
activemq.password: nswlog
activemq.virtualHost: /
activemq.exchangeName: logExchange
activemq.queueName: Log_Error_Queue
activemq.routingKey: error
---
spring:
  profiles: vt_test
  cache:
    ehcache: 
      config: classpath:ehcache.xml
  data:
      elasticsearch:
            cluster-name: NSWSearch
            cluster-nodes: 10.224.164.16:9300
  http:
      multipart:
       max-file-size: 10MB
       max-request-size: 10MB
  jmx:
    default-domain: MARDBackend
datasource:
  MARDBackend:
    url: jdbc:oracle:thin:@10.224.164.16:1521/orcl
    username: NSW
    password: NSW
    driverClassName: oracle.jdbc.OracleDriver
    defaultSchema: MARD
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: none
      show_sql: false
      format_sql: false
      dialect: org.hibernate.dialect.Oracle10gDialect
management:
    security:
        enabled: false
PATH_TEMPLATE: /home/TEMP/TEMPLATE/
EXPORT_FOLDER: /home/TEMP/EXPORT/
PATH_UPLOAD: /home/TEMP/UPLOAD/
URL_DOWNLOAD: http://10.224.164.18:8001/FileServices/file/download
URL_FILE_SERVICE: http://10.224.164.18:8001/FileServices
FOLDER_TEMP_FILE_SERVICE: /home/TEMP/UPLOAD/
TIMEOUT: 900
ACTIVE_PROFILE: vt_test
# URL common backend de lay danh muc Quoc gia
COMMON_BACKEND_DIC_STATE: http://10.224.164.18:8007/NSWBackendCommon/dic/state/
# URL common backend de lay danh muc Don vi tinh
COMMON_BACKEND_DIC_UNIT: http://10.224.164.18:8007/NSWBackendCommon/dic/unit/
# URL SERVICE
SEND_SERVICE_URL: http://10.224.164.18:8002/MARDWs/send/01/sendAll/
SEND_PAY_SERVICE_URL:  http://10.224.164.18:8002/MARDWs/send/10/sendPayFee/
SEND_SERVICE_11_URL: http://10.224.164.18:8002/MARDWs/send/11/sendAll/
SEND_PAY_SERVICE_11_URL: http://10.224.164.18:8002/MARDWs/send/11/sendPayFee/
SEND_SERVICE_URL_12: http://10.224.164.18:8002/MARDWs/send/12/sendAll/
SEND_SERVICE_URL_14: http://10.224.164.18:8002/MARDWs/send/14/sendAll/
SEND_SERVICE_URL_15: http://10.224.164.18:8002/MARDWs/send/15/sendAll/
SEND_SERVICE_URL_16: http://10.224.164.18:8002/MARDWs/send/16/sendAll/
# URL To khai hai quan
URI_ADDRESS_TOKHAI_SERVER: http://103.248.160.16/eMoitService/ServiceTCTKHQ.svc?wsdl
# Service kiem tra chu ky so cua doanh nghiep
CASERVICE_LINK: http://10.224.164.236/CAService/CAService.svc?wsdl
CASERVICE_NAMESPACE_NAME: tem
CASERVICE_NAMESPACE_LINK: http://tempuri.org/
CASERVICE_METHOD: Verify
CASERVICE_PARAMS: user,signature
# Thong tin rabbitMQ
activemq.host: 10.224.164.16
activemq.port: 5672
activemq.user: nswlog
activemq.password: nswlog
activemq.virtualHost: /
activemq.exchangeName: logExchange
activemq.queueName: Log_Error_Queue
activemq.routingKey: error
---
spring:
  profiles: hq_test
  cache:
    ehcache: 
      config: classpath:ehcache.xml
  data:
      elasticsearch:
            cluster-name: NSWSearch
            cluster-nodes: 127.0.0.1:9300
  http:
      multipart:
       max-file-size: 10MB
       max-request-size: 10MB
  jmx:
    default-domain: MARDBackend
datasource:
  MARDBackend:
#    url: jdbc:oracle:thin:@118.70.125.195:1525:ORCLCDB
    url: jdbc:oracle:thin:@10.224.130.194:1521:nswstandby
    username: NSW
    password: 123456789
    driverClassName: oracle.jdbc.OracleDriver
    defaultSchema: MARD
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: false
      format_sql: false
      dialect: org.hibernate.dialect.Oracle12cDialect
management:
    security:
        enabled: false
PATH_TEMPLATE: /home/TEMP/TEMPLATE/
EXPORT_FOLDER: /home/TEMP/EXPORT/
PATH_UPLOAD: /home/TEMP/UPLOAD/
URL_DOWNLOAD: http://10.224.128.132:8005/FileServices/file/download
URL_FILE_SERVICE: http://10.224.128.132:8005/FileServices
FOLDER_TEMP_FILE_SERVICE: /home/TEMP/UPLOAD/
TIMEOUT: 900
ACTIVE_PROFILE: hq_test
# URL common backend de lay danh muc Quoc gia
COMMON_BACKEND_DIC_STATE: http://10.224.128.132:8001/NSWBackendCommon/dic/state/
# URL common backend de lay danh muc Don vi tinh
COMMON_BACKEND_DIC_UNIT: http://10.224.128.132:8001/NSWBackendCommon/dic/unit/
# URL SERVICE
SEND_WS_ROOT_URL: http://localhost:8082/MARDWs/
SEND_SERVICE_URL: http://10.224.128.132:8004/MARDWs/send/10/sendAll/
SEND_PAY_SERVICE_URL:  http://10.224.128.132:8004/MARDWs/send/10/sendPayFee/
SEND_SERVICE_11_URL: http://10.224.128.132:8004/MARDWs/send/11/sendAll/
SEND_PAY_SERVICE_11_URL: http://10.224.128.132:8004/MARDWs/send/11/sendPayFee/
SEND_SERVICE_URL_12: http://10.224.128.132:8004/MARDWs/send/12/sendAll/
SEND_SERVICE_URL_14: http://10.224.128.132:8004/MARDWs/send/14/sendAll/
SEND_SERVICE_URL_15: http://10.224.128.132:8004/MARDWs/send/15/sendAll/
SEND_SERVICE_URL_16: http://10.224.128.132:8004/MARDWs/send/16/sendAll/
SEND_SERVICE_URL_04: http://10.224.128.132:8004/MARDWs/send/04/sendAll/
SEND_SERVICE_URL_17: http://10.224.128.132:8004/MARDWs/send/17/sendAll/
SEND_SERVICE_URL_18: http://10.224.128.132:8004/MARDWs/send/18/sendAll/
FILE_SERVICES_URL: http://27.72.96.51:8585/FileUpload/FileAttachments/
# URL To khai hai quan
URI_ADDRESS_TOKHAI_SERVER: http://10.224.138.56:8887/eMoitService/ServiceTCTKHQ.svc?wsdl
# Service kiem tra chu ky so cua doanh nghiep
CASERVICE_LINK: http://10.224.164.236/CAService/CAService.svc?wsdl
CASERVICE_NAMESPACE_NAME: tem
CASERVICE_NAMESPACE_LINK: http://tempuri.org/
CASERVICE_METHOD: Verify
CASERVICE_PARAMS: user,signature
# Thong tin rabbitMQ
activemq.host: 10.224.128.148
activemq.port: 5672
activemq.user: nswlog
activemq.password: nswlog
activemq.virtualHost: /
activemq.exchangeName: logExchange
activemq.queueName: Log_Error_Queue
activemq.routingKey: error
---
spring:
  profiles: hq_live
  cache:
    ehcache: 
      config: classpath:ehcache.xml
  data:
      elasticsearch:
            cluster-name: NSWSearch
            cluster-nodes: 127.0.0.1:9300
  http:
      multipart:
       max-file-size: 10MB
       max-request-size: 10MB
  jmx:
    default-domain: MARDBackend
datasource:
  MARDBackend:
    url: jdbc:oracle:thin:@10.224.130.231:1521/nswdb
    username: NSW
    password: 123456789
    driverClassName: oracle.jdbc.OracleDriver
    defaultSchema: MARD
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: false
      format_sql: false
      dialect: org.hibernate.dialect.Oracle10gDialect
management:
    security:
        enabled: false
PATH_TEMPLATE: /home/TEMP/TEMPLATE/
EXPORT_FOLDER: /home/TEMP/EXPORT/
PATH_UPLOAD: /home/TEMP/UPLOAD/
URL_DOWNLOAD: http://10.224.144.58:8001/FileServices/file/download
URL_FILE_SERVICE: http://10.224.144.58:8001/FileServices
FOLDER_TEMP_FILE_SERVICE: /home/TEMP/UPLOAD/
TIMEOUT: 900
ACTIVE_PROFILE: hq_live
# URL common backend de lay danh muc Quoc gia
COMMON_BACKEND_DIC_STATE: http://10.224.128.193:8001/NSWBackendCommon/dic/state/
# URL common backend de lay danh muc Don vi tinh
COMMON_BACKEND_DIC_UNIT: http://10.224.128.193:8001/NSWBackendCommon/dic/unit/
# URL SERVICE
SEND_SERVICE_URL: http://10.224.128.194:8003/MARDWs/send/10/sendAll/
SEND_PAY_SERVICE_URL:  http://10.224.128.194:8003/MARDWs/send/10/sendPayFee/
SEND_SERVICE_11_URL: http://10.224.128.194:8003/MARDWs/send/11/sendAll/
SEND_PAY_SERVICE_11_URL: http://10.224.128.194:8003/MARDWs/send/11/sendPayFee/
SEND_SERVICE_URL_12: http://10.224.128.194:8003/MARDWs/send/12/sendAll/
SEND_SERVICE_URL_14: http://10.224.128.194:8003/MARDWs/send/14/sendAll/
SEND_SERVICE_URL_15: http://10.224.128.194:8003/MARDWs/send/15/sendAll/
SEND_SERVICE_URL_16: http://10.224.128.194:8003/MARDWs/send/16/sendAll/
# URL To khai hai quan
URI_ADDRESS_TOKHAI_SERVER: http://10.224.128.161:8080/eMoitService/ServiceTCTKHQ.svc?wsdl
# Service kiem tra chu ky so cua doanh nghiep
CASERVICE_LINK: http://10.224.164.236/CAService/CAService.svc?wsdl
CASERVICE_NAMESPACE_NAME: tem
CASERVICE_NAMESPACE_LINK: http://tempuri.org/
CASERVICE_METHOD: Verify
CASERVICE_PARAMS: user,signature
# Thong tin rabbitMQ
activemq.host: 10.224.138.93
activemq.port: 5672
activemq.user: nswlog
activemq.password: nswlog
activemq.virtualHost: /
activemq.exchangeName: logExchange
activemq.queueName: Log_Error_Queue
activemq.routingKey: error