/*
 * Created on 11 Mar 2019 ( Time 12:48:11 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 
package com.nsw.moh.p01.model;

import java.io.Serializable;
import java.util.Date;

public class TbsmdnkTlieu1 implements Serializable {

    private static final long serialVersionUID = 1L;
    private Long fiId;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    //@Column(name="FI_ID_MDNK")
    private Long fiIdMdnk;

    //@Column(name="FI_MA_MDNK", length=20)
    private String fiMaMdnk;

    //@Column(name="FI_ID_TAILIEU")
    private Long fiIdTailieu;

    //@Column(name="FI_MA_TAILIEU", length=50)
    private String fiMaTailieu;

    //@Column(name="FI_HOATDONG")
    private Long fiHoatdong;

    //@Column(name="FI_NGUOITAO", length=50)
    private String fiNguoitao;

    //@Temporal(TemporalType.TIMESTAMP)
    //@Column(name="FI_NGAYTAO")
    private Date fiNgaytao;

    //@Temporal(TemporalType.TIMESTAMP)
    //@Column(name="FI_NG_CAPNHAT")
    private Date fiNgCapnhat;

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TbsmdnkTlieu1() {
        super();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setFiId(Long fiId) {
        this.fiId = fiId;
    }

    public Long getFiId() {
        return this.fiId;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : FI_ID_MDNK ( NUMBER ) 
    public void setFiIdMdnk(Long fiIdMdnk) {
        this.fiIdMdnk = fiIdMdnk;
    }

    public Long getFiIdMdnk() {
        return this.fiIdMdnk;
    }

    //--- DATABASE MAPPING : FI_MA_MDNK ( VARCHAR2 ) 
    public void setFiMaMdnk(String fiMaMdnk) {
        this.fiMaMdnk = fiMaMdnk;
    }

    public String getFiMaMdnk() {
        return this.fiMaMdnk;
    }

    //--- DATABASE MAPPING : FI_ID_TAILIEU ( NUMBER ) 
    public void setFiIdTailieu(Long fiIdTailieu) {
        this.fiIdTailieu = fiIdTailieu;
    }

    public Long getFiIdTailieu() {
        return this.fiIdTailieu;
    }

    //--- DATABASE MAPPING : FI_MA_TAILIEU ( VARCHAR2 ) 
    public void setFiMaTailieu(String fiMaTailieu) {
        this.fiMaTailieu = fiMaTailieu;
    }

    public String getFiMaTailieu() {
        return this.fiMaTailieu;
    }

    //--- DATABASE MAPPING : FI_HOATDONG ( NUMBER ) 
    public void setFiHoatdong(Long fiHoatdong) {
        this.fiHoatdong = fiHoatdong;
    }

    public Long getFiHoatdong() {
        return this.fiHoatdong;
    }

    //--- DATABASE MAPPING : FI_NGUOITAO ( VARCHAR2 ) 
    public void setFiNguoitao(String fiNguoitao) {
        this.fiNguoitao = fiNguoitao;
    }

    public String getFiNguoitao() {
        return this.fiNguoitao;
    }

    //--- DATABASE MAPPING : FI_NGAYTAO ( TIMESTAMP(6) ) 
    public void setFiNgaytao(Date fiNgaytao) {
        this.fiNgaytao = fiNgaytao;
    }

    public Date getFiNgaytao() {
        return this.fiNgaytao;
    }

    //--- DATABASE MAPPING : FI_NG_CAPNHAT ( TIMESTAMP(6) ) 
    public void setFiNgCapnhat(Date fiNgCapnhat) {
        this.fiNgCapnhat = fiNgCapnhat;
    }

    public Date getFiNgCapnhat() {
        return this.fiNgCapnhat;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("[");
        sb.append(fiId);
        sb.append("]:");
        sb.append(fiIdMdnk);
        sb.append("|");
        sb.append(fiMaMdnk);
        sb.append("|");
        sb.append(fiIdTailieu);
        sb.append("|");
        sb.append(fiMaTailieu);
        sb.append("|");
        sb.append(fiHoatdong);
        sb.append("|");
        sb.append(fiNguoitao);
        sb.append("|");
        sb.append(fiNgaytao);
        sb.append("|");
        sb.append(fiNgCapnhat);
        return sb.toString();
    }

}
