/*
 * Created on 18 Jul 2017 ( Time 08:39:33 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 
package com.nsw.backend.mard.p08.model;

import lombok.Data;

import javax.persistence.*;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * Persistent class for entity stored in table "TBDDVXL08" - Đơn vị xử lý
 *
 * @author Telosys Tools Generator
 */
@Entity
@Data
@Table(name = "TBDDVXL08", schema = "MARD")
public class Tbddvxl08 implements Serializable {
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name = "FI_ID_PU", nullable = false)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "TBDDVXL08_SEQ")
    @SequenceGenerator(sequenceName = "TBDDVXL08_SEQ", schema = "MARD", initialValue = 10000, allocationSize = 1, name = "TBDDVXL08_SEQ")
    private Long fiIdPU;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name = "FI_PU_CODE")
    private String fiPUCode;

    @Column(name = "FI_PU_DESC")
    private String fiPUDesc;

    @Column(name = "FI_PU_LEVEL")
    private Integer fiPULevel;

    @Column(name = "FI_PARENT_PU")
    private Long fiPUParentID;

    @OneToMany(fetch = FetchType.EAGER, cascade = CascadeType.ALL, orphanRemoval = true)
    @JoinColumn(name = "FI_PARENT_PU")
    private List<Tbddvxl08> lstChildPU;

    public Tbddvxl08() {
        lstChildPU = new ArrayList<>();
    }

    public Tbddvxl08(String fiPUCode, String fiPUDesc, int fiPULevel) {
        this();
        this.fiPUCode = fiPUCode;
        this.fiPUDesc = fiPUDesc;
        this.fiPULevel = fiPULevel;
    }
}
