/*
 * Created on 18 Jul 2017 ( Time 08:39:33 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 
package com.nsw.backend.mard.p08.model;

import lombok.Data;

import javax.persistence.*;
import java.io.Serializable;

/**
 * Persistent class for entity stored in table "TBDHANGHOA08"
 *
 * @author Telosys Tools Generator
 */
@Entity
@Data
@Table(name = "TBDHANGHOA08", schema = "MARD")
public class Tbdhanghoa08 implements Serializable {
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name = "FI_ID_PRODUCT", nullable = false)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "TBDCNKDHANGHOA08_SEQ")
    @SequenceGenerator(sequenceName = "TBDCNKDHANGHOA08_SEQ", schema = "MARD", initialValue = 10000, allocationSize = 1, name = "TBDCNKDHANGHOA08_SEQ")
    private Long fiIdProduct;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS
    //----------------------------------------------------------------------
    @Column(name = "FI_HS_ID")
    private Long fiIdHS;

    @Column(name = "FI_SORT")
    private Integer fiSort;

    @Column(name = "FI_PRODUCT_NAME")
    private String fiProductName;

    @Column(name = "FI_PRODUCT_SCIENCE_NAME")
    private String fiProductScienceName;

    @Column(name = "FI_PRODUCT_CODE")
    private String fiProductCode;

    @Column(name = "FI_CIRCULATE_NO")
    private String fiCirculateNo;

    @Column(name = "FI_QTY_MALE")
    private Integer fiQtyMale;

    @Column(name = "FI_QTY_FEMALE")
    private Integer fiQtyFemale;

    @Column(name = "FI_AGE")
    private Integer fiAge = 0;

    @Column(name = "FI_PACKING_TYPE")
    private String fiPackingType; //Unit of measurement

    @Column(name = "FI_NUMBER")
    private float fiNumber = 0;

    @Column(name = "FI_UNIT_CODE")
    private String fiUnitCode; //Unit of measurement

    @Column(name = "FI_NET_WEIGHT")
    private float fiNetWeight = 0;

    @Column(name = "FI_NW_UNIT_CODE")
    private String fiNWUnitCode; //Unit of measurement

    @Column(name = "FI_GROSS_WEIGHT")
    private float fiGrossWeight = 0;

    @Column(name = "FI_GW_UNIT_CODE")
    private String fiGWUnitCode; //Unit of measurement

    @Column(name = "FI_PURPOSE", length = 500)
    private String fiPurpose;

    @Column(name = "FI_COUNTRY_ORIGIN")
    private String fiCountryOrigin;

    @Column(name = "FI_PORT_NAME")
    private String fiPortName;

    public Tbdhanghoa08() {
        super();
    }

}
