/*
 * Created on 31 Mar 2019 ( Time 01:30:29 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.nsw.moh.p10.model;

import java.io.Serializable;

import java.util.Date;
import java.util.List;

public class Tbdhoso10 implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    private Long fiIdHoso     ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    //@Column(name="FI_MA_HOSO", length=50)
    private String     fiMaHoso     ;

    //@Column(name="FI_SO_VB_DN", length=20)
    private String     fiSoVbDn     ;

    //@Column(name="FI_MA_DV_NHAN", length=20)
    private String     fiMaDvNhan   ;

    //@Column(name="FI_TEN_DV_NHAN", length=250)
    private String     fiTenDvNhan  ;

    //@Column(name="FI_MST_DN", length=20)
    private String     fiMstDn      ;

    //@Column(name="FI_TEN_DN", length=250)
    private String     fiTenDn      ;

    //@Column(name="FI_DIACHI_DN", length=250)
    private String     fiDiachiDn   ;

    //@Column(name="FI_TEN_TINH", length=250)
    private String     fiTenTinh    ;

    //@Column(name="FI_MA_TINH", length=10)
    private String     fiMaTinh     ;

    //@Column(name="FI_TEN_QUAN", length=250)
    private String     fiTenQuan    ;

    //@Column(name="FI_MA_QUAN", length=10)
    private String     fiMaQuan     ;

    //@Column(name="FI_LOAIHINH", length=250)
    private String     fiLoaihinh   ;

    //@Column(name="FI_PBAN_QUANLY", length=250)
    private String     fiPbanQuanly ;

    //@Column(name="FI_TEN_DN_EN", length=250)
    private String     fiTenDnEn    ;

    //@Column(name="FI_TEN_VTAT", length=250)
    private String     fiTenVtat    ;

    //@Column(name="FI_SO_DKKD", length=250)
    private String     fiSoDkkd     ;

    //@Column(name="FI_NAM_TLAP")
    private Long fiNamTlap    ;

    //@Column(name="FI_WEB_DN", length=250)
    private String     fiWebDn      ;

    //@Column(name="FI_SDT_DN", length=50)
    private String     fiSdtDn      ;

    //@Column(name="FI_FAX_DN", length=50)
    private String     fiFaxDn      ;

    //@Column(name="FI_EMAIL_DN", length=50)
    private String     fiEmailDn    ;

    //@Column(name="FI_TEN_NDD", length=250)
    private String     fiTenNdd     ;

    //@Column(name="FI_SO_CMND_NDD", length=50)
    private String     fiSoCmndNdd  ;

    //@Temporal(TemporalType.TIMESTAMP)
    //@Column(name="FI_NGAYCAP_CMND")
    private Date       fiNgaycapCmnd ;

    //@Column(name="FI_NOI_CAP_CMND", length=250)
    private String     fiNoiCapCmnd ;

    //@Column(name="FI_SDT_CODINH", length=50)
    private String     fiSdtCodinh  ;

    //@Column(name="FI_SDT_DD", length=50)
    private String     fiSdtDd      ;

    //@Column(name="FI_LOAI_TTB", length=250)
    private String     fiLoaiTtb    ;

    //@Column(name="FI_LOAI_HS_TTB", length=250)
    private String     fiLoaiHsTtb  ;

    //@Column(name="FI_MA_MDICH_NK", length=10)
    private String     fiMaMdichNk  ;

    //@Column(name="FI_TEN_MDICH_NK", length=250)
    private String     fiTenMdichNk ;

    //@Column(name="FI_DONVI_SD", length=250)
    private String     fiDonviSd    ;

    //@Column(name="FI_HOATDONG")
    private Long fiHoatdong   ;

    //@Column(name="FI_NGUOITAO", length=50)
    private String     fiNguoitao   ;

    //@Temporal(TemporalType.TIMESTAMP)
    //@Column(name="FI_NGAYTAO")
    private Date       fiNgaytao    ;

    //@Temporal(TemporalType.TIMESTAMP)
    //@Column(name="FI_NG_CAPNHAT")
    private Date       fiNgCapnhat  ;

    //@Column(name="FI_TRANGTHAI")
    private Long fiTrangthai  ;

    //@Column(name="FI_TEN_TT", length=500)
    private String     fiTenTt      ;

    //@Temporal(TemporalType.TIMESTAMP)
    //@Column(name="FI_NGAYNOP")
    private Date       fiNgaynop    ;

    //@Column(name="FI_SO_CHUNGNHAN", length=255)
    private String     fiSoChungnhan ;

    //@Temporal(TemporalType.TIMESTAMP)
    //@Column(name="FI_NGAYCAP_GCN")
    private Date       fiNgaycapGcn ;

    //@Column(name="FI_MA_THUTUC", length=50)
    private String     fiMaThutuc   ;

    //@Column(name="FI_TEN_THUTUC", length=4000)
    private String     fiTenThutuc  ;

    //@Transient
    TbdhsHanghoa10 hangHoa;
    
    //@Transient
    List<Tbddinhkem10> lstDinhKems;
    
    //@Transient
    List<TbdhsThanhtoan10> lstThanhToans;

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Tbdhoso10() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setFiIdHoso( Long fiIdHoso ) {
        this.fiIdHoso = fiIdHoso ;
    }
    public Long getFiIdHoso() {
        return this.fiIdHoso;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : FI_MA_HOSO ( VARCHAR2 ) 
    public void setFiMaHoso( String fiMaHoso ) {
        this.fiMaHoso = fiMaHoso;
    }
    public String getFiMaHoso() {
        return this.fiMaHoso;
    }

    //--- DATABASE MAPPING : FI_SO_VB_DN ( VARCHAR2 ) 
    public void setFiSoVbDn( String fiSoVbDn ) {
        this.fiSoVbDn = fiSoVbDn;
    }
    public String getFiSoVbDn() {
        return this.fiSoVbDn;
    }

    //--- DATABASE MAPPING : FI_MA_DV_NHAN ( VARCHAR2 ) 
    public void setFiMaDvNhan( String fiMaDvNhan ) {
        this.fiMaDvNhan = fiMaDvNhan;
    }
    public String getFiMaDvNhan() {
        return this.fiMaDvNhan;
    }

    //--- DATABASE MAPPING : FI_TEN_DV_NHAN ( VARCHAR2 ) 
    public void setFiTenDvNhan( String fiTenDvNhan ) {
        this.fiTenDvNhan = fiTenDvNhan;
    }
    public String getFiTenDvNhan() {
        return this.fiTenDvNhan;
    }

    //--- DATABASE MAPPING : FI_MST_DN ( VARCHAR2 ) 
    public void setFiMstDn( String fiMstDn ) {
        this.fiMstDn = fiMstDn;
    }
    public String getFiMstDn() {
        return this.fiMstDn;
    }

    //--- DATABASE MAPPING : FI_TEN_DN ( VARCHAR2 ) 
    public void setFiTenDn( String fiTenDn ) {
        this.fiTenDn = fiTenDn;
    }
    public String getFiTenDn() {
        return this.fiTenDn;
    }

    //--- DATABASE MAPPING : FI_DIACHI_DN ( VARCHAR2 ) 
    public void setFiDiachiDn( String fiDiachiDn ) {
        this.fiDiachiDn = fiDiachiDn;
    }
    public String getFiDiachiDn() {
        return this.fiDiachiDn;
    }

    //--- DATABASE MAPPING : FI_TEN_TINH ( VARCHAR2 ) 
    public void setFiTenTinh( String fiTenTinh ) {
        this.fiTenTinh = fiTenTinh;
    }
    public String getFiTenTinh() {
        return this.fiTenTinh;
    }

    //--- DATABASE MAPPING : FI_MA_TINH ( VARCHAR2 ) 
    public void setFiMaTinh( String fiMaTinh ) {
        this.fiMaTinh = fiMaTinh;
    }
    public String getFiMaTinh() {
        return this.fiMaTinh;
    }

    //--- DATABASE MAPPING : FI_TEN_QUAN ( VARCHAR2 ) 
    public void setFiTenQuan( String fiTenQuan ) {
        this.fiTenQuan = fiTenQuan;
    }
    public String getFiTenQuan() {
        return this.fiTenQuan;
    }

    //--- DATABASE MAPPING : FI_MA_QUAN ( VARCHAR2 ) 
    public void setFiMaQuan( String fiMaQuan ) {
        this.fiMaQuan = fiMaQuan;
    }
    public String getFiMaQuan() {
        return this.fiMaQuan;
    }

    //--- DATABASE MAPPING : FI_LOAIHINH ( VARCHAR2 ) 
    public void setFiLoaihinh( String fiLoaihinh ) {
        this.fiLoaihinh = fiLoaihinh;
    }
    public String getFiLoaihinh() {
        return this.fiLoaihinh;
    }

    //--- DATABASE MAPPING : FI_PBAN_QUANLY ( VARCHAR2 ) 
    public void setFiPbanQuanly( String fiPbanQuanly ) {
        this.fiPbanQuanly = fiPbanQuanly;
    }
    public String getFiPbanQuanly() {
        return this.fiPbanQuanly;
    }

    //--- DATABASE MAPPING : FI_TEN_DN_EN ( VARCHAR2 ) 
    public void setFiTenDnEn( String fiTenDnEn ) {
        this.fiTenDnEn = fiTenDnEn;
    }
    public String getFiTenDnEn() {
        return this.fiTenDnEn;
    }

    //--- DATABASE MAPPING : FI_TEN_VTAT ( VARCHAR2 ) 
    public void setFiTenVtat( String fiTenVtat ) {
        this.fiTenVtat = fiTenVtat;
    }
    public String getFiTenVtat() {
        return this.fiTenVtat;
    }

    //--- DATABASE MAPPING : FI_SO_DKKD ( VARCHAR2 ) 
    public void setFiSoDkkd( String fiSoDkkd ) {
        this.fiSoDkkd = fiSoDkkd;
    }
    public String getFiSoDkkd() {
        return this.fiSoDkkd;
    }

    //--- DATABASE MAPPING : FI_NAM_TLAP ( NUMBER ) 
    public void setFiNamTlap( Long fiNamTlap ) {
        this.fiNamTlap = fiNamTlap;
    }
    public Long getFiNamTlap() {
        return this.fiNamTlap;
    }

    //--- DATABASE MAPPING : FI_WEB_DN ( VARCHAR2 ) 
    public void setFiWebDn( String fiWebDn ) {
        this.fiWebDn = fiWebDn;
    }
    public String getFiWebDn() {
        return this.fiWebDn;
    }

    //--- DATABASE MAPPING : FI_SDT_DN ( VARCHAR2 ) 
    public void setFiSdtDn( String fiSdtDn ) {
        this.fiSdtDn = fiSdtDn;
    }
    public String getFiSdtDn() {
        return this.fiSdtDn;
    }

    //--- DATABASE MAPPING : FI_FAX_DN ( VARCHAR2 ) 
    public void setFiFaxDn( String fiFaxDn ) {
        this.fiFaxDn = fiFaxDn;
    }
    public String getFiFaxDn() {
        return this.fiFaxDn;
    }

    //--- DATABASE MAPPING : FI_EMAIL_DN ( VARCHAR2 ) 
    public void setFiEmailDn( String fiEmailDn ) {
        this.fiEmailDn = fiEmailDn;
    }
    public String getFiEmailDn() {
        return this.fiEmailDn;
    }

    //--- DATABASE MAPPING : FI_TEN_NDD ( VARCHAR2 ) 
    public void setFiTenNdd( String fiTenNdd ) {
        this.fiTenNdd = fiTenNdd;
    }
    public String getFiTenNdd() {
        return this.fiTenNdd;
    }

    //--- DATABASE MAPPING : FI_SO_CMND_NDD ( VARCHAR2 ) 
    public void setFiSoCmndNdd( String fiSoCmndNdd ) {
        this.fiSoCmndNdd = fiSoCmndNdd;
    }
    public String getFiSoCmndNdd() {
        return this.fiSoCmndNdd;
    }

    //--- DATABASE MAPPING : FI_NGAYCAP_CMND ( TIMESTAMP(6) ) 
    public void setFiNgaycapCmnd( Date fiNgaycapCmnd ) {
        this.fiNgaycapCmnd = fiNgaycapCmnd;
    }
    public Date getFiNgaycapCmnd() {
        return this.fiNgaycapCmnd;
    }

    //--- DATABASE MAPPING : FI_NOI_CAP_CMND ( VARCHAR2 ) 
    public void setFiNoiCapCmnd( String fiNoiCapCmnd ) {
        this.fiNoiCapCmnd = fiNoiCapCmnd;
    }
    public String getFiNoiCapCmnd() {
        return this.fiNoiCapCmnd;
    }

    //--- DATABASE MAPPING : FI_SDT_CODINH ( VARCHAR2 ) 
    public void setFiSdtCodinh( String fiSdtCodinh ) {
        this.fiSdtCodinh = fiSdtCodinh;
    }
    public String getFiSdtCodinh() {
        return this.fiSdtCodinh;
    }

    //--- DATABASE MAPPING : FI_SDT_DD ( VARCHAR2 ) 
    public void setFiSdtDd( String fiSdtDd ) {
        this.fiSdtDd = fiSdtDd;
    }
    public String getFiSdtDd() {
        return this.fiSdtDd;
    }

    //--- DATABASE MAPPING : FI_LOAI_TTB ( VARCHAR2 ) 
    public void setFiLoaiTtb( String fiLoaiTtb ) {
        this.fiLoaiTtb = fiLoaiTtb;
    }
    public String getFiLoaiTtb() {
        return this.fiLoaiTtb;
    }

    //--- DATABASE MAPPING : FI_LOAI_HS_TTB ( VARCHAR2 ) 
    public void setFiLoaiHsTtb( String fiLoaiHsTtb ) {
        this.fiLoaiHsTtb = fiLoaiHsTtb;
    }
    public String getFiLoaiHsTtb() {
        return this.fiLoaiHsTtb;
    }

    //--- DATABASE MAPPING : FI_MA_MDICH_NK ( VARCHAR2 ) 
    public void setFiMaMdichNk( String fiMaMdichNk ) {
        this.fiMaMdichNk = fiMaMdichNk;
    }
    public String getFiMaMdichNk() {
        return this.fiMaMdichNk;
    }

    //--- DATABASE MAPPING : FI_TEN_MDICH_NK ( VARCHAR2 ) 
    public void setFiTenMdichNk( String fiTenMdichNk ) {
        this.fiTenMdichNk = fiTenMdichNk;
    }
    public String getFiTenMdichNk() {
        return this.fiTenMdichNk;
    }

    //--- DATABASE MAPPING : FI_DONVI_SD ( VARCHAR2 ) 
    public void setFiDonviSd( String fiDonviSd ) {
        this.fiDonviSd = fiDonviSd;
    }
    public String getFiDonviSd() {
        return this.fiDonviSd;
    }

    //--- DATABASE MAPPING : FI_HOATDONG ( NUMBER ) 
    public void setFiHoatdong( Long fiHoatdong ) {
        this.fiHoatdong = fiHoatdong;
    }
    public Long getFiHoatdong() {
        return this.fiHoatdong;
    }

    //--- DATABASE MAPPING : FI_NGUOITAO ( VARCHAR2 ) 
    public void setFiNguoitao( String fiNguoitao ) {
        this.fiNguoitao = fiNguoitao;
    }
    public String getFiNguoitao() {
        return this.fiNguoitao;
    }

    //--- DATABASE MAPPING : FI_NGAYTAO ( TIMESTAMP(6) ) 
    public void setFiNgaytao( Date fiNgaytao ) {
        this.fiNgaytao = fiNgaytao;
    }
    public Date getFiNgaytao() {
        return this.fiNgaytao;
    }

    //--- DATABASE MAPPING : FI_NG_CAPNHAT ( TIMESTAMP(6) ) 
    public void setFiNgCapnhat( Date fiNgCapnhat ) {
        this.fiNgCapnhat = fiNgCapnhat;
    }
    public Date getFiNgCapnhat() {
        return this.fiNgCapnhat;
    }

    //--- DATABASE MAPPING : FI_TRANGTHAI ( NUMBER ) 
    public void setFiTrangthai( Long fiTrangthai ) {
        this.fiTrangthai = fiTrangthai;
    }
    public Long getFiTrangthai() {
        return this.fiTrangthai;
    }

    //--- DATABASE MAPPING : FI_TEN_TT ( VARCHAR2 ) 
    public void setFiTenTt( String fiTenTt ) {
        this.fiTenTt = fiTenTt;
    }
    public String getFiTenTt() {
        return this.fiTenTt;
    }

    //--- DATABASE MAPPING : FI_NGAYNOP ( TIMESTAMP(6) ) 
    public void setFiNgaynop( Date fiNgaynop ) {
        this.fiNgaynop = fiNgaynop;
    }
    public Date getFiNgaynop() {
        return this.fiNgaynop;
    }

    //--- DATABASE MAPPING : FI_SO_CHUNGNHAN ( VARCHAR2 ) 
    public void setFiSoChungnhan( String fiSoChungnhan ) {
        this.fiSoChungnhan = fiSoChungnhan;
    }
    public String getFiSoChungnhan() {
        return this.fiSoChungnhan;
    }

    //--- DATABASE MAPPING : FI_NGAYCAP_GCN ( TIMESTAMP(6) ) 
    public void setFiNgaycapGcn( Date fiNgaycapGcn ) {
        this.fiNgaycapGcn = fiNgaycapGcn;
    }
    public Date getFiNgaycapGcn() {
        return this.fiNgaycapGcn;
    }

    //--- DATABASE MAPPING : FI_MA_THUTUC ( VARCHAR2 ) 
    public void setFiMaThutuc( String fiMaThutuc ) {
        this.fiMaThutuc = fiMaThutuc;
    }
    public String getFiMaThutuc() {
        return this.fiMaThutuc;
    }

    //--- DATABASE MAPPING : FI_TEN_THUTUC ( VARCHAR2 ) 
    public void setFiTenThutuc( String fiTenThutuc ) {
        this.fiTenThutuc = fiTenThutuc;
    }
    public String getFiTenThutuc() {
        return this.fiTenThutuc;
    }

    public TbdhsHanghoa10 getHangHoa() {
        return hangHoa;
    }

    public void setHangHoa(TbdhsHanghoa10 hangHoa) {
        this.hangHoa = hangHoa;
    }

    public List<Tbddinhkem10> getLstDinhKems() {
        return lstDinhKems;
    }

    public void setLstDinhKems(List<Tbddinhkem10> lstDinhKems) {
        this.lstDinhKems = lstDinhKems;
    }

    public List<TbdhsThanhtoan10> getLstThanhToans() {
        return lstThanhToans;
    }

    public void setLstThanhToans(List<TbdhsThanhtoan10> lstThanhToans) {
        this.lstThanhToans = lstThanhToans;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(fiIdHoso);
        sb.append("]:"); 
        sb.append(fiMaHoso);
        sb.append("|");
        sb.append(fiSoVbDn);
        sb.append("|");
        sb.append(fiMaDvNhan);
        sb.append("|");
        sb.append(fiTenDvNhan);
        sb.append("|");
        sb.append(fiMstDn);
        sb.append("|");
        sb.append(fiTenDn);
        sb.append("|");
        sb.append(fiDiachiDn);
        sb.append("|");
        sb.append(fiTenTinh);
        sb.append("|");
        sb.append(fiMaTinh);
        sb.append("|");
        sb.append(fiTenQuan);
        sb.append("|");
        sb.append(fiMaQuan);
        sb.append("|");
        sb.append(fiLoaihinh);
        sb.append("|");
        sb.append(fiPbanQuanly);
        sb.append("|");
        sb.append(fiTenDnEn);
        sb.append("|");
        sb.append(fiTenVtat);
        sb.append("|");
        sb.append(fiSoDkkd);
        sb.append("|");
        sb.append(fiNamTlap);
        sb.append("|");
        sb.append(fiWebDn);
        sb.append("|");
        sb.append(fiSdtDn);
        sb.append("|");
        sb.append(fiFaxDn);
        sb.append("|");
        sb.append(fiEmailDn);
        sb.append("|");
        sb.append(fiTenNdd);
        sb.append("|");
        sb.append(fiSoCmndNdd);
        sb.append("|");
        sb.append(fiNgaycapCmnd);
        sb.append("|");
        sb.append(fiNoiCapCmnd);
        sb.append("|");
        sb.append(fiSdtCodinh);
        sb.append("|");
        sb.append(fiSdtDd);
        sb.append("|");
        sb.append(fiLoaiTtb);
        sb.append("|");
        sb.append(fiLoaiHsTtb);
        sb.append("|");
        sb.append(fiMaMdichNk);
        sb.append("|");
        sb.append(fiTenMdichNk);
        sb.append("|");
        sb.append(fiDonviSd);
        sb.append("|");
        sb.append(fiHoatdong);
        sb.append("|");
        sb.append(fiNguoitao);
        sb.append("|");
        sb.append(fiNgaytao);
        sb.append("|");
        sb.append(fiNgCapnhat);
        sb.append("|");
        sb.append(fiTrangthai);
        sb.append("|");
        sb.append(fiTenTt);
        sb.append("|");
        sb.append(fiNgaynop);
        sb.append("|");
        sb.append(fiSoChungnhan);
        sb.append("|");
        sb.append(fiNgaycapGcn);
        sb.append("|");
        sb.append(fiMaThutuc);
        sb.append("|");
        sb.append(fiTenThutuc);
        return sb.toString(); 
    } 

}
