/*
 * Created on 15 Apr 2019 ( Time 10:10:24 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 
package com.nsw.moh.p09.model;

import java.io.Serializable;

import java.util.Date;

public class Tbddinhkem9 implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    private Long fiIdDinhKem;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    //@Column(name="FI_ID_DT")
    private Long fiIdDt;

    //@Column(name="FI_LOAI_DT")
    private Long fiLoaiDt;

    //@Column(name="FI_MA_TEP", length=250)
    private String fiMaTep;

    //@Column(name="FI_LOAI_TEP")
    private Long fiLoaiTep;

    //@Column(name="FI_TEN_LOAI_TEP", length=250)
    private String fiTenLoaiTep;

    //@Column(name="FI_TEN_TEP", length=50)
    private String fiTenTep;

    //@Column(name="FI_DUONG_DAN", length=500)
    private String fiDuongDan;

    //@Column(name="FI_HOATDONG")
    private Long fiHoatdong;

    //@Column(name="FI_NGUOITAO", length=50)
    private String fiNguoitao;

    //@Temporal(TemporalType.TIMESTAMP)
    //@Column(name="FI_NGAYTAO")
    private Date fiNgaytao;

    //@Temporal(TemporalType.TIMESTAMP)
    //@Column(name="FI_NG_CAPNHAT")
    private Date fiNgCapnhat;

    //@Column(name="FI_PATH_LOCAL", length=2000)
    private String fiPathLocal;

    //@Column(name="FI_GUI_ID", length=2000)
    private String fiGuiId;

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Tbddinhkem9() {
        super();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setFiIdDinhKem(Long fiIdDinhKem) {
        this.fiIdDinhKem = fiIdDinhKem;
    }

    public Long getFiIdDinhKem() {
        return this.fiIdDinhKem;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : FI_ID_DT ( NUMBER ) 
    public void setFiIdDt(Long fiIdDt) {
        this.fiIdDt = fiIdDt;
    }

    public Long getFiIdDt() {
        return this.fiIdDt;
    }

    //--- DATABASE MAPPING : FI_LOAI_DT ( NUMBER ) 
    public void setFiLoaiDt(Long fiLoaiDt) {
        this.fiLoaiDt = fiLoaiDt;
    }

    public Long getFiLoaiDt() {
        return this.fiLoaiDt;
    }

    //--- DATABASE MAPPING : FI_MA_TEP ( VARCHAR2 ) 
    public void setFiMaTep(String fiMaTep) {
        this.fiMaTep = fiMaTep;
    }

    public String getFiMaTep() {
        return this.fiMaTep;
    }

    //--- DATABASE MAPPING : FI_LOAI_TEP ( NUMBER ) 
    public void setFiLoaiTep(Long fiLoaiTep) {
        this.fiLoaiTep = fiLoaiTep;
    }

    public Long getFiLoaiTep() {
        return this.fiLoaiTep;
    }

    //--- DATABASE MAPPING : FI_TEN_LOAI_TEP ( VARCHAR2 ) 
    public void setFiTenLoaiTep(String fiTenLoaiTep) {
        this.fiTenLoaiTep = fiTenLoaiTep;
    }

    public String getFiTenLoaiTep() {
        return this.fiTenLoaiTep;
    }

    //--- DATABASE MAPPING : FI_TEN_TEP ( VARCHAR2 ) 
    public void setFiTenTep(String fiTenTep) {
        this.fiTenTep = fiTenTep;
    }

    public String getFiTenTep() {
        return this.fiTenTep;
    }

    //--- DATABASE MAPPING : FI_DUONG_DAN ( VARCHAR2 ) 
    public void setFiDuongDan(String fiDuongDan) {
        this.fiDuongDan = fiDuongDan;
    }

    public String getFiDuongDan() {
        return this.fiDuongDan;
    }

    //--- DATABASE MAPPING : FI_HOATDONG ( NUMBER ) 
    public void setFiHoatdong(Long fiHoatdong) {
        this.fiHoatdong = fiHoatdong;
    }

    public Long getFiHoatdong() {
        return this.fiHoatdong;
    }

    //--- DATABASE MAPPING : FI_NGUOITAO ( VARCHAR2 ) 
    public void setFiNguoitao(String fiNguoitao) {
        this.fiNguoitao = fiNguoitao;
    }

    public String getFiNguoitao() {
        return this.fiNguoitao;
    }

    //--- DATABASE MAPPING : FI_NGAYTAO ( TIMESTAMP(6) ) 
    public void setFiNgaytao(Date fiNgaytao) {
        this.fiNgaytao = fiNgaytao;
    }

    public Date getFiNgaytao() {
        return this.fiNgaytao;
    }

    //--- DATABASE MAPPING : FI_NG_CAPNHAT ( TIMESTAMP(6) ) 
    public void setFiNgCapnhat(Date fiNgCapnhat) {
        this.fiNgCapnhat = fiNgCapnhat;
    }

    public Date getFiNgCapnhat() {
        return this.fiNgCapnhat;
    }

    //--- DATABASE MAPPING : FI_PATH_LOCAL ( VARCHAR2 ) 
    public void setFiPathLocal(String fiPathLocal) {
        this.fiPathLocal = fiPathLocal;
    }

    public String getFiPathLocal() {
        return this.fiPathLocal;
    }

    //--- DATABASE MAPPING : FI_GUI_ID ( VARCHAR2 ) 
    public void setFiGuiId(String fiGuiId) {
        this.fiGuiId = fiGuiId;
    }

    public String getFiGuiId() {
        return this.fiGuiId;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("[");
        sb.append(fiIdDinhKem);
        sb.append("]:");
        sb.append(fiIdDt);
        sb.append("|");
        sb.append(fiLoaiDt);
        sb.append("|");
        sb.append(fiMaTep);
        sb.append("|");
        sb.append(fiLoaiTep);
        sb.append("|");
        sb.append(fiTenLoaiTep);
        sb.append("|");
        sb.append(fiTenTep);
        sb.append("|");
        sb.append(fiDuongDan);
        sb.append("|");
        sb.append(fiHoatdong);
        sb.append("|");
        sb.append(fiNguoitao);
        sb.append("|");
        sb.append(fiNgaytao);
        sb.append("|");
        sb.append(fiNgCapnhat);
        sb.append("|");
        sb.append(fiPathLocal);
        sb.append("|");
        sb.append(fiGuiId);
        return sb.toString();
    }

}
