/*
 * Created on 3 Jul 2019 ( Time 11:46:49 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 
package com.nsw.moh.p09.model;

import java.io.Serializable;

import java.util.Date;

public class TbdhsNguoiTn9 implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    private Long fiIdNguoiTn;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    //@Column(name="FI_ID_HOSO")
    private Long fiIdHoso;

    //@Column(name="FI_TEN_NG_TN", length=255)
    private String fiTenNgTn;

    //@Column(name="FI_DIACHI_NG_TN", length=500)
    private String fiDiachiNgTn;

    //@Column(name="FI_SDT_NG_TN", length=50)
    private String fiSdtNgTn;

    //@Column(name="FI_FAX_NG_TN", length=50)
    private String fiFaxNgTn;

    //@Column(name="FI_EMAIL_NG_TN", length=255)
    private String fiEmailNgTn;

    //@Column(name="FI_HOATDONG")
    private Long fiHoatdong;

    //@Column(name="FI_NGUOITAO", length=50)
    private String fiNguoitao;

    //@Temporal(TemporalType.TIMESTAMP)
    //@Column(name="FI_NGAYTAO")
    private Date fiNgaytao;

    //@Temporal(TemporalType.TIMESTAMP)
    //@Column(name="FI_NG_CAPNHAT")
    private Date fiNgCapnhat;

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TbdhsNguoiTn9() {
        super();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setFiIdNguoiTn(Long fiIdNguoiTn) {
        this.fiIdNguoiTn = fiIdNguoiTn;
    }

    public Long getFiIdNguoiTn() {
        return this.fiIdNguoiTn;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : FI_ID_HOSO ( NUMBER ) 
    public void setFiIdHoso(Long fiIdHoso) {
        this.fiIdHoso = fiIdHoso;
    }

    public Long getFiIdHoso() {
        return this.fiIdHoso;
    }

    //--- DATABASE MAPPING : FI_TEN_NG_TN ( VARCHAR2 ) 
    public void setFiTenNgTn(String fiTenNgTn) {
        this.fiTenNgTn = fiTenNgTn;
    }

    public String getFiTenNgTn() {
        return this.fiTenNgTn;
    }

    //--- DATABASE MAPPING : FI_DIACHI_NG_TN ( VARCHAR2 ) 
    public void setFiDiachiNgTn(String fiDiachiNgTn) {
        this.fiDiachiNgTn = fiDiachiNgTn;
    }

    public String getFiDiachiNgTn() {
        return this.fiDiachiNgTn;
    }

    //--- DATABASE MAPPING : FI_SDT_NG_TN ( VARCHAR2 ) 
    public void setFiSdtNgTn(String fiSdtNgTn) {
        this.fiSdtNgTn = fiSdtNgTn;
    }

    public String getFiSdtNgTn() {
        return this.fiSdtNgTn;
    }

    //--- DATABASE MAPPING : FI_FAX_NG_TN ( VARCHAR2 ) 
    public void setFiFaxNgTn(String fiFaxNgTn) {
        this.fiFaxNgTn = fiFaxNgTn;
    }

    public String getFiFaxNgTn() {
        return this.fiFaxNgTn;
    }

    //--- DATABASE MAPPING : FI_EMAIL_NG_TN ( VARCHAR2 ) 
    public void setFiEmailNgTn(String fiEmailNgTn) {
        this.fiEmailNgTn = fiEmailNgTn;
    }

    public String getFiEmailNgTn() {
        return this.fiEmailNgTn;
    }

    //--- DATABASE MAPPING : FI_HOATDONG ( NUMBER ) 
    public void setFiHoatdong(Long fiHoatdong) {
        this.fiHoatdong = fiHoatdong;
    }

    public Long getFiHoatdong() {
        return this.fiHoatdong;
    }

    //--- DATABASE MAPPING : FI_NGUOITAO ( VARCHAR2 ) 
    public void setFiNguoitao(String fiNguoitao) {
        this.fiNguoitao = fiNguoitao;
    }

    public String getFiNguoitao() {
        return this.fiNguoitao;
    }

    //--- DATABASE MAPPING : FI_NGAYTAO ( TIMESTAMP(6) ) 
    public void setFiNgaytao(Date fiNgaytao) {
        this.fiNgaytao = fiNgaytao;
    }

    public Date getFiNgaytao() {
        return this.fiNgaytao;
    }

    //--- DATABASE MAPPING : FI_NG_CAPNHAT ( TIMESTAMP(6) ) 
    public void setFiNgCapnhat(Date fiNgCapnhat) {
        this.fiNgCapnhat = fiNgCapnhat;
    }

    public Date getFiNgCapnhat() {
        return this.fiNgCapnhat;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("[");
        sb.append(fiIdNguoiTn);
        sb.append("]:");
        sb.append(fiIdHoso);
        sb.append("|");
        sb.append(fiTenNgTn);
        sb.append("|");
        sb.append(fiDiachiNgTn);
        sb.append("|");
        sb.append(fiSdtNgTn);
        sb.append("|");
        sb.append(fiFaxNgTn);
        sb.append("|");
        sb.append(fiEmailNgTn);
        sb.append("|");
        sb.append(fiHoatdong);
        sb.append("|");
        sb.append(fiNguoitao);
        sb.append("|");
        sb.append(fiNgaytao);
        sb.append("|");
        sb.append(fiNgCapnhat);
        return sb.toString();
    }

}
