/*
 * Created on 5 May 2017 ( Time 10:32:38 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.nsw.backend.mard.p06.service;


import com.nsw.backend.mard.p06.model.TbdLichsu06;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;

import java.util.List;

/**
 * Business Service Interface for entity TbdLichsu06.
 */
public interface TbdLichsu06Service {

    /**
     * Loads an entity from the database using its Primary Key
     *
     * @param fiIdLichsu
     * @return entity
     */
    TbdLichsu06 findById(Long fiIdLichsu);

    /**
     * Loads all entities.
     *
     * @return all entities
     */
    List<TbdLichsu06> findAll();

    /**
     * Saves the given entity in the database (create or update)
     *
     * @param entity
     * @return entity
     */
    TbdLichsu06 save(TbdLichsu06 entity);

    /**
     * Updates the given entity in the database
     *
     * @param entity
     * @return
     */
    TbdLichsu06 update(TbdLichsu06 entity);

    /**
     * Creates the given entity in the database
     *
     * @param entity
     * @return
     */
    TbdLichsu06 create(TbdLichsu06 entity);

    List<TbdLichsu06> findByIdHS(long id);

    List<TbdLichsu06> findByHSCode(String fiMaHoso);

    Page<TbdLichsu06> findByHSCodeAndPagable(String fiHSCode, PageRequest pageRequest);
}
